global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics from your application
  - job_name: 'blitz-backend'
    static_configs:
      - targets: ['host.docker.internal:7070']
        labels:
          service: 'blitz-backend'
  
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # Scrape Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']