// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brands.sql

package pgmain

import (
	"context"

	"github.com/google/uuid"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (
  name
) VALUES (
  $1
)
RETURNING id, name, brand_db_id, created_at, updated_at
`

func (q *Queries) CreateBrand(ctx context.Context, name string) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand, name)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BrandDbID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name, brand_db_id, created_at, updated_at
FROM brands
WHERE id = $1
`

func (q *Queries) GetBrandByID(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BrandDbID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, brand_db_id, created_at, updated_at
FROM brands
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListBrandsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBrands(ctx context.Context, arg ListBrandsParams) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BrandDbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
