CREATE TABLE IF NOT EXISTS cources (
    id SERIAL PRIMARY KEY,
    guid UUID NOT NULL DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);