ALTER TABLE cafe_tables
  DROP COLUMN IF EXISTS pos_x,
  DROP COLUMN IF EXISTS pos_y,
  DROP COLUMN IF EXISTS width,
  DROP COLUMN IF EXISTS height,
  DROP COLUMN IF EXISTS rotation;

ALTER TABLE halls
  DROP COLUMN IF EXISTS width,
  DROP COLUMN IF EXISTS height;
