ALTER TABLE halls
  ADD COLUMN IF NOT EXISTS width INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS height INTEGER NOT NULL DEFAULT 0;

ALTER TABLE cafe_tables
  ADD COLUMN IF NOT EXISTS pos_x INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pos_y INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS width INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS height INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rotation INTEGER NOT NULL DEFAULT 0;
