DROP TRIGGER IF EXISTS trg_change_log_attendances ON attendances;
DROP TRIGGER IF EXISTS trg_change_log_bill_daily_counters ON bill_daily_counters;
DROP TRIGGER IF EXISTS trg_change_log_branches ON branches;
DROP TRIGGER IF EXISTS trg_change_log_cafe_tables ON cafe_tables;
DROP TRIGGER IF EXISTS trg_change_log_calculation ON calculation;
DROP TRIGGER IF EXISTS trg_change_log_categories ON categories;
DROP TRIGGER IF EXISTS trg_change_log_compounds ON compounds;
DROP TRIGGER IF EXISTS trg_change_log_compounds_details ON compounds_details;
DROP TRIGGER IF EXISTS trg_change_log_compound_stock ON compound_stock;
DROP TRIGGER IF EXISTS trg_change_log_deduction_act_groups ON deduction_act_groups;
DROP TRIGGER IF EXISTS trg_change_log_deduction_item_ingredients ON deduction_item_ingredients;
DROP TRIGGER IF EXISTS trg_change_log_deduction_items ON deduction_items;
DROP TRIGGER IF EXISTS trg_change_log_deductions ON deductions;
DROP TRIGGER IF EXISTS trg_change_log_departments ON departments;
DROP TRIGGER IF EXISTS trg_change_log_goods ON goods;
DROP TRIGGER IF EXISTS trg_change_log_goods_details ON goods_details;
DROP TRIGGER IF EXISTS trg_change_log_halls ON halls;
DROP TRIGGER IF EXISTS trg_change_log_ingredient_groups ON ingredient_groups;
DROP TRIGGER IF EXISTS trg_change_log_ingredients ON ingredients;
DROP TRIGGER IF EXISTS trg_change_log_ingredient_stock ON ingredient_stock;
DROP TRIGGER IF EXISTS trg_change_log_ingredient_stock_movements ON ingredient_stock_movements;
DROP TRIGGER IF EXISTS trg_change_log_inventories ON inventories;
DROP TRIGGER IF EXISTS trg_change_log_inventory_items ON inventory_items;
DROP TRIGGER IF EXISTS trg_change_log_invoice_detailed ON invoice_detailed;
DROP TRIGGER IF EXISTS trg_change_log_invoices ON invoices;
DROP TRIGGER IF EXISTS trg_change_log_order_items ON order_items;
DROP TRIGGER IF EXISTS trg_change_log_orders ON orders;
DROP TRIGGER IF EXISTS trg_change_log_shifts ON shifts;
DROP TRIGGER IF EXISTS trg_change_log_storages ON storages;
DROP TRIGGER IF EXISTS trg_change_log_suppliers ON suppliers;
DROP TRIGGER IF EXISTS trg_change_log_translations ON translations;
DROP TRIGGER IF EXISTS trg_change_log_user_payments ON user_payments;
DROP TRIGGER IF EXISTS trg_change_log_users ON users;

DROP FUNCTION IF EXISTS log_change();
DROP TABLE IF EXISTS change_log;
