// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*)
FROM categories c
LEFT JOIN departments d
    ON c.department_id = d.id
   AND d.deleted_at = 0
LEFT JOIN translations t
    ON c.name_i18n = t.id
   AND t.deleted_at = 0
WHERE c.deleted_at = 0
  AND (
        $1::text = ''
        OR COALESCE(c.name, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(t.uz, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(t.ru, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(t.en, '') ILIKE '%' || $1::text || '%'
      )
  AND (
        $2::uuid IS NULL
        OR c.department_id = $2::uuid
      )
  AND (
        $3::uuid IS NULL
        OR d.storage_id = $3::uuid
      )
  AND EXISTS (
        SELECT 1
        FROM storages s
        WHERE s.id = d.storage_id
          AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
      )
`

type CountCategoriesParams struct {
	Search       string      `json:"search"`
	DepartmentID pgtype.UUID `json:"department_id"`
	StorageID    pgtype.UUID `json:"storage_id"`
}

func (q *Queries) CountCategories(ctx context.Context, arg CountCategoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, arg.Search, arg.DepartmentID, arg.StorageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesByDepartment = `-- name: CountCategoriesByDepartment :one
SELECT COUNT(*) FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE c.department_id = $1 AND c.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = d.storage_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) CountCategoriesByDepartment(ctx context.Context, departmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesByDepartment, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesByIDs = `-- name: CountCategoriesByIDs :one
SELECT COUNT(*)::BIGINT
FROM categories
WHERE deleted_at = 0
  AND id IN (
    SELECT x::uuid
    FROM unnest($1::text[]) AS x
  )
`

func (q *Queries) CountCategoriesByIDs(ctx context.Context, ids []string) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesByIDs, ids)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCategoriesByParent = `-- name: CountCategoriesByParent :one
SELECT COUNT(*) FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE c.parent = $1 AND c.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = d.storage_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) CountCategoriesByParent(ctx context.Context, parent pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesByParent, parent)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesByStorage = `-- name: CountCategoriesByStorage :one
SELECT COUNT(*) FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE c.deleted_at = 0
  AND d.storage_id = $1
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = $1
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) CountCategoriesByStorage(ctx context.Context, storageID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesByStorage, storageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesWithLanguage = `-- name: CountCategoriesWithLanguage :one
SELECT COUNT(*)
FROM categories c
LEFT JOIN departments d
    ON c.department_id = d.id
   AND d.deleted_at = 0
LEFT JOIN translations t
    ON c.name_i18n = t.id
   AND t.deleted_at = 0
WHERE c.deleted_at = 0
  AND (
        $1::text = ''
        OR COALESCE(c.name, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(t.uz, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(t.ru, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(t.en, '') ILIKE '%' || $1::text || '%'
      )
  AND (
        $2::uuid IS NULL
        OR c.department_id = $2::uuid
      )
  AND (
        $3::uuid IS NULL
        OR d.storage_id = $3::uuid
      )
  AND EXISTS (
        SELECT 1
        FROM storages s
        WHERE s.id = d.storage_id
          AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
      )
`

type CountCategoriesWithLanguageParams struct {
	Search       string      `json:"search"`
	DepartmentID pgtype.UUID `json:"department_id"`
	StorageID    pgtype.UUID `json:"storage_id"`
}

func (q *Queries) CountCategoriesWithLanguage(ctx context.Context, arg CountCategoriesWithLanguageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesWithLanguage, arg.Search, arg.DepartmentID, arg.StorageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRootCategories = `-- name: CountRootCategories :one
SELECT COUNT(*) FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE c.parent IS NULL AND c.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = d.storage_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) CountRootCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRootCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, name, picture_url, name_i18n, department_id, parent, color_code)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE $5 IS NOT NULL AND EXISTS (
  SELECT 1 FROM departments dep
  JOIN storages s ON s.id = dep.storage_id
  WHERE dep.id = $5
    AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
)
RETURNING id, name, picture_url, color_code, name_i18n, department_id,
  (SELECT dep.storage_id FROM departments dep WHERE dep.id = department_id AND dep.deleted_at = 0) as storage_id,
  parent, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	PictureUrl   *string     `json:"picture_url"`
	NameI18n     pgtype.UUID `json:"name_i18n"`
	DepartmentID pgtype.UUID `json:"department_id"`
	Parent       pgtype.UUID `json:"parent"`
	ColorCode    *string     `json:"color_code"`
}

type CreateCategoryRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.PictureUrl,
		arg.NameI18n,
		arg.DepartmentID,
		arg.Parent,
		arg.ColorCode,
	)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.ColorCode,
		&i.NameI18n,
		&i.DepartmentID,
		&i.StorageID,
		&i.Parent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE categories.id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM departments d
    JOIN storages s ON s.id = d.storage_id
    WHERE d.id = categories.department_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT
    c.id,
    c.name,
    c.picture_url,
    c.color_code,
    c.name_i18n,
    c.department_id,
    d.storage_id,
    c.parent,
    c.created_at,
    c.updated_at,
    c.deleted_at
FROM categories c
LEFT JOIN departments d
    ON c.department_id = d.id
   AND d.deleted_at = 0
LEFT JOIN translations t
    ON c.name_i18n = t.id
   AND t.deleted_at = 0
WHERE c.deleted_at = 0
  AND (
        $1::text = ''
        OR COALESCE(c.name, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(t.uz, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(t.ru, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(t.en, '') ILIKE '%' || $1::text || '%'
      )
  AND (
        $2::uuid IS NULL
        OR c.department_id = $2::uuid
      )
  AND (
        $3::uuid IS NULL
        OR d.storage_id = $3::uuid
      )
  AND EXISTS (
        SELECT 1
        FROM storages s
        WHERE s.id = d.storage_id
          AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
      )
ORDER BY
    CASE
        WHEN $4::text = 'name' AND $5::text = 'asc'
        THEN c.name
    END ASC,
    CASE
        WHEN $4::text = 'name' AND $5::text = 'desc'
        THEN c.name
    END DESC,
    CASE
        WHEN $4::text = 'created_at' AND $5::text = 'asc'
        THEN c.created_at
    END ASC,
    CASE
        WHEN $4::text = 'created_at' AND $5::text = 'desc'
        THEN c.created_at
    END DESC,
    c.created_at DESC
LIMIT $7::int
OFFSET $6::int
`

type GetAllCategoriesParams struct {
	Search       string      `json:"search"`
	DepartmentID pgtype.UUID `json:"department_id"`
	StorageID    pgtype.UUID `json:"storage_id"`
	SortBy       string      `json:"sort_by"`
	SortOrder    string      `json:"sort_order"`
	Offset       int32       `json:"offset"`
	Limit        int32       `json:"limit"`
}

type GetAllCategoriesRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) GetAllCategories(ctx context.Context, arg GetAllCategoriesParams) ([]GetAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getAllCategories,
		arg.Search,
		arg.DepartmentID,
		arg.StorageID,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCategoriesRow
	for rows.Next() {
		var i GetAllCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.ColorCode,
			&i.NameI18n,
			&i.DepartmentID,
			&i.StorageID,
			&i.Parent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategoriesWithLanguage = `-- name: GetAllCategoriesWithLanguage :many
SELECT
    c.id,
    COALESCE(
        CASE
            WHEN $1::text = 'uz' THEN t.uz
            WHEN $1::text = 'ru' THEN t.ru
            WHEN $1::text = 'en' THEN t.en
            ELSE c.name
        END,
        c.name
    ) AS name,
    c.picture_url,
    c.color_code,
    c.name_i18n,
    c.department_id,
    d.storage_id,
    c.parent,
    c.created_at,
    c.updated_at,
    c.deleted_at
FROM categories c
LEFT JOIN departments d
    ON c.department_id = d.id
   AND d.deleted_at = 0
LEFT JOIN translations t
    ON c.name_i18n = t.id
   AND t.deleted_at = 0
WHERE c.deleted_at = 0
  AND (
        $2::text = ''
        OR COALESCE(c.name, '') ILIKE '%' || $2::text || '%'
        OR COALESCE(t.uz, '') ILIKE '%' || $2::text || '%'
        OR COALESCE(t.ru, '') ILIKE '%' || $2::text || '%'
        OR COALESCE(t.en, '') ILIKE '%' || $2::text || '%'
      )
  AND (
        $3::uuid IS NULL
        OR c.department_id = $3::uuid
      )
  AND (
        $4::uuid IS NULL
        OR d.storage_id = $4::uuid
      )
  AND EXISTS (
        SELECT 1
        FROM storages s
        WHERE s.id = d.storage_id
          AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
      )
ORDER BY
    CASE
        WHEN $5::text = 'name' AND $6::text = 'asc'
        THEN COALESCE(
            CASE
                WHEN $1::text = 'uz' THEN t.uz
                WHEN $1::text = 'ru' THEN t.ru
                WHEN $1::text = 'en' THEN t.en
                ELSE c.name
            END,
            c.name
        )
    END ASC,
    CASE
        WHEN $5::text = 'name' AND $6::text = 'desc'
        THEN COALESCE(
            CASE
                WHEN $1::text = 'uz' THEN t.uz
                WHEN $1::text = 'ru' THEN t.ru
                WHEN $1::text = 'en' THEN t.en
                ELSE c.name
            END,
            c.name
        )
    END DESC,
    CASE
        WHEN $5::text = 'created_at' AND $6::text = 'asc'
        THEN c.created_at
    END ASC,
    CASE
        WHEN $5::text = 'created_at' AND $6::text = 'desc'
        THEN c.created_at
    END DESC,
    c.created_at DESC
LIMIT $8::int
OFFSET $7::int
`

type GetAllCategoriesWithLanguageParams struct {
	Lang         string      `json:"lang"`
	Search       string      `json:"search"`
	DepartmentID pgtype.UUID `json:"department_id"`
	StorageID    pgtype.UUID `json:"storage_id"`
	SortBy       string      `json:"sort_by"`
	SortOrder    string      `json:"sort_order"`
	Offset       int32       `json:"offset"`
	Limit        int32       `json:"limit"`
}

type GetAllCategoriesWithLanguageRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) GetAllCategoriesWithLanguage(ctx context.Context, arg GetAllCategoriesWithLanguageParams) ([]GetAllCategoriesWithLanguageRow, error) {
	rows, err := q.db.Query(ctx, getAllCategoriesWithLanguage,
		arg.Lang,
		arg.Search,
		arg.DepartmentID,
		arg.StorageID,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCategoriesWithLanguageRow
	for rows.Next() {
		var i GetAllCategoriesWithLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.ColorCode,
			&i.NameI18n,
			&i.DepartmentID,
			&i.StorageID,
			&i.Parent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByDepartmentID = `-- name: GetCategoriesByDepartmentID :many
SELECT c.id, c.name, c.picture_url, c.color_code, c.name_i18n, c.department_id,
       d.storage_id, c.parent, c.created_at, c.updated_at, c.deleted_at
FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE c.department_id = $1 AND c.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = d.storage_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type GetCategoriesByDepartmentIDParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

type GetCategoriesByDepartmentIDRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) GetCategoriesByDepartmentID(ctx context.Context, arg GetCategoriesByDepartmentIDParams) ([]GetCategoriesByDepartmentIDRow, error) {
	rows, err := q.db.Query(ctx, getCategoriesByDepartmentID, arg.DepartmentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesByDepartmentIDRow
	for rows.Next() {
		var i GetCategoriesByDepartmentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.ColorCode,
			&i.NameI18n,
			&i.DepartmentID,
			&i.StorageID,
			&i.Parent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByParentID = `-- name: GetCategoriesByParentID :many
SELECT c.id, c.name, c.picture_url, c.color_code, c.name_i18n, c.department_id,
       d.storage_id, c.parent, c.created_at, c.updated_at, c.deleted_at
FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE c.parent = $1 AND c.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = d.storage_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type GetCategoriesByParentIDParams struct {
	Parent pgtype.UUID `json:"parent"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetCategoriesByParentIDRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) GetCategoriesByParentID(ctx context.Context, arg GetCategoriesByParentIDParams) ([]GetCategoriesByParentIDRow, error) {
	rows, err := q.db.Query(ctx, getCategoriesByParentID, arg.Parent, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesByParentIDRow
	for rows.Next() {
		var i GetCategoriesByParentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.ColorCode,
			&i.NameI18n,
			&i.DepartmentID,
			&i.StorageID,
			&i.Parent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByStorageID = `-- name: GetCategoriesByStorageID :many
SELECT c.id, c.name, c.picture_url, c.color_code, c.name_i18n, c.department_id,
       d.storage_id, c.parent, c.created_at, c.updated_at, c.deleted_at
FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE c.deleted_at = 0
  AND d.storage_id = $1
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = $1
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type GetCategoriesByStorageIDParams struct {
	StorageID pgtype.UUID `json:"storage_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type GetCategoriesByStorageIDRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) GetCategoriesByStorageID(ctx context.Context, arg GetCategoriesByStorageIDParams) ([]GetCategoriesByStorageIDRow, error) {
	rows, err := q.db.Query(ctx, getCategoriesByStorageID, arg.StorageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesByStorageIDRow
	for rows.Next() {
		var i GetCategoriesByStorageIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.ColorCode,
			&i.NameI18n,
			&i.DepartmentID,
			&i.StorageID,
			&i.Parent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT c.id, c.name, c.picture_url, c.color_code, c.name_i18n, c.department_id,
       d.storage_id, c.parent, c.created_at, c.updated_at, c.deleted_at
FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE c.id = $1 AND c.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = d.storage_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

type GetCategoryByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.ColorCode,
		&i.NameI18n,
		&i.DepartmentID,
		&i.StorageID,
		&i.Parent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByIDWithLanguage = `-- name: GetCategoryByIDWithLanguage :one
SELECT
    c.id,
    COALESCE(CASE
        WHEN $2::text = 'uz' THEN t.uz
        WHEN $2::text = 'ru' THEN t.ru
        WHEN $2::text = 'en' THEN t.en
        ELSE c.name
    END, c.name) as name,
    c.picture_url, c.name_i18n, c.department_id,
    d.storage_id, c.parent, c.color_code, c.created_at, c.updated_at, c.deleted_at
FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
LEFT JOIN translations t ON c.name_i18n = t.id AND t.deleted_at = 0
WHERE c.id = $1 AND c.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = d.storage_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

type GetCategoryByIDWithLanguageParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

type GetCategoryByIDWithLanguageRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	ColorCode    *string            `json:"color_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) GetCategoryByIDWithLanguage(ctx context.Context, arg GetCategoryByIDWithLanguageParams) (GetCategoryByIDWithLanguageRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByIDWithLanguage, arg.ID, arg.Column2)
	var i GetCategoryByIDWithLanguageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.NameI18n,
		&i.DepartmentID,
		&i.StorageID,
		&i.Parent,
		&i.ColorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryWithRelations = `-- name: GetCategoryWithRelations :one
SELECT
    c.id, c.name, c.picture_url, c.name_i18n, c.department_id,
    d.storage_id, c.parent, c.color_code, c.created_at, c.updated_at,
    d.name as department_name,
    s.name as storage_name,
    pc.name as parent_name
FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
LEFT JOIN storages s ON d.storage_id = s.id AND s.deleted_at = 0
LEFT JOIN categories pc ON c.parent = pc.id AND pc.deleted_at = 0
WHERE c.id = $1 AND c.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM storages s2
    WHERE s2.id = d.storage_id
      AND s2.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

type GetCategoryWithRelationsRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	PictureUrl     *string            `json:"picture_url"`
	NameI18n       pgtype.UUID        `json:"name_i18n"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	StorageID      pgtype.UUID        `json:"storage_id"`
	Parent         pgtype.UUID        `json:"parent"`
	ColorCode      *string            `json:"color_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DepartmentName *string            `json:"department_name"`
	StorageName    *string            `json:"storage_name"`
	ParentName     *string            `json:"parent_name"`
}

func (q *Queries) GetCategoryWithRelations(ctx context.Context, id uuid.UUID) (GetCategoryWithRelationsRow, error) {
	row := q.db.QueryRow(ctx, getCategoryWithRelations, id)
	var i GetCategoryWithRelationsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.NameI18n,
		&i.DepartmentID,
		&i.StorageID,
		&i.Parent,
		&i.ColorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentName,
		&i.StorageName,
		&i.ParentName,
	)
	return i, err
}

const getRootCategories = `-- name: GetRootCategories :many
SELECT c.id, c.name, c.picture_url, c.color_code, c.name_i18n, c.department_id,
       d.storage_id, c.parent, c.created_at, c.updated_at, c.deleted_at
FROM categories c
LEFT JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE c.parent IS NULL AND c.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM storages s
    WHERE s.id = d.storage_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type GetRootCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetRootCategoriesRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) GetRootCategories(ctx context.Context, arg GetRootCategoriesParams) ([]GetRootCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getRootCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRootCategoriesRow
	for rows.Next() {
		var i GetRootCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.ColorCode,
			&i.NameI18n,
			&i.DepartmentID,
			&i.StorageID,
			&i.Parent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCategory = `-- name: RestoreCategory :exec
UPDATE categories
SET deleted_at = 0
WHERE categories.id = $1 AND deleted_at != 0
  AND EXISTS (
    SELECT 1 FROM departments d
    JOIN storages s ON s.id = d.storage_id
    WHERE d.id = categories.department_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) RestoreCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreCategory, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name          = COALESCE($2, name),
    picture_url   = COALESCE($3, picture_url),
    name_i18n     = COALESCE($4, name_i18n),
    department_id = COALESCE($5, department_id),
    parent        = COALESCE($6, parent),
    color_code    = COALESCE($7, color_code),
    updated_at    = NOW()
WHERE categories.id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM departments d
    JOIN storages s ON s.id = d.storage_id
    WHERE d.id = categories.department_id
      AND s.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
  AND ($5 IS NULL OR EXISTS (
    SELECT 1 FROM departments d2
    JOIN storages s2 ON s2.id = d2.storage_id
    WHERE d2.id = $5
      AND s2.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  ))
RETURNING id, name, picture_url, color_code, name_i18n, department_id,
  (SELECT dep.storage_id FROM departments dep WHERE dep.id = department_id AND dep.deleted_at = 0) as storage_id,
  parent, created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	PictureUrl   *string     `json:"picture_url"`
	NameI18n     pgtype.UUID `json:"name_i18n"`
	DepartmentID pgtype.UUID `json:"department_id"`
	Parent       pgtype.UUID `json:"parent"`
	ColorCode    *string     `json:"color_code"`
}

type UpdateCategoryRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.PictureUrl,
		arg.NameI18n,
		arg.DepartmentID,
		arg.Parent,
		arg.ColorCode,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.ColorCode,
		&i.NameI18n,
		&i.DepartmentID,
		&i.StorageID,
		&i.Parent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
