// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goods_modifiers.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachModifierToGood = `-- name: AttachModifierToGood :one
INSERT INTO goods_modifiers (
    id,
    good_id,
    modifier_id,
    is_required,
    sort_order
)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    good_id,
    modifier_id,
    is_required,
    sort_order,
    created_at,
    updated_at,
    deleted_at
`

type AttachModifierToGoodParams struct {
	ID         uuid.UUID `json:"id"`
	GoodID     uuid.UUID `json:"good_id"`
	ModifierID uuid.UUID `json:"modifier_id"`
	IsRequired bool      `json:"is_required"`
	SortOrder  int32     `json:"sort_order"`
}

func (q *Queries) AttachModifierToGood(ctx context.Context, arg AttachModifierToGoodParams) (GoodsModifier, error) {
	row := q.db.QueryRow(ctx, attachModifierToGood,
		arg.ID,
		arg.GoodID,
		arg.ModifierID,
		arg.IsRequired,
		arg.SortOrder,
	)
	var i GoodsModifier
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.ModifierID,
		&i.IsRequired,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countModifiersByGoodID = `-- name: CountModifiersByGoodID :one
SELECT COUNT(*)
FROM goods_modifiers gm
JOIN modifiers m ON m.id = gm.modifier_id
WHERE gm.good_id = $1
  AND gm.deleted_at = 0
  AND m.deleted_at = 0
`

func (q *Queries) CountModifiersByGoodID(ctx context.Context, goodID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countModifiersByGoodID, goodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGoodModifierByID = `-- name: DeleteGoodModifierByID :exec
UPDATE goods_modifiers
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
  AND deleted_at = 0
`

func (q *Queries) DeleteGoodModifierByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGoodModifierByID, id)
	return err
}

const detachModifierFromGood = `-- name: DetachModifierFromGood :exec
UPDATE goods_modifiers
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE good_id = $1
  AND modifier_id = $2
  AND deleted_at = 0
`

type DetachModifierFromGoodParams struct {
	GoodID     uuid.UUID `json:"good_id"`
	ModifierID uuid.UUID `json:"modifier_id"`
}

func (q *Queries) DetachModifierFromGood(ctx context.Context, arg DetachModifierFromGoodParams) error {
	_, err := q.db.Exec(ctx, detachModifierFromGood, arg.GoodID, arg.ModifierID)
	return err
}

const getActiveGoodModifierByGoodAndModifierID = `-- name: GetActiveGoodModifierByGoodAndModifierID :one
SELECT
    id,
    good_id,
    modifier_id,
    is_required,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM goods_modifiers
WHERE good_id = $1
  AND modifier_id = $2
  AND deleted_at = 0
LIMIT 1
`

type GetActiveGoodModifierByGoodAndModifierIDParams struct {
	GoodID     uuid.UUID `json:"good_id"`
	ModifierID uuid.UUID `json:"modifier_id"`
}

func (q *Queries) GetActiveGoodModifierByGoodAndModifierID(ctx context.Context, arg GetActiveGoodModifierByGoodAndModifierIDParams) (GoodsModifier, error) {
	row := q.db.QueryRow(ctx, getActiveGoodModifierByGoodAndModifierID, arg.GoodID, arg.ModifierID)
	var i GoodsModifier
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.ModifierID,
		&i.IsRequired,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoodModifierByGoodAndModifierID = `-- name: GetGoodModifierByGoodAndModifierID :one
SELECT
    id,
    good_id,
    modifier_id,
    is_required,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM goods_modifiers
WHERE good_id = $1
  AND modifier_id = $2
LIMIT 1
`

type GetGoodModifierByGoodAndModifierIDParams struct {
	GoodID     uuid.UUID `json:"good_id"`
	ModifierID uuid.UUID `json:"modifier_id"`
}

func (q *Queries) GetGoodModifierByGoodAndModifierID(ctx context.Context, arg GetGoodModifierByGoodAndModifierIDParams) (GoodsModifier, error) {
	row := q.db.QueryRow(ctx, getGoodModifierByGoodAndModifierID, arg.GoodID, arg.ModifierID)
	var i GoodsModifier
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.ModifierID,
		&i.IsRequired,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoodsByModifierID = `-- name: GetGoodsByModifierID :many
SELECT
    gm.id,
    gm.good_id,
    gm.modifier_id,
    gm.is_required,
    gm.sort_order,
    gm.created_at,
    gm.updated_at,
    gm.deleted_at
FROM goods_modifiers gm
WHERE gm.modifier_id = $1
  AND gm.deleted_at = 0
ORDER BY gm.sort_order ASC, gm.created_at ASC
`

func (q *Queries) GetGoodsByModifierID(ctx context.Context, modifierID uuid.UUID) ([]GoodsModifier, error) {
	rows, err := q.db.Query(ctx, getGoodsByModifierID, modifierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsModifier
	for rows.Next() {
		var i GoodsModifier
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.ModifierID,
			&i.IsRequired,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModifiersByGoodID = `-- name: GetModifiersByGoodID :many
SELECT
    gm.id,
    gm.good_id,
    gm.modifier_id,
    gm.is_required,
    gm.sort_order,
    gm.created_at,
    gm.updated_at,
    gm.deleted_at,
    m.name,
    m.name_i18n,
    m.description,
    m.code,
    m.is_active,
    m.picture_url
FROM goods_modifiers gm
JOIN modifiers m ON m.id = gm.modifier_id
WHERE gm.good_id = $1
  AND gm.deleted_at = 0
  AND m.deleted_at = 0
ORDER BY gm.sort_order ASC, gm.created_at ASC
`

type GetModifiersByGoodIDRow struct {
	ID          uuid.UUID          `json:"id"`
	GoodID      uuid.UUID          `json:"good_id"`
	ModifierID  uuid.UUID          `json:"modifier_id"`
	IsRequired  bool               `json:"is_required"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
	Name        string             `json:"name"`
	NameI18n    pgtype.UUID        `json:"name_i18n"`
	Description *string            `json:"description"`
	Code        *string            `json:"code"`
	IsActive    bool               `json:"is_active"`
	PictureUrl  *string            `json:"picture_url"`
}

func (q *Queries) GetModifiersByGoodID(ctx context.Context, goodID uuid.UUID) ([]GetModifiersByGoodIDRow, error) {
	rows, err := q.db.Query(ctx, getModifiersByGoodID, goodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModifiersByGoodIDRow
	for rows.Next() {
		var i GetModifiersByGoodIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.ModifierID,
			&i.IsRequired,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.NameI18n,
			&i.Description,
			&i.Code,
			&i.IsActive,
			&i.PictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModifiersByGoodIDPaginated = `-- name: GetModifiersByGoodIDPaginated :many
SELECT
    gm.id,
    gm.good_id,
    gm.modifier_id,
    gm.is_required,
    gm.sort_order,
    gm.created_at,
    gm.updated_at,
    gm.deleted_at,
    m.name,
    m.name_i18n,
    m.description,
    m.code,
    m.is_active,
    m.picture_url
FROM goods_modifiers gm
JOIN modifiers m ON m.id = gm.modifier_id
WHERE gm.good_id = $1
  AND gm.deleted_at = 0
  AND m.deleted_at = 0
ORDER BY gm.sort_order ASC, gm.created_at ASC
LIMIT $2 OFFSET $3
`

type GetModifiersByGoodIDPaginatedParams struct {
	GoodID uuid.UUID `json:"good_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetModifiersByGoodIDPaginatedRow struct {
	ID          uuid.UUID          `json:"id"`
	GoodID      uuid.UUID          `json:"good_id"`
	ModifierID  uuid.UUID          `json:"modifier_id"`
	IsRequired  bool               `json:"is_required"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
	Name        string             `json:"name"`
	NameI18n    pgtype.UUID        `json:"name_i18n"`
	Description *string            `json:"description"`
	Code        *string            `json:"code"`
	IsActive    bool               `json:"is_active"`
	PictureUrl  *string            `json:"picture_url"`
}

func (q *Queries) GetModifiersByGoodIDPaginated(ctx context.Context, arg GetModifiersByGoodIDPaginatedParams) ([]GetModifiersByGoodIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getModifiersByGoodIDPaginated, arg.GoodID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModifiersByGoodIDPaginatedRow
	for rows.Next() {
		var i GetModifiersByGoodIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.ModifierID,
			&i.IsRequired,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.NameI18n,
			&i.Description,
			&i.Code,
			&i.IsActive,
			&i.PictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreModifierToGood = `-- name: RestoreModifierToGood :exec
UPDATE goods_modifiers
SET
    deleted_at = 0,
    is_required = $3,
    sort_order = $4
WHERE good_id = $1
  AND modifier_id = $2
  AND deleted_at <> 0
`

type RestoreModifierToGoodParams struct {
	GoodID     uuid.UUID `json:"good_id"`
	ModifierID uuid.UUID `json:"modifier_id"`
	IsRequired bool      `json:"is_required"`
	SortOrder  int32     `json:"sort_order"`
}

func (q *Queries) RestoreModifierToGood(ctx context.Context, arg RestoreModifierToGoodParams) error {
	_, err := q.db.Exec(ctx, restoreModifierToGood,
		arg.GoodID,
		arg.ModifierID,
		arg.IsRequired,
		arg.SortOrder,
	)
	return err
}

const updateGoodModifierSettings = `-- name: UpdateGoodModifierSettings :one
UPDATE goods_modifiers
SET
    is_required = $3,
    sort_order = $4
WHERE good_id = $1
  AND modifier_id = $2
  AND deleted_at = 0
RETURNING
    id,
    good_id,
    modifier_id,
    is_required,
    sort_order,
    created_at,
    updated_at,
    deleted_at
`

type UpdateGoodModifierSettingsParams struct {
	GoodID     uuid.UUID `json:"good_id"`
	ModifierID uuid.UUID `json:"modifier_id"`
	IsRequired bool      `json:"is_required"`
	SortOrder  int32     `json:"sort_order"`
}

func (q *Queries) UpdateGoodModifierSettings(ctx context.Context, arg UpdateGoodModifierSettingsParams) (GoodsModifier, error) {
	row := q.db.QueryRow(ctx, updateGoodModifierSettings,
		arg.GoodID,
		arg.ModifierID,
		arg.IsRequired,
		arg.SortOrder,
	)
	var i GoodsModifier
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.ModifierID,
		&i.IsRequired,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
