// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goods.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGoodDetails = `-- name: CountGoodDetails :one
SELECT COUNT(*) FROM goods_details
WHERE deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = goods_details.good_id
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) CountGoodDetails(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGoodDetails)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGoodDetailsByGood = `-- name: CountGoodDetailsByGood :one
SELECT COUNT(*) FROM goods_details
WHERE goods_details.good_id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = $1
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) CountGoodDetailsByGood(ctx context.Context, goodID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGoodDetailsByGood, goodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGoods = `-- name: CountGoods :one
SELECT COUNT(*) FROM goods
WHERE deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

func (q *Queries) CountGoods(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGoods)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGoodsByCategory = `-- name: CountGoodsByCategory :one
SELECT COUNT(*) FROM goods
WHERE category_id = $1 AND deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

func (q *Queries) CountGoodsByCategory(ctx context.Context, categoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGoodsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGoodsFiltered = `-- name: CountGoodsFiltered :one
SELECT COUNT(*)
FROM goods
WHERE goods.deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND (($1::uuid = '00000000-0000-0000-0000-000000000000') OR goods.category_id = $1)
  AND ($2 = '' OR goods.name ILIKE '%' || $2 || '%')
`

type CountGoodsFilteredParams struct {
	Column1 uuid.UUID   `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountGoodsFiltered(ctx context.Context, arg CountGoodsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGoodsFiltered, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGood = `-- name: CreateGood :one
INSERT INTO goods (id, name, description, name_i18n, description_i18n, category_id, branch_id, picture_url, color_code, price, cook_time)
VALUES ($1, $2, $3, $4, $5, $6, NULLIF(current_setting('app.branch_id', true), '')::uuid, $7, $8, $9, $10)
RETURNING goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.branch_id, goods.picture_url, goods.color_code, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
`

type CreateGoodParams struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     *string        `json:"description"`
	NameI18n        pgtype.UUID    `json:"name_i18n"`
	DescriptionI18n pgtype.UUID    `json:"description_i18n"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	PictureUrl      *string        `json:"picture_url"`
	ColorCode       *string        `json:"color_code"`
	Price           pgtype.Numeric `json:"price"`
	CookTime        *int32         `json:"cook_time"`
}

type CreateGoodRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) CreateGood(ctx context.Context, arg CreateGoodParams) (CreateGoodRow, error) {
	row := q.db.QueryRow(ctx, createGood,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.NameI18n,
		arg.DescriptionI18n,
		arg.CategoryID,
		arg.PictureUrl,
		arg.ColorCode,
		arg.Price,
		arg.CookTime,
	)
	var i CreateGoodRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.CategoryID,
		&i.BranchID,
		&i.PictureUrl,
		&i.ColorCode,
		&i.Price,
		&i.CookTime,
		&i.CostPrice,
		&i.Profit,
		&i.ProfitMargin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createGoodDetail = `-- name: CreateGoodDetail :one
INSERT INTO goods_details (id, good_id, ingredient_id, compound_id, measurement, quantity)
SELECT $1, $2, $3, $4, $5, $6
WHERE (
    EXISTS (
      SELECT 1 FROM goods g
      WHERE g.id = $2
        AND g.deleted_at = 0
        AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
    )
    AND (
      $3 IS NULL OR EXISTS (
        SELECT 1 FROM ingredients i
        WHERE i.id = $3
          AND i.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
      )
    )
    AND (
      $4 IS NULL OR EXISTS (
        SELECT 1 FROM compounds c
        WHERE c.id = $4
          AND c.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
      )
    )
)
RETURNING goods_details.id, goods_details.good_id, goods_details.ingredient_id, goods_details.compound_id, goods_details.measurement, goods_details.quantity, goods_details.created_at, goods_details.updated_at, goods_details.deleted_at
`

type CreateGoodDetailParams struct {
	ID           uuid.UUID           `json:"id"`
	GoodID       uuid.UUID           `json:"good_id"`
	IngredientID pgtype.UUID         `json:"ingredient_id"`
	CompoundID   pgtype.UUID         `json:"compound_id"`
	Measurement  NullMeasurementType `json:"measurement"`
	Quantity     int64               `json:"quantity"`
}

func (q *Queries) CreateGoodDetail(ctx context.Context, arg CreateGoodDetailParams) (GoodsDetail, error) {
	row := q.db.QueryRow(ctx, createGoodDetail,
		arg.ID,
		arg.GoodID,
		arg.IngredientID,
		arg.CompoundID,
		arg.Measurement,
		arg.Quantity,
	)
	var i GoodsDetail
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.IngredientID,
		&i.CompoundID,
		&i.Measurement,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteGood = `-- name: DeleteGood :exec
UPDATE goods
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE goods.id = $1 AND deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

func (q *Queries) DeleteGood(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGood, id)
	return err
}

const deleteGoodDetail = `-- name: DeleteGoodDetail :exec
UPDATE goods_details
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE goods_details.id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = goods_details.good_id
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) DeleteGoodDetail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGoodDetail, id)
	return err
}

const deleteGoodDetailsByGoodID = `-- name: DeleteGoodDetailsByGoodID :exec
UPDATE goods_details
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE goods_details.good_id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = $1
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) DeleteGoodDetailsByGoodID(ctx context.Context, goodID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGoodDetailsByGoodID, goodID)
	return err
}

const getAllGoodDetails = `-- name: GetAllGoodDetails :many
SELECT goods_details.id, goods_details.good_id, goods_details.ingredient_id, goods_details.compound_id, goods_details.measurement, goods_details.quantity, goods_details.created_at, goods_details.updated_at, goods_details.deleted_at
FROM goods_details
WHERE deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = goods_details.good_id
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllGoodDetailsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllGoodDetails(ctx context.Context, arg GetAllGoodDetailsParams) ([]GoodsDetail, error) {
	rows, err := q.db.Query(ctx, getAllGoodDetails, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsDetail
	for rows.Next() {
		var i GoodsDetail
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.IngredientID,
			&i.CompoundID,
			&i.Measurement,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGoods = `-- name: GetAllGoods :many
SELECT goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.branch_id, goods.picture_url, goods.color_code, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
FROM goods
WHERE deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllGoodsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllGoodsRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) GetAllGoods(ctx context.Context, arg GetAllGoodsParams) ([]GetAllGoodsRow, error) {
	rows, err := q.db.Query(ctx, getAllGoods, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGoodsRow
	for rows.Next() {
		var i GetAllGoodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.CategoryID,
			&i.BranchID,
			&i.PictureUrl,
			&i.ColorCode,
			&i.Price,
			&i.CookTime,
			&i.CostPrice,
			&i.Profit,
			&i.ProfitMargin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGoodsWithLanguage = `-- name: GetAllGoodsWithLanguage :many
SELECT
    g.id,
    COALESCE(CASE
        WHEN $1::text = 'uz' THEN tn.uz
        WHEN $1::text = 'ru' THEN tn.ru
        WHEN $1::text = 'en' THEN tn.en
        ELSE g.name
    END, g.name) as name,
    COALESCE(CASE
        WHEN $1::text = 'uz' THEN td.uz
        WHEN $1::text = 'ru' THEN td.ru
        WHEN $1::text = 'en' THEN td.en
        ELSE g.description
    END, g.description) as description,
    g.name_i18n,
    g.description_i18n,
    g.category_id,
    g.branch_id,
    g.picture_url,
    g.color_code,
    g.price,
    g.cook_time,
    g.cost_price,
    g.profit,
    g.profit_margin,
    g.created_at,
    g.updated_at,
    g.deleted_at
FROM goods g
LEFT JOIN translations tn ON g.name_i18n = tn.id AND tn.deleted_at = 0
LEFT JOIN translations td ON g.description_i18n = td.id AND td.deleted_at = 0
WHERE g.deleted_at = 0
  AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
ORDER BY g.created_at DESC
LIMIT $2 OFFSET $3
`

type GetAllGoodsWithLanguageParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetAllGoodsWithLanguageRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) GetAllGoodsWithLanguage(ctx context.Context, arg GetAllGoodsWithLanguageParams) ([]GetAllGoodsWithLanguageRow, error) {
	rows, err := q.db.Query(ctx, getAllGoodsWithLanguage, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGoodsWithLanguageRow
	for rows.Next() {
		var i GetAllGoodsWithLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.CategoryID,
			&i.BranchID,
			&i.PictureUrl,
			&i.ColorCode,
			&i.Price,
			&i.CookTime,
			&i.CostPrice,
			&i.Profit,
			&i.ProfitMargin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoodByID = `-- name: GetGoodByID :one
SELECT goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.branch_id, goods.picture_url, goods.color_code, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
FROM goods
WHERE goods.id = $1 AND deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

type GetGoodByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) GetGoodByID(ctx context.Context, id uuid.UUID) (GetGoodByIDRow, error) {
	row := q.db.QueryRow(ctx, getGoodByID, id)
	var i GetGoodByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.CategoryID,
		&i.BranchID,
		&i.PictureUrl,
		&i.ColorCode,
		&i.Price,
		&i.CookTime,
		&i.CostPrice,
		&i.Profit,
		&i.ProfitMargin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoodByIDWithLanguage = `-- name: GetGoodByIDWithLanguage :one
SELECT
    g.id,
    COALESCE(CASE
        WHEN $2::text = 'uz' THEN tn.uz
        WHEN $2::text = 'ru' THEN tn.ru
        WHEN $2::text = 'en' THEN tn.en
        ELSE g.name
    END, g.name) as name,
    COALESCE(CASE
        WHEN $2::text = 'uz' THEN td.uz
        WHEN $2::text = 'ru' THEN td.ru
        WHEN $2::text = 'en' THEN td.en
        ELSE g.description
    END, g.description) as description,
    g.name_i18n,
    g.description_i18n,
    g.category_id,
    g.branch_id,
    g.picture_url,
    g.color_code,
    g.price,
    g.cook_time,
    g.cost_price,
    g.profit,
    g.profit_margin,
    g.created_at,
    g.updated_at,
    g.deleted_at
FROM goods g
LEFT JOIN translations tn ON g.name_i18n = tn.id AND tn.deleted_at = 0
LEFT JOIN translations td ON g.description_i18n = td.id AND td.deleted_at = 0
WHERE g.id = $1 AND g.deleted_at = 0
  AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

type GetGoodByIDWithLanguageParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

type GetGoodByIDWithLanguageRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) GetGoodByIDWithLanguage(ctx context.Context, arg GetGoodByIDWithLanguageParams) (GetGoodByIDWithLanguageRow, error) {
	row := q.db.QueryRow(ctx, getGoodByIDWithLanguage, arg.ID, arg.Column2)
	var i GetGoodByIDWithLanguageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.CategoryID,
		&i.BranchID,
		&i.PictureUrl,
		&i.ColorCode,
		&i.Price,
		&i.CookTime,
		&i.CostPrice,
		&i.Profit,
		&i.ProfitMargin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoodDetailByID = `-- name: GetGoodDetailByID :one
SELECT goods_details.id, goods_details.good_id, goods_details.ingredient_id, goods_details.compound_id, goods_details.measurement, goods_details.quantity, goods_details.created_at, goods_details.updated_at, goods_details.deleted_at
FROM goods_details
WHERE goods_details.id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = goods_details.good_id
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) GetGoodDetailByID(ctx context.Context, id uuid.UUID) (GoodsDetail, error) {
	row := q.db.QueryRow(ctx, getGoodDetailByID, id)
	var i GoodsDetail
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.IngredientID,
		&i.CompoundID,
		&i.Measurement,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoodDetailsByCompoundID = `-- name: GetGoodDetailsByCompoundID :many
SELECT goods_details.id, goods_details.good_id, goods_details.ingredient_id, goods_details.compound_id, goods_details.measurement, goods_details.quantity, goods_details.created_at, goods_details.updated_at, goods_details.deleted_at
FROM goods_details
WHERE compound_id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM compounds c
    WHERE c.id = $1
      AND c.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = goods_details.good_id
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetGoodDetailsByCompoundIDParams struct {
	CompoundID pgtype.UUID `json:"compound_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) GetGoodDetailsByCompoundID(ctx context.Context, arg GetGoodDetailsByCompoundIDParams) ([]GoodsDetail, error) {
	rows, err := q.db.Query(ctx, getGoodDetailsByCompoundID, arg.CompoundID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsDetail
	for rows.Next() {
		var i GoodsDetail
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.IngredientID,
			&i.CompoundID,
			&i.Measurement,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoodDetailsByGoodID = `-- name: GetGoodDetailsByGoodID :many
SELECT goods_details.id, goods_details.good_id, goods_details.ingredient_id, goods_details.compound_id, goods_details.measurement, goods_details.quantity, goods_details.created_at, goods_details.updated_at, goods_details.deleted_at
FROM goods_details
WHERE goods_details.good_id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = $1
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY created_at ASC
`

func (q *Queries) GetGoodDetailsByGoodID(ctx context.Context, goodID uuid.UUID) ([]GoodsDetail, error) {
	rows, err := q.db.Query(ctx, getGoodDetailsByGoodID, goodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsDetail
	for rows.Next() {
		var i GoodsDetail
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.IngredientID,
			&i.CompoundID,
			&i.Measurement,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoodDetailsByIngredientID = `-- name: GetGoodDetailsByIngredientID :many
SELECT goods_details.id, goods_details.good_id, goods_details.ingredient_id, goods_details.compound_id, goods_details.measurement, goods_details.quantity, goods_details.created_at, goods_details.updated_at, goods_details.deleted_at
FROM goods_details
WHERE ingredient_id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM ingredients i
    WHERE i.id = $1
      AND i.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = goods_details.good_id
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetGoodDetailsByIngredientIDParams struct {
	IngredientID pgtype.UUID `json:"ingredient_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) GetGoodDetailsByIngredientID(ctx context.Context, arg GetGoodDetailsByIngredientIDParams) ([]GoodsDetail, error) {
	rows, err := q.db.Query(ctx, getGoodDetailsByIngredientID, arg.IngredientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsDetail
	for rows.Next() {
		var i GoodsDetail
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.IngredientID,
			&i.CompoundID,
			&i.Measurement,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoodWithRelations = `-- name: GetGoodWithRelations :one
SELECT
    g.id,
    g.name,
    g.description,
    g.name_i18n,
    g.description_i18n,
    g.picture_url,
    g.price,
    g.cook_time,
    g.cost_price,
    g.profit,
    g.profit_margin,
    g.created_at,
    g.updated_at,
    c.name as category_name
FROM goods g
LEFT JOIN categories c ON g.category_id = c.id AND c.deleted_at = 0
WHERE g.id = $1 AND g.deleted_at = 0
  AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

type GetGoodWithRelationsRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	PictureUrl      *string            `json:"picture_url"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoryName    *string            `json:"category_name"`
}

func (q *Queries) GetGoodWithRelations(ctx context.Context, id uuid.UUID) (GetGoodWithRelationsRow, error) {
	row := q.db.QueryRow(ctx, getGoodWithRelations, id)
	var i GetGoodWithRelationsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.PictureUrl,
		&i.Price,
		&i.CookTime,
		&i.CostPrice,
		&i.Profit,
		&i.ProfitMargin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const getGoodsByCategoryID = `-- name: GetGoodsByCategoryID :many
SELECT goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.branch_id, goods.picture_url, goods.color_code, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
FROM goods
WHERE category_id = $1 AND deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type GetGoodsByCategoryIDParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type GetGoodsByCategoryIDRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) GetGoodsByCategoryID(ctx context.Context, arg GetGoodsByCategoryIDParams) ([]GetGoodsByCategoryIDRow, error) {
	rows, err := q.db.Query(ctx, getGoodsByCategoryID, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGoodsByCategoryIDRow
	for rows.Next() {
		var i GetGoodsByCategoryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.CategoryID,
			&i.BranchID,
			&i.PictureUrl,
			&i.ColorCode,
			&i.Price,
			&i.CookTime,
			&i.CostPrice,
			&i.Profit,
			&i.ProfitMargin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoodsByPriceRange = `-- name: GetGoodsByPriceRange :many
SELECT goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.branch_id, goods.picture_url, goods.color_code, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
FROM goods
WHERE price >= $1 AND price <= $2 AND deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
ORDER BY price ASC
LIMIT $3 OFFSET $4
`

type GetGoodsByPriceRangeParams struct {
	Price   pgtype.Numeric `json:"price"`
	Price_2 pgtype.Numeric `json:"price_2"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

type GetGoodsByPriceRangeRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) GetGoodsByPriceRange(ctx context.Context, arg GetGoodsByPriceRangeParams) ([]GetGoodsByPriceRangeRow, error) {
	rows, err := q.db.Query(ctx, getGoodsByPriceRange,
		arg.Price,
		arg.Price_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGoodsByPriceRangeRow
	for rows.Next() {
		var i GetGoodsByPriceRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.CategoryID,
			&i.BranchID,
			&i.PictureUrl,
			&i.ColorCode,
			&i.Price,
			&i.CookTime,
			&i.CostPrice,
			&i.Profit,
			&i.ProfitMargin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoodsFiltered = `-- name: GetGoodsFiltered :many

SELECT goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.branch_id, goods.picture_url, goods.color_code, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
FROM goods
WHERE goods.deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND (($1::uuid = '00000000-0000-0000-0000-000000000000') OR goods.category_id = $1)
  AND ($2 = '' OR goods.name ILIKE '%' || $2 || '%')
ORDER BY goods.created_at DESC
LIMIT $3 OFFSET $4
`

type GetGoodsFilteredParams struct {
	Column1 uuid.UUID   `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type GetGoodsFilteredRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

// ==================== FILTERED GOODS ====================
func (q *Queries) GetGoodsFiltered(ctx context.Context, arg GetGoodsFilteredParams) ([]GetGoodsFilteredRow, error) {
	rows, err := q.db.Query(ctx, getGoodsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGoodsFilteredRow
	for rows.Next() {
		var i GetGoodsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.CategoryID,
			&i.BranchID,
			&i.PictureUrl,
			&i.ColorCode,
			&i.Price,
			&i.CookTime,
			&i.CostPrice,
			&i.Profit,
			&i.ProfitMargin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoodsFilteredWithLanguage = `-- name: GetGoodsFilteredWithLanguage :many
SELECT
    g.id,
    COALESCE(CASE
        WHEN $1::text = 'uz' THEN tn.uz
        WHEN $1::text = 'ru' THEN tn.ru
        WHEN $1::text = 'en' THEN tn.en
        ELSE g.name
    END, g.name) as name,
    COALESCE(CASE
        WHEN $1::text = 'uz' THEN td.uz
        WHEN $1::text = 'ru' THEN td.ru
        WHEN $1::text = 'en' THEN td.en
        ELSE g.description
    END, g.description) as description,
    g.name_i18n,
    g.description_i18n,
    g.category_id,
    g.branch_id,
    g.picture_url,
    g.color_code,
    g.price,
    g.cook_time,
    g.cost_price,
    g.profit,
    g.profit_margin,
    g.created_at,
    g.updated_at,
    g.deleted_at
FROM goods g
LEFT JOIN translations tn ON g.name_i18n = tn.id AND tn.deleted_at = 0
LEFT JOIN translations td ON g.description_i18n = td.id AND td.deleted_at = 0
WHERE g.deleted_at = 0
  AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND (($2::uuid = '00000000-0000-0000-0000-000000000000') OR g.category_id = $2)
  AND ($3 = '' OR g.name ILIKE '%' || $3 || '%')
ORDER BY g.created_at DESC
LIMIT $4 OFFSET $5
`

type GetGoodsFilteredWithLanguageParams struct {
	Column1 string      `json:"column_1"`
	Column2 uuid.UUID   `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type GetGoodsFilteredWithLanguageRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) GetGoodsFilteredWithLanguage(ctx context.Context, arg GetGoodsFilteredWithLanguageParams) ([]GetGoodsFilteredWithLanguageRow, error) {
	rows, err := q.db.Query(ctx, getGoodsFilteredWithLanguage,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGoodsFilteredWithLanguageRow
	for rows.Next() {
		var i GetGoodsFilteredWithLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.CategoryID,
			&i.BranchID,
			&i.PictureUrl,
			&i.ColorCode,
			&i.Price,
			&i.CookTime,
			&i.CostPrice,
			&i.Profit,
			&i.ProfitMargin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularGoods = `-- name: GetPopularGoods :many
SELECT
    g.id,
    g.name,
    g.picture_url,
    g.price,
    g.cook_time,
    COUNT(oi.id) as order_count,
    SUM(oi.quantity) as total_ordered
FROM goods g
LEFT JOIN order_items oi ON g.id = oi.good_id AND oi.deleted_at = 0
WHERE g.deleted_at = 0
  AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
GROUP BY g.id, g.name, g.picture_url, g.price, g.cook_time
ORDER BY order_count DESC
LIMIT $1 OFFSET $2
`

type GetPopularGoodsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetPopularGoodsRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	PictureUrl   *string        `json:"picture_url"`
	Price        pgtype.Numeric `json:"price"`
	CookTime     *int32         `json:"cook_time"`
	OrderCount   int64          `json:"order_count"`
	TotalOrdered int64          `json:"total_ordered"`
}

func (q *Queries) GetPopularGoods(ctx context.Context, arg GetPopularGoodsParams) ([]GetPopularGoodsRow, error) {
	rows, err := q.db.Query(ctx, getPopularGoods, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularGoodsRow
	for rows.Next() {
		var i GetPopularGoodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.Price,
			&i.CookTime,
			&i.OrderCount,
			&i.TotalOrdered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorageIDByGoodID = `-- name: GetStorageIDByGoodID :one
SELECT d.storage_id
FROM goods g
JOIN categories c ON g.category_id = c.id AND c.deleted_at = 0
JOIN departments d ON c.department_id = d.id AND d.deleted_at = 0
WHERE g.id = $1 AND g.deleted_at = 0
  AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

func (q *Queries) GetStorageIDByGoodID(ctx context.Context, id uuid.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getStorageIDByGoodID, id)
	var storage_id pgtype.UUID
	err := row.Scan(&storage_id)
	return storage_id, err
}

const restoreGood = `-- name: RestoreGood :exec
UPDATE goods
SET deleted_at = 0
WHERE goods.id = $1 AND deleted_at != 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

func (q *Queries) RestoreGood(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreGood, id)
	return err
}

const restoreGoodDetail = `-- name: RestoreGoodDetail :exec
UPDATE goods_details
SET deleted_at = 0
WHERE goods_details.id = $1 AND deleted_at != 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = goods_details.good_id
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) RestoreGoodDetail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreGoodDetail, id)
	return err
}

const searchGoods = `-- name: SearchGoods :many
SELECT goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.picture_url, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
FROM goods
WHERE deleted_at = 0
AND (name ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type SearchGoodsParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type SearchGoodsRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	PictureUrl      *string            `json:"picture_url"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) SearchGoods(ctx context.Context, arg SearchGoodsParams) ([]SearchGoodsRow, error) {
	rows, err := q.db.Query(ctx, searchGoods, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchGoodsRow
	for rows.Next() {
		var i SearchGoodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.CategoryID,
			&i.PictureUrl,
			&i.Price,
			&i.CookTime,
			&i.CostPrice,
			&i.Profit,
			&i.ProfitMargin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGood = `-- name: UpdateGood :one
UPDATE goods
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    name_i18n = COALESCE($4, name_i18n),
    description_i18n = COALESCE($5, description_i18n),
    category_id = COALESCE($6, category_id),
    picture_url = COALESCE($7, picture_url),
    color_code = COALESCE($8, color_code),
    price = COALESCE($9, price),
    cook_time = COALESCE($10, cook_time),
    updated_at = NOW()
WHERE goods.id = $1 AND deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
RETURNING goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.branch_id, goods.picture_url, goods.color_code, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
`

type UpdateGoodParams struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     *string        `json:"description"`
	NameI18n        pgtype.UUID    `json:"name_i18n"`
	DescriptionI18n pgtype.UUID    `json:"description_i18n"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	PictureUrl      *string        `json:"picture_url"`
	ColorCode       *string        `json:"color_code"`
	Price           pgtype.Numeric `json:"price"`
	CookTime        *int32         `json:"cook_time"`
}

type UpdateGoodRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) UpdateGood(ctx context.Context, arg UpdateGoodParams) (UpdateGoodRow, error) {
	row := q.db.QueryRow(ctx, updateGood,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.NameI18n,
		arg.DescriptionI18n,
		arg.CategoryID,
		arg.PictureUrl,
		arg.ColorCode,
		arg.Price,
		arg.CookTime,
	)
	var i UpdateGoodRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.CategoryID,
		&i.BranchID,
		&i.PictureUrl,
		&i.ColorCode,
		&i.Price,
		&i.CookTime,
		&i.CostPrice,
		&i.Profit,
		&i.ProfitMargin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGoodCostFields = `-- name: UpdateGoodCostFields :one
UPDATE goods
SET cost_price = $2,
    profit = $3,
    profit_margin = $4,
    updated_at = NOW()
WHERE goods.id = $1 AND deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
RETURNING goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.branch_id, goods.picture_url, goods.color_code, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
`

type UpdateGoodCostFieldsParams struct {
	ID           uuid.UUID      `json:"id"`
	CostPrice    pgtype.Numeric `json:"cost_price"`
	Profit       pgtype.Numeric `json:"profit"`
	ProfitMargin pgtype.Numeric `json:"profit_margin"`
}

type UpdateGoodCostFieldsRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) UpdateGoodCostFields(ctx context.Context, arg UpdateGoodCostFieldsParams) (UpdateGoodCostFieldsRow, error) {
	row := q.db.QueryRow(ctx, updateGoodCostFields,
		arg.ID,
		arg.CostPrice,
		arg.Profit,
		arg.ProfitMargin,
	)
	var i UpdateGoodCostFieldsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.CategoryID,
		&i.BranchID,
		&i.PictureUrl,
		&i.ColorCode,
		&i.Price,
		&i.CookTime,
		&i.CostPrice,
		&i.Profit,
		&i.ProfitMargin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGoodDetail = `-- name: UpdateGoodDetail :one
UPDATE goods_details
SET good_id = COALESCE($2, good_id),
    ingredient_id = COALESCE($3, ingredient_id),
    compound_id = COALESCE($4, compound_id),
    measurement = COALESCE($5, measurement),
    quantity = COALESCE($6, quantity),
    updated_at = NOW()
WHERE goods_details.id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = goods_details.good_id
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
  AND (
    $2 IS NULL OR EXISTS (
      SELECT 1 FROM goods g2
      WHERE g2.id = $2
        AND g2.deleted_at = 0
        AND g2.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
    )
  )
  AND (
    $3 IS NULL OR EXISTS (
      SELECT 1 FROM ingredients i
      WHERE i.id = $3
        AND i.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
    )
  )
  AND (
    $4 IS NULL OR EXISTS (
      SELECT 1 FROM compounds c
      WHERE c.id = $4
        AND c.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
    )
  )
RETURNING goods_details.id, goods_details.good_id, goods_details.ingredient_id, goods_details.compound_id, goods_details.measurement, goods_details.quantity, goods_details.created_at, goods_details.updated_at, goods_details.deleted_at
`

type UpdateGoodDetailParams struct {
	ID           uuid.UUID           `json:"id"`
	GoodID       uuid.UUID           `json:"good_id"`
	IngredientID pgtype.UUID         `json:"ingredient_id"`
	CompoundID   pgtype.UUID         `json:"compound_id"`
	Measurement  NullMeasurementType `json:"measurement"`
	Quantity     int64               `json:"quantity"`
}

func (q *Queries) UpdateGoodDetail(ctx context.Context, arg UpdateGoodDetailParams) (GoodsDetail, error) {
	row := q.db.QueryRow(ctx, updateGoodDetail,
		arg.ID,
		arg.GoodID,
		arg.IngredientID,
		arg.CompoundID,
		arg.Measurement,
		arg.Quantity,
	)
	var i GoodsDetail
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.IngredientID,
		&i.CompoundID,
		&i.Measurement,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGoodDetailQuantity = `-- name: UpdateGoodDetailQuantity :one
UPDATE goods_details
SET quantity = $2,
    updated_at = NOW()
WHERE goods_details.id = $1 AND deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM goods g
    WHERE g.id = goods_details.good_id
      AND g.deleted_at = 0
      AND g.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
RETURNING goods_details.id, goods_details.good_id, goods_details.ingredient_id, goods_details.compound_id, goods_details.measurement, goods_details.quantity, goods_details.created_at, goods_details.updated_at, goods_details.deleted_at
`

type UpdateGoodDetailQuantityParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int64     `json:"quantity"`
}

func (q *Queries) UpdateGoodDetailQuantity(ctx context.Context, arg UpdateGoodDetailQuantityParams) (GoodsDetail, error) {
	row := q.db.QueryRow(ctx, updateGoodDetailQuantity, arg.ID, arg.Quantity)
	var i GoodsDetail
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.IngredientID,
		&i.CompoundID,
		&i.Measurement,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGoodPrice = `-- name: UpdateGoodPrice :one
UPDATE goods
SET price = $2,
    updated_at = NOW()
WHERE goods.id = $1 AND deleted_at = 0
  AND goods.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
RETURNING goods.id, goods.name, goods.description, goods.name_i18n, goods.description_i18n, goods.category_id, goods.branch_id, goods.picture_url, goods.color_code, goods.price, goods.cook_time, goods.cost_price, goods.profit, goods.profit_margin, goods.created_at, goods.updated_at, goods.deleted_at
`

type UpdateGoodPriceParams struct {
	ID    uuid.UUID      `json:"id"`
	Price pgtype.Numeric `json:"price"`
}

type UpdateGoodPriceRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	PictureUrl      *string            `json:"picture_url"`
	ColorCode       *string            `json:"color_code"`
	Price           pgtype.Numeric     `json:"price"`
	CookTime        *int32             `json:"cook_time"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	Profit          pgtype.Numeric     `json:"profit"`
	ProfitMargin    pgtype.Numeric     `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
}

func (q *Queries) UpdateGoodPrice(ctx context.Context, arg UpdateGoodPriceParams) (UpdateGoodPriceRow, error) {
	row := q.db.QueryRow(ctx, updateGoodPrice, arg.ID, arg.Price)
	var i UpdateGoodPriceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.CategoryID,
		&i.BranchID,
		&i.PictureUrl,
		&i.ColorCode,
		&i.Price,
		&i.CookTime,
		&i.CostPrice,
		&i.Profit,
		&i.ProfitMargin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
