// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToIngredientStock = `-- name: AddToIngredientStock :one
UPDATE ingredient_stock
SET quantity = quantity + $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at = 0
RETURNING id, ingredient_id, quantity, branch_id, created_at, updated_at, deleted_at
`

type AddToIngredientStockParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int64     `json:"quantity"`
}

// AddToIngredientStock increases ingredient stock quantity
func (q *Queries) AddToIngredientStock(ctx context.Context, arg AddToIngredientStockParams) (IngredientStock, error) {
	row := q.db.QueryRow(ctx, addToIngredientStock, arg.ID, arg.Quantity)
	var i IngredientStock
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Quantity,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countIngredientGroups = `-- name: CountIngredientGroups :one
SELECT COUNT(*) FROM ingredient_groups WHERE deleted_at = 0
`

// CountIngredientGroups counts total ingredient groups
func (q *Queries) CountIngredientGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIngredientGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIngredientStock = `-- name: CountIngredientStock :one
SELECT COUNT(*) FROM ingredient_stock WHERE deleted_at = 0
`

// CountIngredientStock counts total ingredient stock entries
func (q *Queries) CountIngredientStock(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIngredientStock)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIngredients = `-- name: CountIngredients :one
SELECT COUNT(*) FROM ingredients WHERE deleted_at = 0
`

// CountIngredients counts total ingredients
func (q *Queries) CountIngredients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIngredients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (id, name, name_i18n, group_id, measurement, picture_url, color_code, brand_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, name_i18n, group_id, measurement, picture_url, color_code, brand_id, created_at, updated_at, deleted_at
`

type CreateIngredientParams struct {
	ID          uuid.UUID           `json:"id"`
	Name        string              `json:"name"`
	NameI18n    pgtype.UUID         `json:"name_i18n"`
	GroupID     pgtype.UUID         `json:"group_id"`
	Measurement NullMeasurementType `json:"measurement"`
	PictureUrl  *string             `json:"picture_url"`
	ColorCode   *string             `json:"color_code"`
	BrandID     pgtype.UUID         `json:"brand_id"`
}

// CreateIngredient creates a new ingredient
func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.ID,
		arg.Name,
		arg.NameI18n,
		arg.GroupID,
		arg.Measurement,
		arg.PictureUrl,
		arg.ColorCode,
		arg.BrandID,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.GroupID,
		&i.Measurement,
		&i.PictureUrl,
		&i.ColorCode,
		&i.BrandID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createIngredientGroup = `-- name: CreateIngredientGroup :one

INSERT INTO ingredient_groups (id, name, picture_url, name_i18n, color_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, picture_url, name_i18n, color_code, created_at, updated_at, deleted_at
`

type CreateIngredientGroupParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	PictureUrl *string     `json:"picture_url"`
	NameI18n   pgtype.UUID `json:"name_i18n"`
	ColorCode  *string     `json:"color_code"`
}

type CreateIngredientGroupRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	PictureUrl *string            `json:"picture_url"`
	NameI18n   pgtype.UUID        `json:"name_i18n"`
	ColorCode  *string            `json:"color_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  *int64             `json:"deleted_at"`
}

// ==================== INGREDIENT GROUPS QUERIES ====================
func (q *Queries) CreateIngredientGroup(ctx context.Context, arg CreateIngredientGroupParams) (CreateIngredientGroupRow, error) {
	row := q.db.QueryRow(ctx, createIngredientGroup,
		arg.ID,
		arg.Name,
		arg.PictureUrl,
		arg.NameI18n,
		arg.ColorCode,
	)
	var i CreateIngredientGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.NameI18n,
		&i.ColorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createIngredientStock = `-- name: CreateIngredientStock :one
INSERT INTO ingredient_stock (id, ingredient_id, quantity, branch_id)
VALUES ($1, $2, $3, $4)
RETURNING id, ingredient_id, quantity, branch_id, created_at, updated_at, deleted_at
`

type CreateIngredientStockParams struct {
	ID           uuid.UUID `json:"id"`
	IngredientID uuid.UUID `json:"ingredient_id"`
	Quantity     int64     `json:"quantity"`
	BranchID     uuid.UUID `json:"branch_id"`
}

// CreateIngredientStock creates a new ingredient stock entry
func (q *Queries) CreateIngredientStock(ctx context.Context, arg CreateIngredientStockParams) (IngredientStock, error) {
	row := q.db.QueryRow(ctx, createIngredientStock,
		arg.ID,
		arg.IngredientID,
		arg.Quantity,
		arg.BranchID,
	)
	var i IngredientStock
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Quantity,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
UPDATE ingredients
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND deleted_at = 0
`

// DeleteIngredient soft deletes an ingredient
func (q *Queries) DeleteIngredient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIngredient, id)
	return err
}

const deleteIngredientGroup = `-- name: DeleteIngredientGroup :exec
UPDATE ingredient_groups
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND deleted_at = 0
`

// DeleteIngredientGroup soft deletes an ingredient group
func (q *Queries) DeleteIngredientGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIngredientGroup, id)
	return err
}

const deleteIngredientStock = `-- name: DeleteIngredientStock :exec
UPDATE ingredient_stock
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND deleted_at = 0
`

// DeleteIngredientStock soft deletes ingredient stock
func (q *Queries) DeleteIngredientStock(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIngredientStock, id)
	return err
}

const getAllIngredientGroups = `-- name: GetAllIngredientGroups :many
SELECT id, name, picture_url, name_i18n, color_code, created_at, updated_at, deleted_at
FROM ingredient_groups
WHERE deleted_at = 0
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllIngredientGroupsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllIngredientGroupsRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	PictureUrl *string            `json:"picture_url"`
	NameI18n   pgtype.UUID        `json:"name_i18n"`
	ColorCode  *string            `json:"color_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  *int64             `json:"deleted_at"`
}

func (q *Queries) GetAllIngredientGroups(ctx context.Context, arg GetAllIngredientGroupsParams) ([]GetAllIngredientGroupsRow, error) {
	rows, err := q.db.Query(ctx, getAllIngredientGroups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllIngredientGroupsRow
	for rows.Next() {
		var i GetAllIngredientGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.NameI18n,
			&i.ColorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllIngredientStock = `-- name: GetAllIngredientStock :many
SELECT id, ingredient_id, quantity, branch_id, created_at, updated_at, deleted_at
FROM ingredient_stock
WHERE deleted_at = 0
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllIngredientStockParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// GetAllIngredientStock retrieves all ingredient stock entries with pagination
func (q *Queries) GetAllIngredientStock(ctx context.Context, arg GetAllIngredientStockParams) ([]IngredientStock, error) {
	rows, err := q.db.Query(ctx, getAllIngredientStock, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientStock
	for rows.Next() {
		var i IngredientStock
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.Quantity,
			&i.BranchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllIngredients = `-- name: GetAllIngredients :many
SELECT id, name, name_i18n, group_id, measurement, picture_url, color_code, brand_id, created_at, updated_at, deleted_at
FROM ingredients
WHERE deleted_at = 0
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllIngredientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// GetAllIngredients retrieves all ingredients with pagination
func (q *Queries) GetAllIngredients(ctx context.Context, arg GetAllIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getAllIngredients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameI18n,
			&i.GroupID,
			&i.Measurement,
			&i.PictureUrl,
			&i.ColorCode,
			&i.BrandID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIngredientByID = `-- name: GetIngredientByID :one
SELECT id, name, name_i18n, group_id, measurement, picture_url, color_code, brand_id, created_at, updated_at, deleted_at
FROM ingredients
WHERE id = $1 AND deleted_at = 0
`

// GetIngredientByID retrieves an ingredient by ID
func (q *Queries) GetIngredientByID(ctx context.Context, id uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByID, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.GroupID,
		&i.Measurement,
		&i.PictureUrl,
		&i.ColorCode,
		&i.BrandID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIngredientGroupByID = `-- name: GetIngredientGroupByID :one
SELECT id, name, picture_url, name_i18n, color_code, created_at, updated_at, deleted_at
FROM ingredient_groups
WHERE id = $1 AND deleted_at = 0
`

type GetIngredientGroupByIDRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	PictureUrl *string            `json:"picture_url"`
	NameI18n   pgtype.UUID        `json:"name_i18n"`
	ColorCode  *string            `json:"color_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  *int64             `json:"deleted_at"`
}

func (q *Queries) GetIngredientGroupByID(ctx context.Context, id uuid.UUID) (GetIngredientGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getIngredientGroupByID, id)
	var i GetIngredientGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.NameI18n,
		&i.ColorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIngredientStockByID = `-- name: GetIngredientStockByID :one
SELECT id, ingredient_id, quantity, branch_id, created_at, updated_at, deleted_at
FROM ingredient_stock
WHERE id = $1 AND deleted_at = 0
`

// GetIngredientStockByID retrieves ingredient stock by ID
func (q *Queries) GetIngredientStockByID(ctx context.Context, id uuid.UUID) (IngredientStock, error) {
	row := q.db.QueryRow(ctx, getIngredientStockByID, id)
	var i IngredientStock
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Quantity,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIngredientsByGroupID = `-- name: GetIngredientsByGroupID :many
SELECT id, name, name_i18n, group_id, measurement, picture_url, color_code, brand_id, created_at, updated_at, deleted_at
FROM ingredients
WHERE group_id = $1 AND deleted_at = 0
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetIngredientsByGroupIDParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// GetIngredientsByGroupID retrieves ingredients by group ID
func (q *Queries) GetIngredientsByGroupID(ctx context.Context, arg GetIngredientsByGroupIDParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getIngredientsByGroupID, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameI18n,
			&i.GroupID,
			&i.Measurement,
			&i.PictureUrl,
			&i.ColorCode,
			&i.BrandID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockByBranchID = `-- name: GetStockByBranchID :many
SELECT id, ingredient_id, quantity, branch_id, created_at, updated_at, deleted_at
FROM ingredient_stock
WHERE branch_id = $1 AND deleted_at = 0
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetStockByBranchIDParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

// GetStockByBranchID retrieves all stock for a branch
func (q *Queries) GetStockByBranchID(ctx context.Context, arg GetStockByBranchIDParams) ([]IngredientStock, error) {
	rows, err := q.db.Query(ctx, getStockByBranchID, arg.BranchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientStock
	for rows.Next() {
		var i IngredientStock
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.Quantity,
			&i.BranchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockByIngredientAndBranch = `-- name: GetStockByIngredientAndBranch :one
SELECT id, ingredient_id, quantity, branch_id, created_at, updated_at, deleted_at
FROM ingredient_stock
WHERE ingredient_id = $1 AND branch_id = $2 AND deleted_at = 0
`

type GetStockByIngredientAndBranchParams struct {
	IngredientID uuid.UUID `json:"ingredient_id"`
	BranchID     uuid.UUID `json:"branch_id"`
}

// GetStockByIngredientAndBranch retrieves stock for a specific ingredient and branch
func (q *Queries) GetStockByIngredientAndBranch(ctx context.Context, arg GetStockByIngredientAndBranchParams) (IngredientStock, error) {
	row := q.db.QueryRow(ctx, getStockByIngredientAndBranch, arg.IngredientID, arg.BranchID)
	var i IngredientStock
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Quantity,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStockByIngredientID = `-- name: GetStockByIngredientID :many
SELECT id, ingredient_id, quantity, branch_id, created_at, updated_at, deleted_at
FROM ingredient_stock
WHERE ingredient_id = $1 AND deleted_at = 0
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetStockByIngredientIDParams struct {
	IngredientID uuid.UUID `json:"ingredient_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

// GetStockByIngredientID retrieves all stock for an ingredient
func (q *Queries) GetStockByIngredientID(ctx context.Context, arg GetStockByIngredientIDParams) ([]IngredientStock, error) {
	rows, err := q.db.Query(ctx, getStockByIngredientID, arg.IngredientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientStock
	for rows.Next() {
		var i IngredientStock
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.Quantity,
			&i.BranchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromIngredientStock = `-- name: RemoveFromIngredientStock :one
UPDATE ingredient_stock
SET quantity = CASE 
    WHEN quantity - $2 < 0 THEN 0 
    ELSE quantity - $2 
END,
    updated_at = NOW()
WHERE id = $1 AND deleted_at = 0
RETURNING id, ingredient_id, quantity, branch_id, created_at, updated_at, deleted_at
`

type RemoveFromIngredientStockParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int64     `json:"quantity"`
}

// RemoveFromIngredientStock decreases ingredient stock quantity
func (q *Queries) RemoveFromIngredientStock(ctx context.Context, arg RemoveFromIngredientStockParams) (IngredientStock, error) {
	row := q.db.QueryRow(ctx, removeFromIngredientStock, arg.ID, arg.Quantity)
	var i IngredientStock
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Quantity,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreIngredient = `-- name: RestoreIngredient :exec
UPDATE ingredients
SET deleted_at = 0
WHERE id = $1 AND deleted_at != 0
`

// RestoreIngredient restores a deleted ingredient
func (q *Queries) RestoreIngredient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreIngredient, id)
	return err
}

const restoreIngredientGroup = `-- name: RestoreIngredientGroup :exec
UPDATE ingredient_groups
SET deleted_at = 0
WHERE id = $1 AND deleted_at != 0
`

// RestoreIngredientGroup restores a deleted ingredient group
func (q *Queries) RestoreIngredientGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreIngredientGroup, id)
	return err
}

const restoreIngredientStock = `-- name: RestoreIngredientStock :exec
UPDATE ingredient_stock
SET deleted_at = 0
WHERE id = $1 AND deleted_at != 0
`

// RestoreIngredientStock restores deleted ingredient stock
func (q *Queries) RestoreIngredientStock(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreIngredientStock, id)
	return err
}

const searchIngredientGroups = `-- name: SearchIngredientGroups :many
SELECT id, name, picture_url, name_i18n, color_code, created_at, updated_at, deleted_at
FROM ingredient_groups
WHERE deleted_at = 0 AND name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchIngredientGroupsParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type SearchIngredientGroupsRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	PictureUrl *string            `json:"picture_url"`
	NameI18n   pgtype.UUID        `json:"name_i18n"`
	ColorCode  *string            `json:"color_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  *int64             `json:"deleted_at"`
}

// SearchIngredientGroups searches ingredient groups by name
func (q *Queries) SearchIngredientGroups(ctx context.Context, arg SearchIngredientGroupsParams) ([]SearchIngredientGroupsRow, error) {
	rows, err := q.db.Query(ctx, searchIngredientGroups, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchIngredientGroupsRow
	for rows.Next() {
		var i SearchIngredientGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.NameI18n,
			&i.ColorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchIngredients = `-- name: SearchIngredients :many
SELECT id, name, name_i18n, group_id, measurement, picture_url, color_code, brand_id, created_at, updated_at, deleted_at
FROM ingredients
WHERE deleted_at = 0 AND name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchIngredientsParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

// SearchIngredients searches ingredients by name
func (q *Queries) SearchIngredients(ctx context.Context, arg SearchIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, searchIngredients, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameI18n,
			&i.GroupID,
			&i.Measurement,
			&i.PictureUrl,
			&i.ColorCode,
			&i.BrandID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients
SET name = COALESCE($2, name),
    name_i18n = COALESCE($3, name_i18n),
    group_id = COALESCE($4, group_id),
    measurement = COALESCE($5, measurement),
    picture_url = COALESCE($6, picture_url),
    color_code = COALESCE($7, color_code),
    brand_id = COALESCE($8, brand_id),
    updated_at = NOW()
WHERE id = $1 AND deleted_at = 0
RETURNING id, name, name_i18n, group_id, measurement, picture_url, color_code, brand_id, created_at, updated_at, deleted_at
`

type UpdateIngredientParams struct {
	ID          uuid.UUID           `json:"id"`
	Name        string              `json:"name"`
	NameI18n    pgtype.UUID         `json:"name_i18n"`
	GroupID     pgtype.UUID         `json:"group_id"`
	Measurement NullMeasurementType `json:"measurement"`
	PictureUrl  *string             `json:"picture_url"`
	ColorCode   *string             `json:"color_code"`
	BrandID     pgtype.UUID         `json:"brand_id"`
}

// UpdateIngredient updates an ingredient
func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.ID,
		arg.Name,
		arg.NameI18n,
		arg.GroupID,
		arg.Measurement,
		arg.PictureUrl,
		arg.ColorCode,
		arg.BrandID,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.GroupID,
		&i.Measurement,
		&i.PictureUrl,
		&i.ColorCode,
		&i.BrandID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateIngredientGroup = `-- name: UpdateIngredientGroup :one
UPDATE ingredient_groups
SET name = COALESCE($2, name),
    picture_url = COALESCE($3, picture_url),
    name_i18n = COALESCE($4, name_i18n),
    color_code = COALESCE($5, color_code),
    updated_at = NOW()
WHERE id = $1 AND deleted_at = 0
RETURNING id, name, picture_url, name_i18n, color_code, created_at, updated_at, deleted_at
`

type UpdateIngredientGroupParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	PictureUrl *string     `json:"picture_url"`
	NameI18n   pgtype.UUID `json:"name_i18n"`
	ColorCode  *string     `json:"color_code"`
}

type UpdateIngredientGroupRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	PictureUrl *string            `json:"picture_url"`
	NameI18n   pgtype.UUID        `json:"name_i18n"`
	ColorCode  *string            `json:"color_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  *int64             `json:"deleted_at"`
}

// UpdateIngredientGroup updates an ingredient group
func (q *Queries) UpdateIngredientGroup(ctx context.Context, arg UpdateIngredientGroupParams) (UpdateIngredientGroupRow, error) {
	row := q.db.QueryRow(ctx, updateIngredientGroup,
		arg.ID,
		arg.Name,
		arg.PictureUrl,
		arg.NameI18n,
		arg.ColorCode,
	)
	var i UpdateIngredientGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.NameI18n,
		&i.ColorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateIngredientStock = `-- name: UpdateIngredientStock :one
UPDATE ingredient_stock
SET quantity = COALESCE($2, quantity),
    updated_at = NOW()
WHERE id = $1 AND deleted_at = 0
RETURNING id, ingredient_id, quantity, branch_id, created_at, updated_at, deleted_at
`

type UpdateIngredientStockParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int64     `json:"quantity"`
}

// UpdateIngredientStock updates ingredient stock quantity
func (q *Queries) UpdateIngredientStock(ctx context.Context, arg UpdateIngredientStockParams) (IngredientStock, error) {
	row := q.db.QueryRow(ctx, updateIngredientStock, arg.ID, arg.Quantity)
	var i IngredientStock
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Quantity,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
