// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InvoiceStatus string

const (
	InvoiceStatusPending   InvoiceStatus = "pending"
	InvoiceStatusArrived   InvoiceStatus = "arrived"
	InvoiceStatusReceived  InvoiceStatus = "received"
	InvoiceStatusCancelled InvoiceStatus = "cancelled"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus `json:"invoice_status"`
	Valid         bool          `json:"valid"` // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type MeasurementType string

const (
	MeasurementTypeKg    MeasurementType = "kg"
	MeasurementTypeL     MeasurementType = "l"
	MeasurementTypePiece MeasurementType = "piece"
)

func (e *MeasurementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeasurementType(s)
	case string:
		*e = MeasurementType(s)
	default:
		return fmt.Errorf("unsupported scan type for MeasurementType: %T", src)
	}
	return nil
}

type NullMeasurementType struct {
	MeasurementType MeasurementType `json:"measurement_type"`
	Valid           bool            `json:"valid"` // Valid is true if MeasurementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeasurementType) Scan(value interface{}) error {
	if value == nil {
		ns.MeasurementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeasurementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeasurementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeasurementType), nil
}

type OrderItemsStatus string

const (
	OrderItemsStatusPending   OrderItemsStatus = "pending"
	OrderItemsStatusCooking   OrderItemsStatus = "cooking"
	OrderItemsStatusReady     OrderItemsStatus = "ready"
	OrderItemsStatusCancelled OrderItemsStatus = "cancelled"
)

func (e *OrderItemsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderItemsStatus(s)
	case string:
		*e = OrderItemsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderItemsStatus: %T", src)
	}
	return nil
}

type NullOrderItemsStatus struct {
	OrderItemsStatus OrderItemsStatus `json:"order_items_status"`
	Valid            bool             `json:"valid"` // Valid is true if OrderItemsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderItemsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderItemsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderItemsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderItemsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderItemsStatus), nil
}

type OrderStatus string

const (
	OrderStatusOpen      OrderStatus = "open"
	OrderStatusCooking   OrderStatus = "cooking"
	OrderStatusReady     OrderStatus = "ready"
	OrderStatusServed    OrderStatus = "served"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type TableStatus string

const (
	TableStatusFree TableStatus = "free"
	TableStatusBusy TableStatus = "busy"
)

func (e *TableStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TableStatus(s)
	case string:
		*e = TableStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TableStatus: %T", src)
	}
	return nil
}

type NullTableStatus struct {
	TableStatus TableStatus `json:"table_status"`
	Valid       bool        `json:"valid"` // Valid is true if TableStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTableStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TableStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TableStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTableStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TableStatus), nil
}

type TransferStatus string

const (
	TransferStatusDraft   TransferStatus = "draft"
	TransferStatusActive  TransferStatus = "active"
	TransferStatusDeleted TransferStatus = "deleted"
)

func (e *TransferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferStatus(s)
	case string:
		*e = TransferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferStatus: %T", src)
	}
	return nil
}

type NullTransferStatus struct {
	TransferStatus TransferStatus `json:"transfer_status"`
	Valid          bool           `json:"valid"` // Valid is true if TransferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferStatus), nil
}

type Attendance struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	OpenDate     pgtype.Date        `json:"open_date"`
	CloseDate    pgtype.Date        `json:"close_date"`
	Difference   *int32             `json:"difference"`
	WorkingHours *int32             `json:"working_hours"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
	BranchID     pgtype.UUID        `json:"branch_id"`
}

type BillDailyCounter struct {
	Day    pgtype.Date `json:"day"`
	LastNo int32       `json:"last_no"`
}

type Branch struct {
	ID                    uuid.UUID          `json:"id"`
	Name                  string             `json:"name"`
	NameI18n              pgtype.UUID        `json:"name_i18n"`
	Address               *string            `json:"address"`
	Phone                 *string            `json:"phone"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             *int64             `json:"deleted_at"`
	DefaultServicePercent pgtype.Numeric     `json:"default_service_percent"`
}

type CafeTable struct {
	ID        uuid.UUID          `json:"id"`
	HallID    uuid.UUID          `json:"hall_id"`
	Number    int32              `json:"number"`
	Capacity  int32              `json:"capacity"`
	Status    NullTableStatus    `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt *int64             `json:"deleted_at"`
	PosX      int32              `json:"pos_x"`
	PosY      int32              `json:"pos_y"`
	Width     int32              `json:"width"`
	Height    int32              `json:"height"`
	Rotation  int32              `json:"rotation"`
}

type Calculation struct {
	ID                  uuid.UUID          `json:"id"`
	GoodID              pgtype.UUID        `json:"good_id"`
	CompoundID          pgtype.UUID        `json:"compound_id"`
	IngredientID        pgtype.UUID        `json:"ingredient_id"`
	ComponentCompoundID pgtype.UUID        `json:"component_compound_id"`
	Quantity            pgtype.Numeric     `json:"quantity"`
	MeasurementUnit     string             `json:"measurement_unit"`
	PricePerUnit        pgtype.Numeric     `json:"price_per_unit"`
	TotalCost           pgtype.Numeric     `json:"total_cost"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           *int64             `json:"deleted_at"`
}

type Category struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	PictureUrl   *string            `json:"picture_url"`
	ColorCode    *string            `json:"color_code"`
	NameI18n     pgtype.UUID        `json:"name_i18n"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	StorageID    pgtype.UUID        `json:"storage_id"`
	Parent       pgtype.UUID        `json:"parent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

type ChangeLog struct {
	ID        int64     `json:"id"`
	BrandID   *string   `json:"brand_id"`
	Entity    string    `json:"entity"`
	Action    string    `json:"action"`
	EntityID  string    `json:"entity_id"`
	Payload   []byte    `json:"payload"`
	ChangedAt time.Time `json:"changed_at"`
}

type Compound struct {
	ID              uuid.UUID           `json:"id"`
	Name            string              `json:"name"`
	NameI18n        pgtype.UUID         `json:"name_i18n"`
	Description     *string             `json:"description"`
	DescriptionI18n pgtype.UUID         `json:"description_i18n"`
	Quantity        *int32              `json:"quantity"`
	PictureUrl      *string             `json:"picture_url"`
	ColorCode       *string             `json:"color_code"`
	Measurement     NullMeasurementType `json:"measurement"`
	Price           pgtype.Numeric      `json:"price"`
	DepartmentID    pgtype.UUID         `json:"department_id"`
	CostPrice       pgtype.Numeric      `json:"cost_price"`
	Profit          pgtype.Numeric      `json:"profit"`
	ProfitMargin    pgtype.Numeric      `json:"profit_margin"`
	CreatedAt       pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz  `json:"updated_at"`
	DeletedAt       *int64              `json:"deleted_at"`
}

type CompoundStock struct {
	ID         uuid.UUID          `json:"id"`
	CompoundID uuid.UUID          `json:"compound_id"`
	Quantity   int64              `json:"quantity"`
	BranchID   uuid.UUID          `json:"branch_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  *int64             `json:"deleted_at"`
}

type CompoundsDetail struct {
	ID           uuid.UUID          `json:"id"`
	CompoundID   uuid.UUID          `json:"compound_id"`
	IngredientID uuid.UUID          `json:"ingredient_id"`
	Quantity     int64              `json:"quantity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

type Deduction struct {
	ID              uuid.UUID          `json:"id"`
	Number          int64              `json:"number"`
	Date            pgtype.Date        `json:"date"`
	ActGroupID      pgtype.UUID        `json:"act_group_id"`
	StorageID       uuid.UUID          `json:"storage_id"`
	Description     *string            `json:"description"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	Status          string             `json:"status"`
	Balance         pgtype.Numeric     `json:"balance"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       int64              `json:"deleted_at"`
}

type DeductionActGroup struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt int64              `json:"deleted_at"`
	BranchID  pgtype.UUID        `json:"branch_id"`
}

type DeductionItem struct {
	ID           uuid.UUID          `json:"id"`
	DeductionID  uuid.UUID          `json:"deduction_id"`
	IngredientID pgtype.UUID        `json:"ingredient_id"`
	GoodID       pgtype.UUID        `json:"good_id"`
	CompoundID   pgtype.UUID        `json:"compound_id"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    int64              `json:"deleted_at"`
}

type DeductionItemIngredient struct {
	ID              uuid.UUID          `json:"id"`
	DeductionItemID uuid.UUID          `json:"deduction_item_id"`
	IngredientID    uuid.UUID          `json:"ingredient_id"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	StockBefore     pgtype.Numeric     `json:"stock_before"`
	StockAfter      pgtype.Numeric     `json:"stock_after"`
	PricePerUnit    pgtype.Numeric     `json:"price_per_unit"`
	Amount          pgtype.Numeric     `json:"amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       int64              `json:"deleted_at"`
}

type Department struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	ColorCode  *string            `json:"color_code"`
	PictureUrl *string            `json:"picture_url"`
	NameI18n   pgtype.UUID        `json:"name_i18n"`
	StorageID  pgtype.UUID        `json:"storage_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  *int64             `json:"deleted_at"`
}

type Good struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     *string        `json:"description"`
	NameI18n        pgtype.UUID    `json:"name_i18n"`
	DescriptionI18n pgtype.UUID    `json:"description_i18n"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	DepartmentID    pgtype.UUID    `json:"department_id"`
	PictureUrl      *string        `json:"picture_url"`
	ColorCode       *string        `json:"color_code"`
	Price           pgtype.Numeric `json:"price"`
	CookTime        *int32         `json:"cook_time"`
	// Total preparation cost (sum of all calculations total_cost)
	CostPrice pgtype.Numeric `json:"cost_price"`
	// Profit = price - cost_price
	Profit pgtype.Numeric `json:"profit"`
	// Profit margin percentage = (profit / cost_price) * 100
	ProfitMargin pgtype.Numeric     `json:"profit_margin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

type GoodsDetail struct {
	ID           uuid.UUID           `json:"id"`
	GoodID       uuid.UUID           `json:"good_id"`
	IngredientID pgtype.UUID         `json:"ingredient_id"`
	CompoundID   pgtype.UUID         `json:"compound_id"`
	Measurement  NullMeasurementType `json:"measurement"`
	Quantity     int64               `json:"quantity"`
	CreatedAt    pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `json:"updated_at"`
	DeletedAt    *int64              `json:"deleted_at"`
}

type Hall struct {
	ID        uuid.UUID          `json:"id"`
	BranchID  uuid.UUID          `json:"branch_id"`
	Name      string             `json:"name"`
	NameI18n  pgtype.UUID        `json:"name_i18n"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt *int64             `json:"deleted_at"`
	Width     int32              `json:"width"`
	Height    int32              `json:"height"`
}

type Ingredient struct {
	ID           uuid.UUID           `json:"id"`
	Name         string              `json:"name"`
	NameI18n     pgtype.UUID         `json:"name_i18n"`
	GroupID      pgtype.UUID         `json:"group_id"`
	Measurement  NullMeasurementType `json:"measurement"`
	PictureUrl   *string             `json:"picture_url"`
	ColorCode    *string             `json:"color_code"`
	BrandID      pgtype.UUID         `json:"brand_id"`
	PricePerUnit pgtype.Numeric      `json:"price_per_unit"`
	CreatedAt    pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `json:"updated_at"`
	DeletedAt    *int64              `json:"deleted_at"`
	BranchID     pgtype.UUID         `json:"branch_id"`
}

type IngredientGroup struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	PictureUrl *string            `json:"picture_url"`
	ColorCode  *string            `json:"color_code"`
	NameI18n   pgtype.UUID        `json:"name_i18n"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  *int64             `json:"deleted_at"`
	BranchID   pgtype.UUID        `json:"branch_id"`
}

type IngredientStock struct {
	ID           uuid.UUID          `json:"id"`
	IngredientID uuid.UUID          `json:"ingredient_id"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	BranchID     pgtype.UUID        `json:"branch_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
	StorageID    pgtype.UUID        `json:"storage_id"`
}

type IngredientStockMovement struct {
	ID           uuid.UUID          `json:"id"`
	StorageID    uuid.UUID          `json:"storage_id"`
	IngredientID uuid.UUID          `json:"ingredient_id"`
	EventType    string             `json:"event_type"`
	QtyIn        pgtype.Numeric     `json:"qty_in"`
	QtyOut       pgtype.Numeric     `json:"qty_out"`
	StockBefore  pgtype.Numeric     `json:"stock_before"`
	StockAfter   pgtype.Numeric     `json:"stock_after"`
	PricePerUnit pgtype.Numeric     `json:"price_per_unit"`
	SourceType   *string            `json:"source_type"`
	SourceID     pgtype.UUID        `json:"source_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Inventory struct {
	ID              uuid.UUID          `json:"id"`
	Number          int64              `json:"number"`
	Date            pgtype.Date        `json:"date"`
	StorageID       uuid.UUID          `json:"storage_id"`
	Description     *string            `json:"description"`
	DescriptionI18n pgtype.UUID        `json:"description_i18n"`
	Status          string             `json:"status"`
	SurplusAmount   pgtype.Numeric     `json:"surplus_amount"`
	ShortageAmount  pgtype.Numeric     `json:"shortage_amount"`
	RemainingAmount pgtype.Numeric     `json:"remaining_amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       int64              `json:"deleted_at"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
}

type InventoryItem struct {
	ID              uuid.UUID          `json:"id"`
	InventoryID     uuid.UUID          `json:"inventory_id"`
	IngredientID    uuid.UUID          `json:"ingredient_id"`
	CountedQuantity pgtype.Numeric     `json:"counted_quantity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       int64              `json:"deleted_at"`
}

type Invoice struct {
	ID          uuid.UUID          `json:"id"`
	SupplierID  uuid.UUID          `json:"supplier_id"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Status      NullInvoiceStatus  `json:"status"`
	Date        pgtype.Timestamp   `json:"date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
	StorageID   pgtype.UUID        `json:"storage_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
}

type InvoiceDetailed struct {
	ID           uuid.UUID          `json:"id"`
	InvoiceID    uuid.UUID          `json:"invoice_id"`
	IngredientID uuid.UUID          `json:"ingredient_id"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	Price        pgtype.Numeric     `json:"price"`
	PricePerUnit pgtype.Numeric     `json:"price_per_unit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
}

type Order struct {
	ID              uuid.UUID          `json:"id"`
	TableID         pgtype.UUID        `json:"table_id"`
	WaiterID        pgtype.UUID        `json:"waiter_id"`
	CashierID       pgtype.UUID        `json:"cashier_id"`
	Status          NullOrderStatus    `json:"status"`
	GuestCount      *int32             `json:"guest_count"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	Comment         *string            `json:"comment"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       *int64             `json:"deleted_at"`
	BillNo          int32              `json:"bill_no"`
	BillStatus      interface{}        `json:"bill_status"`
	BillOpenedAt    time.Time          `json:"bill_opened_at"`
	BillClosedAt    pgtype.Timestamptz `json:"bill_closed_at"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	PaymentType     interface{}        `json:"payment_type"`
	FoodCost        pgtype.Numeric     `json:"food_cost"`
	FoodTotal       pgtype.Numeric     `json:"food_total"`
	ServicePercent  pgtype.Numeric     `json:"service_percent"`
	ServiceAmount   pgtype.Numeric     `json:"service_amount"`
	DiscountPercent pgtype.Numeric     `json:"discount_percent"`
	DiscountAmount  pgtype.Numeric     `json:"discount_amount"`
	DiscountComment *string            `json:"discount_comment"`
	GrandTotal      pgtype.Numeric     `json:"grand_total"`
	StockConsumedAt pgtype.Timestamptz `json:"stock_consumed_at"`
	BranchID        pgtype.UUID        `json:"branch_id"`
}

type OrderItem struct {
	ID        uuid.UUID            `json:"id"`
	GoodID    uuid.UUID            `json:"good_id"`
	OrderID   uuid.UUID            `json:"order_id"`
	Quantity  int32                `json:"quantity"`
	Price     pgtype.Numeric       `json:"price"`
	Status    NullOrderItemsStatus `json:"status"`
	Comment   *string              `json:"comment"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt pgtype.Timestamptz   `json:"updated_at"`
	DeletedAt *int64               `json:"deleted_at"`
}

type PriceForPlan struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Amount    int32              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type QrSession struct {
	ID        uuid.UUID          `json:"id"`
	TableID   uuid.UUID          `json:"table_id"`
	DeviceID  *string            `json:"device_id"`
	StartTime pgtype.Timestamp   `json:"start_time"`
	EndTime   pgtype.Timestamp   `json:"end_time"`
	IsActive  *bool              `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt *int64             `json:"deleted_at"`
}

type Shift struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Role        *string            `json:"role"`
	WorkingDays *string            `json:"working_days"`
	OpenTime    *int64             `json:"open_time"`
	CloseTime   *int64             `json:"close_time"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

type Storage struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	BranchID   pgtype.UUID        `json:"branch_id"`
	NameI18n   pgtype.UUID        `json:"name_i18n"`
	PictureUrl *string            `json:"picture_url"`
	ColorCode  *string            `json:"color_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  *int64             `json:"deleted_at"`
}

type Supplier struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	PhoneNumber *string            `json:"phone_number"`
	Location    *string            `json:"location"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
	BranchID    pgtype.UUID        `json:"branch_id"`
}

type Transfer struct {
	ID            uuid.UUID          `json:"id"`
	Number        *int64             `json:"number"`
	FromBranchID  uuid.UUID          `json:"from_branch_id"`
	ToBranchID    uuid.UUID          `json:"to_branch_id"`
	FromStorageID uuid.UUID          `json:"from_storage_id"`
	ToStorageID   uuid.UUID          `json:"to_storage_id"`
	ActGroupID    pgtype.UUID        `json:"act_group_id"`
	Description   *string            `json:"description"`
	Status        TransferStatus     `json:"status"`
	Date          pgtype.Timestamptz `json:"date"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     int64              `json:"deleted_at"`
}

type TransferItem struct {
	ID             uuid.UUID          `json:"id"`
	TransferID     uuid.UUID          `json:"transfer_id"`
	IngredientID   uuid.UUID          `json:"ingredient_id"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	StockQtyBefore pgtype.Numeric     `json:"stock_qty_before"`
	StockQtyAfter  pgtype.Numeric     `json:"stock_qty_after"`
	Price          pgtype.Numeric     `json:"price"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      int64              `json:"deleted_at"`
}

type Translation struct {
	ID        uuid.UUID          `json:"id"`
	Uz        *string            `json:"uz"`
	Ru        *string            `json:"ru"`
	En        *string            `json:"en"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt *int64             `json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	FullName     *string            `json:"full_name"`
	Username     *string            `json:"username"`
	Role         string             `json:"role"`
	Email        *string            `json:"email"`
	ShiftID      pgtype.UUID        `json:"shift_id"`
	Pincode      *string            `json:"pincode"`
	HashPassword *string            `json:"hash_password"`
	BrandID      pgtype.UUID        `json:"brand_id"`
	PhoneNumber  *string            `json:"phone_number"`
	FcmToken     *string            `json:"fcm_token"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
	BranchID     pgtype.UUID        `json:"branch_id"`
}

type UserPayment struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	PriceForPlanID        uuid.UUID          `json:"price_for_plan_id"`
	IsPaid                *bool              `json:"is_paid"`
	ClickTransID          *int32             `json:"click_trans_id"`
	ClickPayDocID         *int32             `json:"click_pay_doc_id"`
	Error                 *int32             `json:"error"`
	ErrorNote             *string            `json:"error_note"`
	Status                *string            `json:"status"`
	MerchantPrepareID     *int32             `json:"merchant_prepare_id"`
	PaymeID               *string            `json:"payme_id"`
	Provider              string             `json:"provider"`
	OrderNumber           int32              `json:"order_number"`
	PaidAt                *int64             `json:"paid_at"`
	TimePaymeTransCreated *int64             `json:"time_payme_trans_created"`
	Reason                *int64             `json:"reason"`
	Amount                int32              `json:"amount"`
	CancelTime            *int64             `json:"cancel_time"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	BranchID              pgtype.UUID        `json:"branch_id"`
}
