// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modifiers.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createModifier = `-- name: CreateModifier :one
INSERT INTO modifiers (
    id,
    name,
    name_i18n,
    description,
    code,
    price_delta,
    cost_delta,
    is_active,
    picture_url
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING
    id,
    name,
    name_i18n,
    description,
    code,
    price_delta,
    cost_delta,
    is_active,
    picture_url,
    created_at,
    updated_at,
    deleted_at
`

type CreateModifierParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	NameI18n    pgtype.UUID    `json:"name_i18n"`
	Description *string        `json:"description"`
	Code        *string        `json:"code"`
	PriceDelta  pgtype.Numeric `json:"price_delta"`
	CostDelta   pgtype.Numeric `json:"cost_delta"`
	IsActive    bool           `json:"is_active"`
	PictureUrl  *string        `json:"picture_url"`
}

func (q *Queries) CreateModifier(ctx context.Context, arg CreateModifierParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, createModifier,
		arg.ID,
		arg.Name,
		arg.NameI18n,
		arg.Description,
		arg.Code,
		arg.PriceDelta,
		arg.CostDelta,
		arg.IsActive,
		arg.PictureUrl,
	)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.Description,
		&i.Code,
		&i.PriceDelta,
		&i.CostDelta,
		&i.IsActive,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteModifier = `-- name: DeleteModifier :exec
UPDATE modifiers
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
  AND deleted_at = 0
`

func (q *Queries) DeleteModifier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteModifier, id)
	return err
}

const getAllModifiers = `-- name: GetAllModifiers :many
SELECT
    id,
    name,
    name_i18n,
    description,
    code,
    price_delta,
    cost_delta,
    is_active,
    picture_url,
    created_at,
    updated_at,
    deleted_at
FROM modifiers
WHERE deleted_at = 0
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllModifiersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllModifiers(ctx context.Context, arg GetAllModifiersParams) ([]Modifier, error) {
	rows, err := q.db.Query(ctx, getAllModifiers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modifier
	for rows.Next() {
		var i Modifier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameI18n,
			&i.Description,
			&i.Code,
			&i.PriceDelta,
			&i.CostDelta,
			&i.IsActive,
			&i.PictureUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModifierByCode = `-- name: GetModifierByCode :one
SELECT
    id,
    name,
    name_i18n,
    description,
    code,
    price_delta,
    cost_delta,
    is_active,
    picture_url,
    created_at,
    updated_at,
    deleted_at
FROM modifiers
WHERE code = $1
  AND deleted_at = 0
`

func (q *Queries) GetModifierByCode(ctx context.Context, code *string) (Modifier, error) {
	row := q.db.QueryRow(ctx, getModifierByCode, code)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.Description,
		&i.Code,
		&i.PriceDelta,
		&i.CostDelta,
		&i.IsActive,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getModifierByID = `-- name: GetModifierByID :one
SELECT
    id,
    name,
    name_i18n,
    description,
    code,
    price_delta,
    cost_delta,
    is_active,
    picture_url,
    created_at,
    updated_at,
    deleted_at
FROM modifiers
WHERE id = $1
  AND deleted_at = 0
`

func (q *Queries) GetModifierByID(ctx context.Context, id uuid.UUID) (Modifier, error) {
	row := q.db.QueryRow(ctx, getModifierByID, id)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.Description,
		&i.Code,
		&i.PriceDelta,
		&i.CostDelta,
		&i.IsActive,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreModifier = `-- name: RestoreModifier :exec
UPDATE modifiers
SET deleted_at = 0
WHERE id = $1
  AND deleted_at <> 0
`

func (q *Queries) RestoreModifier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreModifier, id)
	return err
}

const searchModifiers = `-- name: SearchModifiers :many
SELECT
    id,
    name,
    name_i18n,
    description,
    code,
    price_delta,
    cost_delta,
    is_active,
    picture_url,
    created_at,
    updated_at,
    deleted_at
FROM modifiers
WHERE deleted_at = 0
  AND (
      name ILIKE '%' || $1 || '%'
      OR COALESCE(description, '') ILIKE '%' || $1 || '%'
      OR COALESCE(code, '') ILIKE '%' || $1 || '%'
  )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchModifiersParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) SearchModifiers(ctx context.Context, arg SearchModifiersParams) ([]Modifier, error) {
	rows, err := q.db.Query(ctx, searchModifiers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modifier
	for rows.Next() {
		var i Modifier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameI18n,
			&i.Description,
			&i.Code,
			&i.PriceDelta,
			&i.CostDelta,
			&i.IsActive,
			&i.PictureUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModifier = `-- name: UpdateModifier :one
UPDATE modifiers
SET
    name = $2,
    name_i18n = $3,
    description = $4,
    code = $5,
    price_delta = $6,
    cost_delta = $7,
    is_active = $8,
    picture_url = $9
WHERE id = $1
  AND deleted_at = 0
RETURNING
    id,
    name,
    name_i18n,
    description,
    code,
    price_delta,
    cost_delta,
    is_active,
    picture_url,
    created_at,
    updated_at,
    deleted_at
`

type UpdateModifierParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	NameI18n    pgtype.UUID    `json:"name_i18n"`
	Description *string        `json:"description"`
	Code        *string        `json:"code"`
	PriceDelta  pgtype.Numeric `json:"price_delta"`
	CostDelta   pgtype.Numeric `json:"cost_delta"`
	IsActive    bool           `json:"is_active"`
	PictureUrl  *string        `json:"picture_url"`
}

func (q *Queries) UpdateModifier(ctx context.Context, arg UpdateModifierParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, updateModifier,
		arg.ID,
		arg.Name,
		arg.NameI18n,
		arg.Description,
		arg.Code,
		arg.PriceDelta,
		arg.CostDelta,
		arg.IsActive,
		arg.PictureUrl,
	)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.Description,
		&i.Code,
		&i.PriceDelta,
		&i.CostDelta,
		&i.IsActive,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
