// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modifier_calculation.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createModifierCalculation = `-- name: CreateModifierCalculation :one
INSERT INTO modifier_calculation (
    id,
    modifier_id,
    ingredient_id,
    component_compound_id,
    quantity,
    measurement_unit,
    price_per_unit,
    total_cost
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id,
    modifier_id,
    ingredient_id,
    component_compound_id,
    quantity,
    measurement_unit,
    price_per_unit,
    total_cost,
    created_at,
    updated_at,
    deleted_at
`

type CreateModifierCalculationParams struct {
	ID                  uuid.UUID      `json:"id"`
	ModifierID          uuid.UUID      `json:"modifier_id"`
	IngredientID        pgtype.UUID    `json:"ingredient_id"`
	ComponentCompoundID pgtype.UUID    `json:"component_compound_id"`
	Quantity            pgtype.Numeric `json:"quantity"`
	MeasurementUnit     string         `json:"measurement_unit"`
	PricePerUnit        pgtype.Numeric `json:"price_per_unit"`
	TotalCost           pgtype.Numeric `json:"total_cost"`
}

func (q *Queries) CreateModifierCalculation(ctx context.Context, arg CreateModifierCalculationParams) (ModifierCalculation, error) {
	row := q.db.QueryRow(ctx, createModifierCalculation,
		arg.ID,
		arg.ModifierID,
		arg.IngredientID,
		arg.ComponentCompoundID,
		arg.Quantity,
		arg.MeasurementUnit,
		arg.PricePerUnit,
		arg.TotalCost,
	)
	var i ModifierCalculation
	err := row.Scan(
		&i.ID,
		&i.ModifierID,
		&i.IngredientID,
		&i.ComponentCompoundID,
		&i.Quantity,
		&i.MeasurementUnit,
		&i.PricePerUnit,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteModifierCalculation = `-- name: DeleteModifierCalculation :exec
UPDATE modifier_calculation
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
  AND deleted_at = 0
`

func (q *Queries) DeleteModifierCalculation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteModifierCalculation, id)
	return err
}

const deleteModifierCalculationsByModifierID = `-- name: DeleteModifierCalculationsByModifierID :exec
UPDATE modifier_calculation
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE modifier_id = $1
  AND deleted_at = 0
`

func (q *Queries) DeleteModifierCalculationsByModifierID(ctx context.Context, modifierID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteModifierCalculationsByModifierID, modifierID)
	return err
}

const getModifierCalculationByID = `-- name: GetModifierCalculationByID :one
SELECT
    id,
    modifier_id,
    ingredient_id,
    component_compound_id,
    quantity,
    measurement_unit,
    price_per_unit,
    total_cost,
    created_at,
    updated_at,
    deleted_at
FROM modifier_calculation
WHERE id = $1
  AND deleted_at = 0
`

func (q *Queries) GetModifierCalculationByID(ctx context.Context, id uuid.UUID) (ModifierCalculation, error) {
	row := q.db.QueryRow(ctx, getModifierCalculationByID, id)
	var i ModifierCalculation
	err := row.Scan(
		&i.ID,
		&i.ModifierID,
		&i.IngredientID,
		&i.ComponentCompoundID,
		&i.Quantity,
		&i.MeasurementUnit,
		&i.PricePerUnit,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getModifierCalculationsByModifierID = `-- name: GetModifierCalculationsByModifierID :many
SELECT
    id,
    modifier_id,
    ingredient_id,
    component_compound_id,
    quantity,
    measurement_unit,
    price_per_unit,
    total_cost,
    created_at,
    updated_at,
    deleted_at
FROM modifier_calculation
WHERE modifier_id = $1
  AND deleted_at = 0
ORDER BY created_at ASC
`

func (q *Queries) GetModifierCalculationsByModifierID(ctx context.Context, modifierID uuid.UUID) ([]ModifierCalculation, error) {
	rows, err := q.db.Query(ctx, getModifierCalculationsByModifierID, modifierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModifierCalculation
	for rows.Next() {
		var i ModifierCalculation
		if err := rows.Scan(
			&i.ID,
			&i.ModifierID,
			&i.IngredientID,
			&i.ComponentCompoundID,
			&i.Quantity,
			&i.MeasurementUnit,
			&i.PricePerUnit,
			&i.TotalCost,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCostByModifierID = `-- name: GetTotalCostByModifierID :one
SELECT COALESCE(SUM(total_cost), 0) AS total_cost
FROM modifier_calculation
WHERE modifier_id = $1
  AND deleted_at = 0
`

func (q *Queries) GetTotalCostByModifierID(ctx context.Context, modifierID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalCostByModifierID, modifierID)
	var total_cost interface{}
	err := row.Scan(&total_cost)
	return total_cost, err
}

const updateModifierCalculation = `-- name: UpdateModifierCalculation :one
UPDATE modifier_calculation
SET
    quantity = COALESCE($2, quantity),
    measurement_unit = COALESCE($3, measurement_unit),
    price_per_unit = COALESCE($4, price_per_unit),
    total_cost = COALESCE($5, total_cost),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at = 0
RETURNING
    id,
    modifier_id,
    ingredient_id,
    component_compound_id,
    quantity,
    measurement_unit,
    price_per_unit,
    total_cost,
    created_at,
    updated_at,
    deleted_at
`

type UpdateModifierCalculationParams struct {
	ID              uuid.UUID      `json:"id"`
	Quantity        pgtype.Numeric `json:"quantity"`
	MeasurementUnit string         `json:"measurement_unit"`
	PricePerUnit    pgtype.Numeric `json:"price_per_unit"`
	TotalCost       pgtype.Numeric `json:"total_cost"`
}

func (q *Queries) UpdateModifierCalculation(ctx context.Context, arg UpdateModifierCalculationParams) (ModifierCalculation, error) {
	row := q.db.QueryRow(ctx, updateModifierCalculation,
		arg.ID,
		arg.Quantity,
		arg.MeasurementUnit,
		arg.PricePerUnit,
		arg.TotalCost,
	)
	var i ModifierCalculation
	err := row.Scan(
		&i.ID,
		&i.ModifierID,
		&i.IngredientID,
		&i.ComponentCompoundID,
		&i.Quantity,
		&i.MeasurementUnit,
		&i.PricePerUnit,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
