// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignCashierToOrder = `-- name: AssignCashierToOrder :one
UPDATE orders
SET cashier_id = $2,
    updated_at = NOW()
WHERE orders.id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type AssignCashierToOrderParams struct {
	ID        uuid.UUID   `json:"id"`
	CashierID pgtype.UUID `json:"cashier_id"`
}

type AssignCashierToOrderRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) AssignCashierToOrder(ctx context.Context, arg AssignCashierToOrderParams) (AssignCashierToOrderRow, error) {
	row := q.db.QueryRow(ctx, assignCashierToOrder, arg.ID, arg.CashierID)
	var i AssignCashierToOrderRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const assignWaiterToOrder = `-- name: AssignWaiterToOrder :one
UPDATE orders
SET waiter_id = $2,
    updated_at = NOW()
WHERE orders.id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type AssignWaiterToOrderParams struct {
	ID       uuid.UUID   `json:"id"`
	WaiterID pgtype.UUID `json:"waiter_id"`
}

type AssignWaiterToOrderRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) AssignWaiterToOrder(ctx context.Context, arg AssignWaiterToOrderParams) (AssignWaiterToOrderRow, error) {
	row := q.db.QueryRow(ctx, assignWaiterToOrder, arg.ID, arg.WaiterID)
	var i AssignWaiterToOrderRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1 AND deleted_at = 0
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type CancelOrderRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) CancelOrder(ctx context.Context, id uuid.UUID) (CancelOrderRow, error) {
	row := q.db.QueryRow(ctx, cancelOrder, id)
	var i CancelOrderRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const cancelOrderItem = `-- name: CancelOrderItem :one
UPDATE order_items
SET status = 'cancelled',
    updated_at = NOW()
WHERE order_items.id = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
RETURNING id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
`

func (q *Queries) CancelOrderItem(ctx context.Context, id uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRow(ctx, cancelOrderItem, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
	)
	return i, err
}

const countActiveOrders = `-- name: CountActiveOrders :one
SELECT COUNT(*) FROM orders
WHERE status NOT IN ('paid', 'cancelled')
  AND deleted_at = 0
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

func (q *Queries) CountActiveOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrderItems = `-- name: CountOrderItems :one
SELECT COUNT(*) FROM order_items
WHERE order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) CountOrderItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrderItemsByOrder = `-- name: CountOrderItemsByOrder :one
SELECT COUNT(*) FROM order_items
WHERE order_items.order_id = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) CountOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderItemsByOrder, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrderItemsByStatus = `-- name: CountOrderItemsByStatus :one
SELECT COUNT(*) FROM order_items
WHERE order_items.status = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) CountOrderItemsByStatus(ctx context.Context, status NullOrderItemsStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderItemsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*) FROM orders
WHERE deleted_at = 0
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByStatus = `-- name: CountOrdersByStatus :one
SELECT COUNT(*) FROM orders
WHERE status = $1
  AND deleted_at = 0
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

func (q *Queries) CountOrdersByStatus(ctx context.Context, status NullOrderStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, table_id, waiter_id, cashier_id, status, guest_count, total_amount, comment, branch_id)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    COALESCE(
        (SELECT h.branch_id FROM cafe_tables ct JOIN halls h ON h.id = ct.hall_id WHERE ct.id = $2),
        (SELECT s.branch_id FROM users u JOIN shifts s ON s.id = u.shift_id WHERE u.id = $3),
        (SELECT s.branch_id FROM users u JOIN shifts s ON s.id = u.shift_id WHERE u.id = $4)
    )
)
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type CreateOrderParams struct {
	ID          uuid.UUID       `json:"id"`
	TableID     pgtype.UUID     `json:"table_id"`
	WaiterID    pgtype.UUID     `json:"waiter_id"`
	CashierID   pgtype.UUID     `json:"cashier_id"`
	Status      NullOrderStatus `json:"status"`
	GuestCount  *int32          `json:"guest_count"`
	TotalAmount pgtype.Numeric  `json:"total_amount"`
	Comment     *string         `json:"comment"`
}

type CreateOrderRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.TableID,
		arg.WaiterID,
		arg.CashierID,
		arg.Status,
		arg.GuestCount,
		arg.TotalAmount,
		arg.Comment,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, good_id, order_id, quantity, price, cost_price, status, comment)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
`

type CreateOrderItemParams struct {
	ID        uuid.UUID            `json:"id"`
	GoodID    uuid.UUID            `json:"good_id"`
	OrderID   uuid.UUID            `json:"order_id"`
	Quantity  int32                `json:"quantity"`
	Price     pgtype.Numeric       `json:"price"`
	CostPrice pgtype.Numeric       `json:"cost_price"`
	Status    NullOrderItemsStatus `json:"status"`
	Comment   *string              `json:"comment"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.GoodID,
		arg.OrderID,
		arg.Quantity,
		arg.Price,
		arg.CostPrice,
		arg.Status,
		arg.Comment,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
UPDATE orders
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE orders.id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
`

func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
UPDATE order_items
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE order_items.id = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderItem, id)
	return err
}

const deleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
UPDATE order_items
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE order_items.order_id = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderItemsByOrderID, orderID)
	return err
}

const getAllOrderItems = `-- name: GetAllOrderItems :many
SELECT id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
FROM order_items
WHERE order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllOrderItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllOrderItems(ctx context.Context, arg GetAllOrderItemsParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getAllOrderItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.OrderID,
			&i.Quantity,
			&i.Price,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CostPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
FROM orders
WHERE deleted_at = 0
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllOrdersRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) GetAllOrders(ctx context.Context, arg GetAllOrdersParams) ([]GetAllOrdersRow, error) {
	rows, err := q.db.Query(ctx, getAllOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrdersRow
	for rows.Next() {
		var i GetAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.WaiterID,
			&i.CashierID,
			&i.BranchID,
			&i.Status,
			&i.GuestCount,
			&i.TotalAmount,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKitchenQueue = `-- name: GetKitchenQueue :many
SELECT 
    oi.id,
    oi.order_id,
    oi.good_id,
    oi.quantity,
    oi.status,
    oi.comment,
    oi.created_at,
    g.name as dish_name,
    g.cook_time,
    o.table_id,
    ct.number as table_number,
    h.name as hall_name,
    o.guest_count,
    EXTRACT(EPOCH FROM (NOW() - oi.created_at))/60 as wait_time_minutes
FROM order_items oi
LEFT JOIN goods g ON oi.good_id = g.id AND g.deleted_at = 0
LEFT JOIN orders o ON oi.order_id = o.id AND o.deleted_at = 0
LEFT JOIN cafe_tables ct ON o.table_id = ct.id AND ct.deleted_at = 0
LEFT JOIN halls h ON ct.hall_id = h.id AND h.deleted_at = 0
WHERE oi.status IN ('pending', 'cooking') 
  AND oi.deleted_at = 0
  AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
ORDER BY oi.created_at ASC
`

type GetKitchenQueueRow struct {
	ID              uuid.UUID            `json:"id"`
	OrderID         uuid.UUID            `json:"order_id"`
	GoodID          uuid.UUID            `json:"good_id"`
	Quantity        int32                `json:"quantity"`
	Status          NullOrderItemsStatus `json:"status"`
	Comment         *string              `json:"comment"`
	CreatedAt       pgtype.Timestamptz   `json:"created_at"`
	DishName        *string              `json:"dish_name"`
	CookTime        *int32               `json:"cook_time"`
	TableID         pgtype.UUID          `json:"table_id"`
	TableNumber     *int32               `json:"table_number"`
	HallName        *string              `json:"hall_name"`
	GuestCount      *int32               `json:"guest_count"`
	WaitTimeMinutes int32                `json:"wait_time_minutes"`
}

func (q *Queries) GetKitchenQueue(ctx context.Context) ([]GetKitchenQueueRow, error) {
	rows, err := q.db.Query(ctx, getKitchenQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetKitchenQueueRow
	for rows.Next() {
		var i GetKitchenQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.GoodID,
			&i.Quantity,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.DishName,
			&i.CookTime,
			&i.TableID,
			&i.TableNumber,
			&i.HallName,
			&i.GuestCount,
			&i.WaitTimeMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
FROM orders
WHERE orders.id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
`

type GetOrderByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
FROM order_items
WHERE order_items.id = $1
  AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) GetOrderItemByID(ctx context.Context, id uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItemByID, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
FROM order_items
WHERE order_items.order_id = $1
  AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY created_at ASC
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.OrderID,
			&i.Quantity,
			&i.Price,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CostPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemsByStatus = `-- name: GetOrderItemsByStatus :many
SELECT id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
FROM order_items
WHERE order_items.status = $1
  AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type GetOrderItemsByStatusParams struct {
	Status NullOrderItemsStatus `json:"status"`
	Limit  int32                `json:"limit"`
	Offset int32                `json:"offset"`
}

func (q *Queries) GetOrderItemsByStatus(ctx context.Context, arg GetOrderItemsByStatusParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.GoodID,
			&i.OrderID,
			&i.Quantity,
			&i.Price,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CostPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderWithDetails = `-- name: GetOrderWithDetails :one
SELECT 
    o.id,
    o.table_id,
    o.waiter_id,
    o.cashier_id,
    o.status,
    o.guest_count,
    o.total_amount,
    o.comment,
    o.created_at,
    o.updated_at,
    ct.number as table_number,
    ct.capacity as table_capacity,
    h.name as hall_name,
    w.full_name as waiter_name,
    c.full_name as cashier_name,
    COUNT(oi.id) as item_count,
    SUM(oi.quantity) as total_items
FROM orders o
LEFT JOIN cafe_tables ct ON o.table_id = ct.id AND ct.deleted_at = 0
LEFT JOIN halls h ON ct.hall_id = h.id AND h.deleted_at = 0
LEFT JOIN users w ON o.waiter_id = w.id AND w.deleted_at = 0
LEFT JOIN users c ON o.cashier_id = c.id AND c.deleted_at = 0
LEFT JOIN order_items oi ON o.id = oi.order_id AND oi.deleted_at = 0
WHERE o.id = $1
  AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND o.deleted_at = 0
GROUP BY o.id, o.table_id, o.waiter_id, o.cashier_id, o.status, o.guest_count, o.total_amount, o.comment, o.created_at, o.updated_at, ct.number, ct.capacity, h.name, w.full_name, c.full_name
`

type GetOrderWithDetailsRow struct {
	ID            uuid.UUID          `json:"id"`
	TableID       pgtype.UUID        `json:"table_id"`
	WaiterID      pgtype.UUID        `json:"waiter_id"`
	CashierID     pgtype.UUID        `json:"cashier_id"`
	Status        NullOrderStatus    `json:"status"`
	GuestCount    *int32             `json:"guest_count"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	Comment       *string            `json:"comment"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	TableNumber   *int32             `json:"table_number"`
	TableCapacity *int32             `json:"table_capacity"`
	HallName      *string            `json:"hall_name"`
	WaiterName    *string            `json:"waiter_name"`
	CashierName   *string            `json:"cashier_name"`
	ItemCount     int64              `json:"item_count"`
	TotalItems    int64              `json:"total_items"`
}

func (q *Queries) GetOrderWithDetails(ctx context.Context, id uuid.UUID) (GetOrderWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getOrderWithDetails, id)
	var i GetOrderWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableNumber,
		&i.TableCapacity,
		&i.HallName,
		&i.WaiterName,
		&i.CashierName,
		&i.ItemCount,
		&i.TotalItems,
	)
	return i, err
}

const getOrdersByDateRange = `-- name: GetOrdersByDateRange :many
SELECT id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
FROM orders
WHERE created_at >= $1
  AND created_at <= $2
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetOrdersByDateRangeParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

type GetOrdersByDateRangeRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) GetOrdersByDateRange(ctx context.Context, arg GetOrdersByDateRangeParams) ([]GetOrdersByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByDateRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByDateRangeRow
	for rows.Next() {
		var i GetOrdersByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.WaiterID,
			&i.CashierID,
			&i.BranchID,
			&i.Status,
			&i.GuestCount,
			&i.TotalAmount,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByStatus = `-- name: GetOrdersByStatus :many
SELECT id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
FROM orders
WHERE status = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetOrdersByStatusParams struct {
	Status NullOrderStatus `json:"status"`
	Limit  int32           `json:"limit"`
	Offset int32           `json:"offset"`
}

type GetOrdersByStatusRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) GetOrdersByStatus(ctx context.Context, arg GetOrdersByStatusParams) ([]GetOrdersByStatusRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByStatusRow
	for rows.Next() {
		var i GetOrdersByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.WaiterID,
			&i.CashierID,
			&i.BranchID,
			&i.Status,
			&i.GuestCount,
			&i.TotalAmount,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByTableID = `-- name: GetOrdersByTableID :many
SELECT id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
FROM orders
WHERE table_id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
ORDER BY created_at DESC
`

type GetOrdersByTableIDRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) GetOrdersByTableID(ctx context.Context, tableID pgtype.UUID) ([]GetOrdersByTableIDRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByTableID, tableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByTableIDRow
	for rows.Next() {
		var i GetOrdersByTableIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.WaiterID,
			&i.CashierID,
			&i.BranchID,
			&i.Status,
			&i.GuestCount,
			&i.TotalAmount,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByWaiterID = `-- name: GetOrdersByWaiterID :many
SELECT id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
FROM orders
WHERE waiter_id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetOrdersByWaiterIDParams struct {
	WaiterID pgtype.UUID `json:"waiter_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetOrdersByWaiterIDRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) GetOrdersByWaiterID(ctx context.Context, arg GetOrdersByWaiterIDParams) ([]GetOrdersByWaiterIDRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByWaiterID, arg.WaiterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByWaiterIDRow
	for rows.Next() {
		var i GetOrdersByWaiterIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.WaiterID,
			&i.CashierID,
			&i.BranchID,
			&i.Status,
			&i.GuestCount,
			&i.TotalAmount,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderCooking = `-- name: MarkOrderCooking :one
UPDATE orders
SET status = 'cooking',
    updated_at = NOW()
WHERE orders.id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type MarkOrderCookingRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) MarkOrderCooking(ctx context.Context, id uuid.UUID) (MarkOrderCookingRow, error) {
	row := q.db.QueryRow(ctx, markOrderCooking, id)
	var i MarkOrderCookingRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markOrderItemCooking = `-- name: MarkOrderItemCooking :one
UPDATE order_items
SET status = 'cooking',
    updated_at = NOW()
WHERE order_items.id = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
RETURNING id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
`

func (q *Queries) MarkOrderItemCooking(ctx context.Context, id uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRow(ctx, markOrderItemCooking, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
	)
	return i, err
}

const markOrderItemReady = `-- name: MarkOrderItemReady :one
UPDATE order_items
SET status = 'ready',
    updated_at = NOW()
WHERE order_items.id = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
RETURNING id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
`

func (q *Queries) MarkOrderItemReady(ctx context.Context, id uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRow(ctx, markOrderItemReady, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
	)
	return i, err
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE orders
SET status = 'paid',
    cashier_id = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at = 0
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type MarkOrderPaidParams struct {
	ID        uuid.UUID   `json:"id"`
	CashierID pgtype.UUID `json:"cashier_id"`
}

type MarkOrderPaidRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (MarkOrderPaidRow, error) {
	row := q.db.QueryRow(ctx, markOrderPaid, arg.ID, arg.CashierID)
	var i MarkOrderPaidRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markOrderReady = `-- name: MarkOrderReady :one
UPDATE orders
SET status = 'ready',
    updated_at = NOW()
WHERE orders.id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type MarkOrderReadyRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) MarkOrderReady(ctx context.Context, id uuid.UUID) (MarkOrderReadyRow, error) {
	row := q.db.QueryRow(ctx, markOrderReady, id)
	var i MarkOrderReadyRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markOrderServed = `-- name: MarkOrderServed :one
UPDATE orders
SET status = 'served',
    updated_at = NOW()
WHERE id = $1 AND deleted_at = 0
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type MarkOrderServedRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) MarkOrderServed(ctx context.Context, id uuid.UUID) (MarkOrderServedRow, error) {
	row := q.db.QueryRow(ctx, markOrderServed, id)
	var i MarkOrderServedRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreOrder = `-- name: RestoreOrder :exec
UPDATE orders
SET deleted_at = 0
WHERE orders.id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at != 0
`

func (q *Queries) RestoreOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreOrder, id)
	return err
}

const restoreOrderItem = `-- name: RestoreOrderItem :exec
UPDATE order_items
SET deleted_at = 0
WHERE order_items.id = $1 AND order_items.deleted_at != 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
`

func (q *Queries) RestoreOrderItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreOrderItem, id)
	return err
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET table_id = COALESCE($2, table_id),
    waiter_id = COALESCE($3, waiter_id),
    cashier_id = COALESCE($4, cashier_id),
    status = COALESCE($5, status),
    guest_count = COALESCE($6, guest_count),
    total_amount = COALESCE($7, total_amount),
    comment = COALESCE($8, comment),
    updated_at = NOW(),
    branch_id = COALESCE(
        (SELECT h.branch_id FROM cafe_tables ct JOIN halls h ON h.id = ct.hall_id WHERE ct.id = COALESCE($2, table_id)),
        (SELECT s.branch_id FROM users u JOIN shifts s ON s.id = u.shift_id WHERE u.id = COALESCE($3, waiter_id)),
        (SELECT s.branch_id FROM users u JOIN shifts s ON s.id = u.shift_id WHERE u.id = COALESCE($4, cashier_id)),
        branch_id
    )
WHERE orders.id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type UpdateOrderParams struct {
	ID          uuid.UUID       `json:"id"`
	TableID     pgtype.UUID     `json:"table_id"`
	WaiterID    pgtype.UUID     `json:"waiter_id"`
	CashierID   pgtype.UUID     `json:"cashier_id"`
	Status      NullOrderStatus `json:"status"`
	GuestCount  *int32          `json:"guest_count"`
	TotalAmount pgtype.Numeric  `json:"total_amount"`
	Comment     *string         `json:"comment"`
}

type UpdateOrderRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (UpdateOrderRow, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.TableID,
		arg.WaiterID,
		arg.CashierID,
		arg.Status,
		arg.GuestCount,
		arg.TotalAmount,
		arg.Comment,
	)
	var i UpdateOrderRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOrderItem = `-- name: UpdateOrderItem :one
UPDATE order_items
SET good_id = COALESCE($2, good_id),
    order_id = COALESCE($3, order_id),
    quantity = COALESCE($4, quantity),
    price = COALESCE($5, price),
    status = COALESCE($6, status),
    comment = COALESCE($7, comment),
    updated_at = NOW()
WHERE order_items.id = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
RETURNING id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
`

type UpdateOrderItemParams struct {
	ID       uuid.UUID            `json:"id"`
	GoodID   uuid.UUID            `json:"good_id"`
	OrderID  uuid.UUID            `json:"order_id"`
	Quantity int32                `json:"quantity"`
	Price    pgtype.Numeric       `json:"price"`
	Status   NullOrderItemsStatus `json:"status"`
	Comment  *string              `json:"comment"`
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItem,
		arg.ID,
		arg.GoodID,
		arg.OrderID,
		arg.Quantity,
		arg.Price,
		arg.Status,
		arg.Comment,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
	)
	return i, err
}

const updateOrderItemQuantity = `-- name: UpdateOrderItemQuantity :one
UPDATE order_items
SET quantity = $2,
    updated_at = NOW()
WHERE order_items.id = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
RETURNING id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
`

type UpdateOrderItemQuantityParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) UpdateOrderItemQuantity(ctx context.Context, arg UpdateOrderItemQuantityParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItemQuantity, arg.ID, arg.Quantity)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
	)
	return i, err
}

const updateOrderItemStatus = `-- name: UpdateOrderItemStatus :one
UPDATE order_items
SET status = $2,
    updated_at = NOW()
WHERE order_items.id = $1 AND order_items.deleted_at = 0
  AND EXISTS (
    SELECT 1 FROM orders o
    WHERE o.id = order_items.order_id
      AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  )
RETURNING id, good_id, order_id, quantity, price, status, comment, created_at, updated_at, deleted_at, cost_price
`

type UpdateOrderItemStatusParams struct {
	ID     uuid.UUID            `json:"id"`
	Status NullOrderItemsStatus `json:"status"`
}

func (q *Queries) UpdateOrderItemStatus(ctx context.Context, arg UpdateOrderItemStatusParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItemStatus, arg.ID, arg.Status)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.GoodID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
    updated_at = NOW()
WHERE orders.id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
RETURNING id, table_id, waiter_id, cashier_id, branch_id, status, guest_count, total_amount, comment, created_at, updated_at, deleted_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID       `json:"id"`
	Status NullOrderStatus `json:"status"`
}

type UpdateOrderStatusRow struct {
	ID          uuid.UUID          `json:"id"`
	TableID     pgtype.UUID        `json:"table_id"`
	WaiterID    pgtype.UUID        `json:"waiter_id"`
	CashierID   pgtype.UUID        `json:"cashier_id"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	Status      NullOrderStatus    `json:"status"`
	GuestCount  *int32             `json:"guest_count"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (UpdateOrderStatusRow, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i UpdateOrderStatusRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WaiterID,
		&i.CashierID,
		&i.BranchID,
		&i.Status,
		&i.GuestCount,
		&i.TotalAmount,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
