// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: printer_settings.sql

package pg

import (
	"context"

	"github.com/google/uuid"
)

const createPrinterSetting = `-- name: CreatePrinterSetting :one
INSERT INTO printer_settings (
  ip,
  port,
  type,
  connected_entity_ids
)
VALUES (
  $1,
  $2,
  $3,
  ARRAY(
    SELECT x::uuid
    FROM unnest($4::text[]) AS x
  )
)
RETURNING
  id,
  ip,
  port,
  type,
  connected_entity_ids,
  created_at,
  updated_at,
  deleted_at
`

type CreatePrinterSettingParams struct {
	Ip                 string   `json:"ip"`
	Port               int32    `json:"port"`
	Type               string   `json:"type"`
	ConnectedEntityIds []string `json:"connected_entity_ids"`
}

func (q *Queries) CreatePrinterSetting(ctx context.Context, arg CreatePrinterSettingParams) (PrinterSetting, error) {
	row := q.db.QueryRow(ctx, createPrinterSetting,
		arg.Ip,
		arg.Port,
		arg.Type,
		arg.ConnectedEntityIds,
	)
	var i PrinterSetting
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.Port,
		&i.Type,
		&i.ConnectedEntityIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPrinterSettingByID = `-- name: GetPrinterSettingByID :one
SELECT
  id,
  ip,
  port,
  type,
  connected_entity_ids,
  created_at,
  updated_at,
  deleted_at
FROM printer_settings
WHERE id = $1
  AND deleted_at = 0
LIMIT 1
`

func (q *Queries) GetPrinterSettingByID(ctx context.Context, id uuid.UUID) (PrinterSetting, error) {
	row := q.db.QueryRow(ctx, getPrinterSettingByID, id)
	var i PrinterSetting
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.Port,
		&i.Type,
		&i.ConnectedEntityIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPrinterSettings = `-- name: ListPrinterSettings :many
SELECT
  id,
  ip,
  port,
  type,
  connected_entity_ids,
  created_at,
  updated_at,
  deleted_at
FROM printer_settings
WHERE deleted_at = 0
ORDER BY created_at DESC
`

func (q *Queries) ListPrinterSettings(ctx context.Context) ([]PrinterSetting, error) {
	rows, err := q.db.Query(ctx, listPrinterSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrinterSetting
	for rows.Next() {
		var i PrinterSetting
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.Port,
			&i.Type,
			&i.ConnectedEntityIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrinterSetting = `-- name: UpdatePrinterSetting :one
UPDATE printer_settings
SET
  ip = $1,
  port = $2,
  type = $3,
  connected_entity_ids = ARRAY(
    SELECT x::uuid
    FROM unnest($4::text[]) AS x
  ),
  updated_at = NOW()
WHERE id = $5
  AND deleted_at = 0
RETURNING
  id,
  ip,
  port,
  type,
  connected_entity_ids,
  created_at,
  updated_at,
  deleted_at
`

type UpdatePrinterSettingParams struct {
	Ip                 string    `json:"ip"`
	Port               int32     `json:"port"`
	Type               string    `json:"type"`
	ConnectedEntityIds []string  `json:"connected_entity_ids"`
	ID                 uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePrinterSetting(ctx context.Context, arg UpdatePrinterSettingParams) (PrinterSetting, error) {
	row := q.db.QueryRow(ctx, updatePrinterSetting,
		arg.Ip,
		arg.Port,
		arg.Type,
		arg.ConnectedEntityIds,
		arg.ID,
	)
	var i PrinterSetting
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.Port,
		&i.Type,
		&i.ConnectedEntityIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
