// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: printer_settings.sql

package pg

import (
	"context"
)

const getPrinterSettings = `-- name: GetPrinterSettings :one
SELECT id, cashier_printer_ip, kitchen_printer_ip, printer_port, created_at, updated_at
FROM printer_settings
WHERE id = 1
LIMIT 1
`

func (q *Queries) GetPrinterSettings(ctx context.Context) (PrinterSetting, error) {
	row := q.db.QueryRow(ctx, getPrinterSettings)
	var i PrinterSetting
	err := row.Scan(
		&i.ID,
		&i.CashierPrinterIp,
		&i.KitchenPrinterIp,
		&i.PrinterPort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPrinterSettings = `-- name: UpsertPrinterSettings :exec
INSERT INTO printer_settings (id, cashier_printer_ip, kitchen_printer_ip, printer_port)
VALUES (1, $1, $2, $3)
ON CONFLICT (id)
DO UPDATE SET
  cashier_printer_ip = EXCLUDED.cashier_printer_ip,
  kitchen_printer_ip = EXCLUDED.kitchen_printer_ip,
  printer_port = EXCLUDED.printer_port,
  updated_at = NOW()
`

type UpsertPrinterSettingsParams struct {
	CashierPrinterIp string `json:"cashier_printer_ip"`
	KitchenPrinterIp string `json:"kitchen_printer_ip"`
	PrinterPort      int32  `json:"printer_port"`
}

func (q *Queries) UpsertPrinterSettings(ctx context.Context, arg UpsertPrinterSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertPrinterSettings, arg.CashierPrinterIp, arg.KitchenPrinterIp, arg.PrinterPort)
	return err
}
