// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const goodsReport = `-- name: GoodsReport :many
SELECT
  g.id::text                                                               AS good_id,
  g.name                                                                   AS name,
  COALESCE(SUM(oi.quantity), 0)::bigint                                    AS total_qty,
  COALESCE(AVG(oi.price), 0)::numeric                                      AS avg_sell_price,
  COALESCE(SUM(oi.quantity::numeric * oi.price), 0)                        AS total_sell,
  COALESCE(AVG(oi.cost_price), 0)::numeric                                 AS avg_cost_price,
  COALESCE(SUM(oi.quantity::numeric * oi.cost_price), 0)                   AS total_cost,
  COALESCE(AVG(oi.price - oi.cost_price), 0)::numeric                     AS avg_markup,
  COALESCE(SUM(oi.quantity::numeric * (oi.price - oi.cost_price)), 0)      AS total_markup,
  CASE
    WHEN COALESCE(AVG(oi.cost_price), 0) = 0 THEN 0
    ELSE (AVG(oi.price - oi.cost_price) / AVG(oi.cost_price)) * 100
  END::numeric                                                             AS avg_markup_pct
FROM order_items oi
JOIN orders o           ON o.id  = oi.order_id   AND o.deleted_at = 0 AND o.bill_status = 'paid'
JOIN goods g            ON g.id  = oi.good_id    AND g.deleted_at = 0
LEFT JOIN categories c  ON c.id  = g.category_id AND c.deleted_at = 0
LEFT JOIN cafe_tables ct ON ct.id = o.table_id
WHERE oi.deleted_at = 0
  AND o.created_at >= $1
  AND o.created_at <  $2
  AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND (NULLIF($3::text, '') IS NULL OR c.department_id = NULLIF($3::text, '')::uuid)
  AND (NULLIF($4::text, '') IS NULL OR g.category_id   = NULLIF($4::text, '')::uuid)
  AND (NULLIF($5::text, '') IS NULL OR g.id             = NULLIF($5::text, '')::uuid)
  AND (NULLIF($6::text, '') IS NULL OR o.waiter_id      = NULLIF($6::text, '')::uuid)
  AND (NULLIF($7::text, '') IS NULL OR ct.hall_id        = NULLIF($7::text, '')::uuid)
  AND (NULLIF($8::text, '') IS NULL OR o.table_id        = NULLIF($8::text, '')::uuid)
GROUP BY g.id, g.name
ORDER BY g.name
LIMIT  $9
OFFSET $10
`

type GoodsReportParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Column3     string             `json:"column_3"`
	Column4     string             `json:"column_4"`
	Column5     string             `json:"column_5"`
	Column6     string             `json:"column_6"`
	Column7     string             `json:"column_7"`
	Column8     string             `json:"column_8"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

type GoodsReportRow struct {
	GoodID       string         `json:"good_id"`
	Name         string         `json:"name"`
	TotalQty     int64          `json:"total_qty"`
	AvgSellPrice pgtype.Numeric `json:"avg_sell_price"`
	TotalSell    interface{}    `json:"total_sell"`
	AvgCostPrice pgtype.Numeric `json:"avg_cost_price"`
	TotalCost    interface{}    `json:"total_cost"`
	AvgMarkup    pgtype.Numeric `json:"avg_markup"`
	TotalMarkup  interface{}    `json:"total_markup"`
	AvgMarkupPct pgtype.Numeric `json:"avg_markup_pct"`
}

func (q *Queries) GoodsReport(ctx context.Context, arg GoodsReportParams) ([]GoodsReportRow, error) {
	rows, err := q.db.Query(ctx, goodsReport,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsReportRow
	for rows.Next() {
		var i GoodsReportRow
		if err := rows.Scan(
			&i.GoodID,
			&i.Name,
			&i.TotalQty,
			&i.AvgSellPrice,
			&i.TotalSell,
			&i.AvgCostPrice,
			&i.TotalCost,
			&i.AvgMarkup,
			&i.TotalMarkup,
			&i.AvgMarkupPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const goodsReportTotals = `-- name: GoodsReportTotals :one
SELECT
  COALESCE(SUM(oi.quantity), 0)::bigint                                          AS total_qty,
  COALESCE(SUM(oi.quantity::numeric * oi.price), 0)                              AS total_sell,
  COALESCE(SUM(oi.quantity::numeric * oi.cost_price), 0)                         AS total_cost,
  COALESCE(SUM(oi.quantity::numeric * (oi.price - oi.cost_price)), 0)            AS total_markup,
  CASE
    WHEN COALESCE(SUM(oi.quantity::numeric * oi.cost_price), 0) = 0 THEN 0
    ELSE SUM(oi.quantity::numeric * (oi.price - oi.cost_price))
       / SUM(oi.quantity::numeric * oi.cost_price) * 100
  END::numeric                                                                   AS avg_markup_pct,
  COUNT(DISTINCT g.id)::bigint                                                   AS total_count
FROM order_items oi
JOIN orders o           ON o.id  = oi.order_id   AND o.deleted_at = 0 AND o.bill_status = 'paid'
JOIN goods g            ON g.id  = oi.good_id    AND g.deleted_at = 0
LEFT JOIN categories c  ON c.id  = g.category_id AND c.deleted_at = 0
LEFT JOIN cafe_tables ct ON ct.id = o.table_id
WHERE oi.deleted_at = 0
  AND o.created_at >= $1
  AND o.created_at <  $2
  AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND (NULLIF($3::text, '') IS NULL OR c.department_id = NULLIF($3::text, '')::uuid)
  AND (NULLIF($4::text, '') IS NULL OR g.category_id   = NULLIF($4::text, '')::uuid)
  AND (NULLIF($5::text, '') IS NULL OR g.id             = NULLIF($5::text, '')::uuid)
  AND (NULLIF($6::text, '') IS NULL OR o.waiter_id      = NULLIF($6::text, '')::uuid)
  AND (NULLIF($7::text, '') IS NULL OR ct.hall_id        = NULLIF($7::text, '')::uuid)
  AND (NULLIF($8::text, '') IS NULL OR o.table_id        = NULLIF($8::text, '')::uuid)
`

type GoodsReportTotalsParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Column3     string             `json:"column_3"`
	Column4     string             `json:"column_4"`
	Column5     string             `json:"column_5"`
	Column6     string             `json:"column_6"`
	Column7     string             `json:"column_7"`
	Column8     string             `json:"column_8"`
}

type GoodsReportTotalsRow struct {
	TotalQty     int64          `json:"total_qty"`
	TotalSell    interface{}    `json:"total_sell"`
	TotalCost    interface{}    `json:"total_cost"`
	TotalMarkup  interface{}    `json:"total_markup"`
	AvgMarkupPct pgtype.Numeric `json:"avg_markup_pct"`
	TotalCount   int64          `json:"total_count"`
}

func (q *Queries) GoodsReportTotals(ctx context.Context, arg GoodsReportTotalsParams) (GoodsReportTotalsRow, error) {
	row := q.db.QueryRow(ctx, goodsReportTotals,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var i GoodsReportTotalsRow
	err := row.Scan(
		&i.TotalQty,
		&i.TotalSell,
		&i.TotalCost,
		&i.TotalMarkup,
		&i.AvgMarkupPct,
		&i.TotalCount,
	)
	return i, err
}
