// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package pg

import (
	"context"

	"github.com/google/uuid"
)

const countSuppliers = `-- name: CountSuppliers :one
SELECT COUNT(*)
FROM suppliers
WHERE branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
`

func (q *Queries) CountSuppliers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupplier = `-- name: CreateSupplier :one

INSERT INTO suppliers (id, name, phone_number, location, branch_id)
VALUES ($1, $2, $3, $4, NULLIF(current_setting('app.branch_id', true), '')::uuid)
RETURNING id, name, phone_number, location, branch_id, created_at, updated_at, deleted_at
`

type CreateSupplierParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	PhoneNumber *string   `json:"phone_number"`
	Location    *string   `json:"location"`
}

// ==================== SUPPLIERS QUERIES ====================
func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.ID,
		arg.Name,
		arg.PhoneNumber,
		arg.Location,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Location,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
UPDATE suppliers
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

func (q *Queries) DeleteSupplier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSupplier, id)
	return err
}

const getAllSuppliers = `-- name: GetAllSuppliers :many
SELECT id, name, phone_number, location, branch_id, created_at, updated_at, deleted_at
FROM suppliers
WHERE branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type GetAllSuppliersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllSuppliers(ctx context.Context, arg GetAllSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, getAllSuppliers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.Location,
			&i.BranchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, name, phone_number, location, branch_id, created_at, updated_at, deleted_at
FROM suppliers
WHERE id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
`

func (q *Queries) GetSupplierByID(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Location,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSuppliersByPhoneNumber = `-- name: GetSuppliersByPhoneNumber :many
SELECT id, name, phone_number, location, branch_id, created_at, updated_at, deleted_at
FROM suppliers
WHERE phone_number = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
`

func (q *Queries) GetSuppliersByPhoneNumber(ctx context.Context, phoneNumber *string) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, getSuppliersByPhoneNumber, phoneNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.Location,
			&i.BranchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreSupplier = `-- name: RestoreSupplier :one
UPDATE suppliers
SET deleted_at = 0,
    updated_at = NOW()
WHERE id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
RETURNING id, name, phone_number, location, branch_id, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreSupplier(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, restoreSupplier, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Location,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const searchSuppliers = `-- name: SearchSuppliers :many
SELECT id, name, phone_number, location, branch_id, created_at, updated_at, deleted_at
FROM suppliers
WHERE name ILIKE $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  AND deleted_at = 0
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type SearchSuppliersParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchSuppliers(ctx context.Context, arg SearchSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, searchSuppliers, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.Location,
			&i.BranchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET name = $2,
    phone_number = $3,
    location = $4,
    updated_at = NOW()
WHERE id = $1
  AND branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
RETURNING id, name, phone_number, location, branch_id, created_at, updated_at, deleted_at
`

type UpdateSupplierParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	PhoneNumber *string   `json:"phone_number"`
	Location    *string   `json:"location"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.ID,
		arg.Name,
		arg.PhoneNumber,
		arg.Location,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Location,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
