// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeAttendance = `-- name: CloseAttendance :one
UPDATE attendances SET
    close_date = $2,
    difference = $3,
    working_hours = $4
WHERE id = $1 AND deleted_at = 0
RETURNING id, user_id, open_date, close_date, difference, working_hours, created_at, updated_at, deleted_at
`

type CloseAttendanceParams struct {
	ID           uuid.UUID   `json:"id"`
	CloseDate    pgtype.Date `json:"close_date"`
	Difference   *int32      `json:"difference"`
	WorkingHours *int32      `json:"working_hours"`
}

func (q *Queries) CloseAttendance(ctx context.Context, arg CloseAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, closeAttendance,
		arg.ID,
		arg.CloseDate,
		arg.Difference,
		arg.WorkingHours,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpenDate,
		&i.CloseDate,
		&i.Difference,
		&i.WorkingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users 
WHERE deleted_at = 0
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users 
WHERE role = $1 AND deleted_at = 0
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByShift = `-- name: CountUsersByShift :one
SELECT COUNT(*) FROM users 
WHERE shift_id = $1 AND deleted_at = 0
`

func (q *Queries) CountUsersByShift(ctx context.Context, shiftID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByShift, shiftID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttendance = `-- name: CreateAttendance :one
INSERT INTO attendances (
    id,
    user_id,
    open_date,
    close_date,
    difference,
    working_hours
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, open_date, close_date, difference, working_hours, created_at, updated_at, deleted_at
`

type CreateAttendanceParams struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	OpenDate     pgtype.Date `json:"open_date"`
	CloseDate    pgtype.Date `json:"close_date"`
	Difference   *int32      `json:"difference"`
	WorkingHours *int32      `json:"working_hours"`
}

func (q *Queries) CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, createAttendance,
		arg.ID,
		arg.UserID,
		arg.OpenDate,
		arg.CloseDate,
		arg.Difference,
		arg.WorkingHours,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpenDate,
		&i.CloseDate,
		&i.Difference,
		&i.WorkingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (
    id,
    name,
    role,
    working_days,
    open_time,
    close_time,
    branch_id
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, role, working_days, open_time, close_time, branch_id, is_active, created_at, updated_at, deleted_at
`

type CreateShiftParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Role        *string     `json:"role"`
	WorkingDays *string     `json:"working_days"`
	OpenTime    *int64      `json:"open_time"`
	CloseTime   *int64      `json:"close_time"`
	BranchID    pgtype.UUID `json:"branch_id"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, createShift,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.WorkingDays,
		arg.OpenTime,
		arg.CloseTime,
		arg.BranchID,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.WorkingDays,
		&i.OpenTime,
		&i.CloseTime,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    full_name,
    username,
    role,
    email,
    shift_id,
    pincode,
    hash_password,
    brand_id,
    phone_number,
    is_active
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	FullName     *string     `json:"full_name"`
	Username     *string     `json:"username"`
	Role         string      `json:"role"`
	Email        *string     `json:"email"`
	ShiftID      pgtype.UUID `json:"shift_id"`
	Pincode      *string     `json:"pincode"`
	HashPassword *string     `json:"hash_password"`
	BrandID      pgtype.UUID `json:"brand_id"`
	PhoneNumber  *string     `json:"phone_number"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Username,
		arg.Role,
		arg.Email,
		arg.ShiftID,
		arg.Pincode,
		arg.HashPassword,
		arg.BrandID,
		arg.PhoneNumber,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllShifts = `-- name: GetAllShifts :many
SELECT id, name, role, working_days, open_time, close_time, branch_id, is_active, created_at, updated_at, deleted_at FROM shifts 
WHERE deleted_at = 0
ORDER BY name ASC
`

func (q *Queries) GetAllShifts(ctx context.Context) ([]Shift, error) {
	rows, err := q.db.Query(ctx, getAllShifts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shift
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.WorkingDays,
			&i.OpenTime,
			&i.CloseTime,
			&i.BranchID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE deleted_at = 0
ORDER BY created_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.ShiftID,
			&i.Pincode,
			&i.HashPassword,
			&i.BrandID,
			&i.PhoneNumber,
			&i.FcmToken,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersPaginated = `-- name: GetAllUsersPaginated :many
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE deleted_at = 0
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllUsersPaginated(ctx context.Context, arg GetAllUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.ShiftID,
			&i.Pincode,
			&i.HashPassword,
			&i.BrandID,
			&i.PhoneNumber,
			&i.FcmToken,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceByID = `-- name: GetAttendanceByID :one
SELECT id, user_id, open_date, close_date, difference, working_hours, created_at, updated_at, deleted_at FROM attendances 
WHERE id = $1 AND deleted_at = 0
`

func (q *Queries) GetAttendanceByID(ctx context.Context, id uuid.UUID) (Attendance, error) {
	row := q.db.QueryRow(ctx, getAttendanceByID, id)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpenDate,
		&i.CloseDate,
		&i.Difference,
		&i.WorkingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAttendanceStatsByRole = `-- name: GetAttendanceStatsByRole :many
SELECT 
    u.role,
    COUNT(a.id) as total_attendances,
    SUM(a.working_hours) as total_hours,
    AVG(a.working_hours) as avg_hours_per_day,
    COUNT(DISTINCT a.user_id) as unique_users
FROM attendances a
JOIN users u ON a.user_id = u.id AND u.deleted_at = 0
WHERE a.open_date >= $1 
AND a.open_date <= $2 
AND a.deleted_at = 0
GROUP BY u.role
ORDER BY total_hours DESC
`

type GetAttendanceStatsByRoleParams struct {
	OpenDate   pgtype.Date `json:"open_date"`
	OpenDate_2 pgtype.Date `json:"open_date_2"`
}

type GetAttendanceStatsByRoleRow struct {
	Role             string  `json:"role"`
	TotalAttendances int64   `json:"total_attendances"`
	TotalHours       int64   `json:"total_hours"`
	AvgHoursPerDay   float64 `json:"avg_hours_per_day"`
	UniqueUsers      int64   `json:"unique_users"`
}

func (q *Queries) GetAttendanceStatsByRole(ctx context.Context, arg GetAttendanceStatsByRoleParams) ([]GetAttendanceStatsByRoleRow, error) {
	rows, err := q.db.Query(ctx, getAttendanceStatsByRole, arg.OpenDate, arg.OpenDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceStatsByRoleRow
	for rows.Next() {
		var i GetAttendanceStatsByRoleRow
		if err := rows.Scan(
			&i.Role,
			&i.TotalAttendances,
			&i.TotalHours,
			&i.AvgHoursPerDay,
			&i.UniqueUsers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendancesByDateRange = `-- name: GetAttendancesByDateRange :many
SELECT a.id, a.user_id, a.open_date, a.close_date, a.difference, a.working_hours, a.created_at, a.updated_at, a.deleted_at, u.full_name, u.username, u.role
FROM attendances a
JOIN users u ON a.user_id = u.id AND u.deleted_at = 0
WHERE a.open_date >= $1 
AND a.open_date <= $2 
AND a.deleted_at = 0
ORDER BY a.open_date DESC
`

type GetAttendancesByDateRangeParams struct {
	OpenDate   pgtype.Date `json:"open_date"`
	OpenDate_2 pgtype.Date `json:"open_date_2"`
}

type GetAttendancesByDateRangeRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	OpenDate     pgtype.Date        `json:"open_date"`
	CloseDate    pgtype.Date        `json:"close_date"`
	Difference   *int32             `json:"difference"`
	WorkingHours *int32             `json:"working_hours"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
	FullName     *string            `json:"full_name"`
	Username     *string            `json:"username"`
	Role         string             `json:"role"`
}

func (q *Queries) GetAttendancesByDateRange(ctx context.Context, arg GetAttendancesByDateRangeParams) ([]GetAttendancesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getAttendancesByDateRange, arg.OpenDate, arg.OpenDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendancesByDateRangeRow
	for rows.Next() {
		var i GetAttendancesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpenDate,
			&i.CloseDate,
			&i.Difference,
			&i.WorkingHours,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FullName,
			&i.Username,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendancesByUserID = `-- name: GetAttendancesByUserID :many
SELECT id, user_id, open_date, close_date, difference, working_hours, created_at, updated_at, deleted_at FROM attendances 
WHERE user_id = $1 AND deleted_at = 0
ORDER BY open_date DESC
`

func (q *Queries) GetAttendancesByUserID(ctx context.Context, userID uuid.UUID) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, getAttendancesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpenDate,
			&i.CloseDate,
			&i.Difference,
			&i.WorkingHours,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendancesByUserIDPaginated = `-- name: GetAttendancesByUserIDPaginated :many
SELECT id, user_id, open_date, close_date, difference, working_hours, created_at, updated_at, deleted_at FROM attendances 
WHERE user_id = $1 AND deleted_at = 0
ORDER BY open_date DESC
LIMIT $2 OFFSET $3
`

type GetAttendancesByUserIDPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetAttendancesByUserIDPaginated(ctx context.Context, arg GetAttendancesByUserIDPaginatedParams) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, getAttendancesByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpenDate,
			&i.CloseDate,
			&i.Difference,
			&i.WorkingHours,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendancesForToday = `-- name: GetAttendancesForToday :many
SELECT a.id, a.user_id, a.open_date, a.close_date, a.difference, a.working_hours, a.created_at, a.updated_at, a.deleted_at, u.full_name, u.username, u.role
FROM attendances a
JOIN users u ON a.user_id = u.id AND u.deleted_at = 0
WHERE a.open_date = CURRENT_DATE 
AND a.deleted_at = 0
ORDER BY a.open_date DESC
`

type GetAttendancesForTodayRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	OpenDate     pgtype.Date        `json:"open_date"`
	CloseDate    pgtype.Date        `json:"close_date"`
	Difference   *int32             `json:"difference"`
	WorkingHours *int32             `json:"working_hours"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    *int64             `json:"deleted_at"`
	FullName     *string            `json:"full_name"`
	Username     *string            `json:"username"`
	Role         string             `json:"role"`
}

func (q *Queries) GetAttendancesForToday(ctx context.Context) ([]GetAttendancesForTodayRow, error) {
	rows, err := q.db.Query(ctx, getAttendancesForToday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendancesForTodayRow
	for rows.Next() {
		var i GetAttendancesForTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpenDate,
			&i.CloseDate,
			&i.Difference,
			&i.WorkingHours,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FullName,
			&i.Username,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyAttendanceSummary = `-- name: GetDailyAttendanceSummary :many
SELECT 
    a.open_date,
    COUNT(a.id) as total_attendances,
    SUM(a.working_hours) as total_hours,
    AVG(a.working_hours) as avg_hours,
    COUNT(DISTINCT a.user_id) as unique_users
FROM attendances a
WHERE a.open_date >= $1 
AND a.open_date <= $2 
AND a.deleted_at = 0
GROUP BY a.open_date
ORDER BY a.open_date DESC
`

type GetDailyAttendanceSummaryParams struct {
	OpenDate   pgtype.Date `json:"open_date"`
	OpenDate_2 pgtype.Date `json:"open_date_2"`
}

type GetDailyAttendanceSummaryRow struct {
	OpenDate         pgtype.Date `json:"open_date"`
	TotalAttendances int64       `json:"total_attendances"`
	TotalHours       int64       `json:"total_hours"`
	AvgHours         float64     `json:"avg_hours"`
	UniqueUsers      int64       `json:"unique_users"`
}

func (q *Queries) GetDailyAttendanceSummary(ctx context.Context, arg GetDailyAttendanceSummaryParams) ([]GetDailyAttendanceSummaryRow, error) {
	rows, err := q.db.Query(ctx, getDailyAttendanceSummary, arg.OpenDate, arg.OpenDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyAttendanceSummaryRow
	for rows.Next() {
		var i GetDailyAttendanceSummaryRow
		if err := rows.Scan(
			&i.OpenDate,
			&i.TotalAttendances,
			&i.TotalHours,
			&i.AvgHours,
			&i.UniqueUsers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenAttendancesByUserID = `-- name: GetOpenAttendancesByUserID :one
SELECT id, user_id, open_date, close_date, difference, working_hours, created_at, updated_at, deleted_at FROM attendances 
WHERE user_id = $1 
AND close_date IS NULL 
AND deleted_at = 0
ORDER BY open_date DESC
LIMIT 1
`

func (q *Queries) GetOpenAttendancesByUserID(ctx context.Context, userID uuid.UUID) (Attendance, error) {
	row := q.db.QueryRow(ctx, getOpenAttendancesByUserID, userID)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpenDate,
		&i.CloseDate,
		&i.Difference,
		&i.WorkingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShiftByID = `-- name: GetShiftByID :one
SELECT id, name, role, working_days, open_time, close_time, branch_id, is_active, created_at, updated_at, deleted_at FROM shifts 
WHERE id = $1 AND deleted_at = 0
`

func (q *Queries) GetShiftByID(ctx context.Context, id uuid.UUID) (Shift, error) {
	row := q.db.QueryRow(ctx, getShiftByID, id)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.WorkingDays,
		&i.OpenTime,
		&i.CloseTime,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShiftWithUsers = `-- name: GetShiftWithUsers :one
SELECT 
    s.id, s.name, s.role, s.working_days, s.open_time, s.close_time, s.branch_id, s.is_active, s.created_at, s.updated_at, s.deleted_at,
    COUNT(u.id) as user_count
FROM shifts s
LEFT JOIN users u ON s.id = u.shift_id AND u.deleted_at = 0
WHERE s.id = $1 AND s.deleted_at = 0
GROUP BY s.id
`

type GetShiftWithUsersRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Role        *string            `json:"role"`
	WorkingDays *string            `json:"working_days"`
	OpenTime    *int64             `json:"open_time"`
	CloseTime   *int64             `json:"close_time"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
	UserCount   int64              `json:"user_count"`
}

func (q *Queries) GetShiftWithUsers(ctx context.Context, id uuid.UUID) (GetShiftWithUsersRow, error) {
	row := q.db.QueryRow(ctx, getShiftWithUsers, id)
	var i GetShiftWithUsersRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.WorkingDays,
		&i.OpenTime,
		&i.CloseTime,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserCount,
	)
	return i, err
}

const getShiftsByBranchID = `-- name: GetShiftsByBranchID :many
SELECT id, name, role, working_days, open_time, close_time, branch_id, is_active, created_at, updated_at, deleted_at FROM shifts 
WHERE branch_id = $1 AND deleted_at = 0
ORDER BY name ASC
`

func (q *Queries) GetShiftsByBranchID(ctx context.Context, branchID pgtype.UUID) ([]Shift, error) {
	rows, err := q.db.Query(ctx, getShiftsByBranchID, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shift
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.WorkingDays,
			&i.OpenTime,
			&i.CloseTime,
			&i.BranchID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShiftsByRole = `-- name: GetShiftsByRole :many
SELECT id, name, role, working_days, open_time, close_time, branch_id, is_active, created_at, updated_at, deleted_at FROM shifts 
WHERE role = $1 AND deleted_at = 0
ORDER BY name ASC
`

func (q *Queries) GetShiftsByRole(ctx context.Context, role *string) ([]Shift, error) {
	rows, err := q.db.Query(ctx, getShiftsByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shift
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.WorkingDays,
			&i.OpenTime,
			&i.CloseTime,
			&i.BranchID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShiftsWithUserCounts = `-- name: GetShiftsWithUserCounts :many
SELECT 
    s.id, s.name, s.role, s.working_days, s.open_time, s.close_time, s.branch_id, s.is_active, s.created_at, s.updated_at, s.deleted_at,
    COUNT(u.id) as user_count
FROM shifts s
LEFT JOIN users u ON s.id = u.shift_id AND u.deleted_at = 0
WHERE s.deleted_at = 0
GROUP BY s.id
ORDER BY s.name ASC
`

type GetShiftsWithUserCountsRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Role        *string            `json:"role"`
	WorkingDays *string            `json:"working_days"`
	OpenTime    *int64             `json:"open_time"`
	CloseTime   *int64             `json:"close_time"`
	BranchID    pgtype.UUID        `json:"branch_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   *int64             `json:"deleted_at"`
	UserCount   int64              `json:"user_count"`
}

func (q *Queries) GetShiftsWithUserCounts(ctx context.Context) ([]GetShiftsWithUserCountsRow, error) {
	rows, err := q.db.Query(ctx, getShiftsWithUserCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShiftsWithUserCountsRow
	for rows.Next() {
		var i GetShiftsWithUserCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.WorkingDays,
			&i.OpenTime,
			&i.CloseTime,
			&i.BranchID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAttendanceStats = `-- name: GetUserAttendanceStats :one
SELECT 
    user_id,
    COUNT(*) as total_days,
    SUM(working_hours) as total_hours,
    AVG(working_hours) as avg_hours_per_day,
    MIN(open_date) as first_attendance,
    MAX(open_date) as last_attendance
FROM attendances
WHERE user_id = $1 AND deleted_at = 0
GROUP BY user_id
`

type GetUserAttendanceStatsRow struct {
	UserID          uuid.UUID   `json:"user_id"`
	TotalDays       int64       `json:"total_days"`
	TotalHours      int64       `json:"total_hours"`
	AvgHoursPerDay  float64     `json:"avg_hours_per_day"`
	FirstAttendance interface{} `json:"first_attendance"`
	LastAttendance  interface{} `json:"last_attendance"`
}

func (q *Queries) GetUserAttendanceStats(ctx context.Context, userID uuid.UUID) (GetUserAttendanceStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserAttendanceStats, userID)
	var i GetUserAttendanceStatsRow
	err := row.Scan(
		&i.UserID,
		&i.TotalDays,
		&i.TotalHours,
		&i.AvgHoursPerDay,
		&i.FirstAttendance,
		&i.LastAttendance,
	)
	return i, err
}

const getUserAttendanceStatsByDateRange = `-- name: GetUserAttendanceStatsByDateRange :one
SELECT 
    user_id,
    COUNT(*) as total_days,
    SUM(working_hours) as total_hours,
    AVG(working_hours) as avg_hours_per_day,
    MIN(open_date) as first_attendance,
    MAX(open_date) as last_attendance
FROM attendances
WHERE user_id = $1 
AND open_date >= $2 
AND open_date <= $3 
AND deleted_at = 0
GROUP BY user_id
`

type GetUserAttendanceStatsByDateRangeParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	OpenDate   pgtype.Date `json:"open_date"`
	OpenDate_2 pgtype.Date `json:"open_date_2"`
}

type GetUserAttendanceStatsByDateRangeRow struct {
	UserID          uuid.UUID   `json:"user_id"`
	TotalDays       int64       `json:"total_days"`
	TotalHours      int64       `json:"total_hours"`
	AvgHoursPerDay  float64     `json:"avg_hours_per_day"`
	FirstAttendance interface{} `json:"first_attendance"`
	LastAttendance  interface{} `json:"last_attendance"`
}

func (q *Queries) GetUserAttendanceStatsByDateRange(ctx context.Context, arg GetUserAttendanceStatsByDateRangeParams) (GetUserAttendanceStatsByDateRangeRow, error) {
	row := q.db.QueryRow(ctx, getUserAttendanceStatsByDateRange, arg.UserID, arg.OpenDate, arg.OpenDate_2)
	var i GetUserAttendanceStatsByDateRangeRow
	err := row.Scan(
		&i.UserID,
		&i.TotalDays,
		&i.TotalHours,
		&i.AvgHoursPerDay,
		&i.FirstAttendance,
		&i.LastAttendance,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE email = $1 AND deleted_at = 0
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE id = $1 AND deleted_at = 0
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE phone_number = $1 AND deleted_at = 0
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPincode = `-- name: GetUserByPincode :one
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE pincode = $1 AND deleted_at = 0
`

func (q *Queries) GetUserByPincode(ctx context.Context, pincode *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPincode, pincode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE username = $1 AND deleted_at = 0
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserWithAttendanceStats = `-- name: GetUserWithAttendanceStats :one
SELECT 
    u.id, u.full_name, u.username, u.role, u.email, u.shift_id, u.pincode, u.hash_password, u.brand_id, u.phone_number, u.fcm_token, u.is_active, u.created_at, u.updated_at, u.deleted_at,
    COUNT(a.id) as total_attendances,
    SUM(a.working_hours) as total_hours_worked,
    AVG(a.working_hours) as avg_hours_per_day,
    MAX(a.open_date) as last_attendance_date
FROM users u
LEFT JOIN attendances a ON u.id = a.user_id AND a.deleted_at = 0
WHERE u.id = $1 AND u.deleted_at = 0
GROUP BY u.id
`

type GetUserWithAttendanceStatsRow struct {
	ID                 uuid.UUID          `json:"id"`
	FullName           *string            `json:"full_name"`
	Username           *string            `json:"username"`
	Role               string             `json:"role"`
	Email              *string            `json:"email"`
	ShiftID            pgtype.UUID        `json:"shift_id"`
	Pincode            *string            `json:"pincode"`
	HashPassword       *string            `json:"hash_password"`
	BrandID            pgtype.UUID        `json:"brand_id"`
	PhoneNumber        *string            `json:"phone_number"`
	FcmToken           *string            `json:"fcm_token"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          *int64             `json:"deleted_at"`
	TotalAttendances   int64              `json:"total_attendances"`
	TotalHoursWorked   int64              `json:"total_hours_worked"`
	AvgHoursPerDay     float64            `json:"avg_hours_per_day"`
	LastAttendanceDate interface{}        `json:"last_attendance_date"`
}

func (q *Queries) GetUserWithAttendanceStats(ctx context.Context, id uuid.UUID) (GetUserWithAttendanceStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserWithAttendanceStats, id)
	var i GetUserWithAttendanceStatsRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TotalAttendances,
		&i.TotalHoursWorked,
		&i.AvgHoursPerDay,
		&i.LastAttendanceDate,
	)
	return i, err
}

const getUserWithShift = `-- name: GetUserWithShift :one
SELECT 
    u.id,
    u.full_name,
    u.username,
    u.role,
    u.email,
    u.pincode,
    u.brand_id,
    u.phone_number,
    u.created_at,
    u.updated_at,
    s.id as shift_id,
    s.name as shift_name,
    s.role as shift_role,
    s.working_days as shift_working_days,
    s.open_time as shift_open_time,
    s.close_time as shift_close_time,
    s.branch_id as shift_branch_id
FROM users u
LEFT JOIN shifts s ON u.shift_id = s.id AND s.deleted_at = 0
WHERE u.id = $1 AND u.deleted_at = 0
`

type GetUserWithShiftRow struct {
	ID               uuid.UUID          `json:"id"`
	FullName         *string            `json:"full_name"`
	Username         *string            `json:"username"`
	Role             string             `json:"role"`
	Email            *string            `json:"email"`
	Pincode          *string            `json:"pincode"`
	BrandID          pgtype.UUID        `json:"brand_id"`
	PhoneNumber      *string            `json:"phone_number"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ShiftID          pgtype.UUID        `json:"shift_id"`
	ShiftName        *string            `json:"shift_name"`
	ShiftRole        *string            `json:"shift_role"`
	ShiftWorkingDays *string            `json:"shift_working_days"`
	ShiftOpenTime    *int64             `json:"shift_open_time"`
	ShiftCloseTime   *int64             `json:"shift_close_time"`
	ShiftBranchID    pgtype.UUID        `json:"shift_branch_id"`
}

func (q *Queries) GetUserWithShift(ctx context.Context, id uuid.UUID) (GetUserWithShiftRow, error) {
	row := q.db.QueryRow(ctx, getUserWithShift, id)
	var i GetUserWithShiftRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.Pincode,
		&i.BrandID,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShiftID,
		&i.ShiftName,
		&i.ShiftRole,
		&i.ShiftWorkingDays,
		&i.ShiftOpenTime,
		&i.ShiftCloseTime,
		&i.ShiftBranchID,
	)
	return i, err
}

const getUserWithShiftAndBranch = `-- name: GetUserWithShiftAndBranch :one
SELECT 
    u.id,
    u.full_name,
    u.username,
    u.role,
    u.email,
    u.pincode,
    u.brand_id,
    u.phone_number,
    u.created_at,
    u.updated_at,
    s.id as shift_id,
    s.name as shift_name,
    s.role as shift_role,
    s.working_days as shift_working_days,
    s.open_time as shift_open_time,
    s.close_time as shift_close_time,
    b.id as branch_id,
    b.name as branch_name,
    b.address as branch_address,
    b.phone as branch_phone
FROM users u
LEFT JOIN shifts s ON u.shift_id = s.id AND s.deleted_at = 0
LEFT JOIN branches b ON s.branch_id = b.id AND b.deleted_at = 0
WHERE u.id = $1 AND u.deleted_at = 0
`

type GetUserWithShiftAndBranchRow struct {
	ID               uuid.UUID          `json:"id"`
	FullName         *string            `json:"full_name"`
	Username         *string            `json:"username"`
	Role             string             `json:"role"`
	Email            *string            `json:"email"`
	Pincode          *string            `json:"pincode"`
	BrandID          pgtype.UUID        `json:"brand_id"`
	PhoneNumber      *string            `json:"phone_number"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ShiftID          pgtype.UUID        `json:"shift_id"`
	ShiftName        *string            `json:"shift_name"`
	ShiftRole        *string            `json:"shift_role"`
	ShiftWorkingDays *string            `json:"shift_working_days"`
	ShiftOpenTime    *int64             `json:"shift_open_time"`
	ShiftCloseTime   *int64             `json:"shift_close_time"`
	BranchID         pgtype.UUID        `json:"branch_id"`
	BranchName       *string            `json:"branch_name"`
	BranchAddress    *string            `json:"branch_address"`
	BranchPhone      *string            `json:"branch_phone"`
}

func (q *Queries) GetUserWithShiftAndBranch(ctx context.Context, id uuid.UUID) (GetUserWithShiftAndBranchRow, error) {
	row := q.db.QueryRow(ctx, getUserWithShiftAndBranch, id)
	var i GetUserWithShiftAndBranchRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.Pincode,
		&i.BrandID,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShiftID,
		&i.ShiftName,
		&i.ShiftRole,
		&i.ShiftWorkingDays,
		&i.ShiftOpenTime,
		&i.ShiftCloseTime,
		&i.BranchID,
		&i.BranchName,
		&i.BranchAddress,
		&i.BranchPhone,
	)
	return i, err
}

const getUsersByBrandID = `-- name: GetUsersByBrandID :many
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE brand_id = $1 AND deleted_at = 0
ORDER BY full_name ASC
`

func (q *Queries) GetUsersByBrandID(ctx context.Context, brandID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByBrandID, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.ShiftID,
			&i.Pincode,
			&i.HashPassword,
			&i.BrandID,
			&i.PhoneNumber,
			&i.FcmToken,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE role = $1 AND deleted_at = 0
ORDER BY full_name ASC
`

func (q *Queries) GetUsersByRole(ctx context.Context, role string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.ShiftID,
			&i.Pincode,
			&i.HashPassword,
			&i.BrandID,
			&i.PhoneNumber,
			&i.FcmToken,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRolePaginated = `-- name: GetUsersByRolePaginated :many
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE role = $1 AND deleted_at = 0
ORDER BY full_name ASC
LIMIT $2 OFFSET $3
`

type GetUsersByRolePaginatedParams struct {
	Role   string `json:"role"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetUsersByRolePaginated(ctx context.Context, arg GetUsersByRolePaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByRolePaginated, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.ShiftID,
			&i.Pincode,
			&i.HashPassword,
			&i.BrandID,
			&i.PhoneNumber,
			&i.FcmToken,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByShiftID = `-- name: GetUsersByShiftID :many
SELECT u.id, u.full_name, u.username, u.role, u.email, u.shift_id, u.pincode, u.hash_password, u.brand_id, u.phone_number, u.fcm_token, u.is_active, u.created_at, u.updated_at, u.deleted_at
FROM users u
WHERE u.shift_id = $1 AND u.deleted_at = 0
ORDER BY u.full_name ASC
`

func (q *Queries) GetUsersByShiftID(ctx context.Context, shiftID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByShiftID, shiftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.ShiftID,
			&i.Pincode,
			&i.HashPassword,
			&i.BrandID,
			&i.PhoneNumber,
			&i.FcmToken,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreShift = `-- name: RestoreShift :one
UPDATE shifts SET
    deleted_at = 0
WHERE id = $1 AND deleted_at != 0
RETURNING id, name, role, working_days, open_time, close_time, branch_id, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreShift(ctx context.Context, id uuid.UUID) (Shift, error) {
	row := q.db.QueryRow(ctx, restoreShift, id)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.WorkingDays,
		&i.OpenTime,
		&i.CloseTime,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users SET
    deleted_at = 0
WHERE id = $1 AND deleted_at != 0
RETURNING id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE deleted_at = 0
AND (
    full_name ILIKE '%' || $1 || '%' OR
    username ILIKE '%' || $1 || '%' OR
    email ILIKE '%' || $1 || '%' OR
    phone_number ILIKE '%' || $1 || '%'
)
ORDER BY full_name ASC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.ShiftID,
			&i.Pincode,
			&i.HashPassword,
			&i.BrandID,
			&i.PhoneNumber,
			&i.FcmToken,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByRole = `-- name: SearchUsersByRole :many
SELECT id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at FROM users 
WHERE role = $1 AND deleted_at = 0
AND (
    full_name ILIKE '%' || $2 || '%' OR
    username ILIKE '%' || $2 || '%' OR
    email ILIKE '%' || $2 || '%'
)
ORDER BY full_name ASC
LIMIT $3 OFFSET $4
`

type SearchUsersByRoleParams struct {
	Role    string  `json:"role"`
	Column2 *string `json:"column_2"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) SearchUsersByRole(ctx context.Context, arg SearchUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsersByRole,
		arg.Role,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.ShiftID,
			&i.Pincode,
			&i.HashPassword,
			&i.BrandID,
			&i.PhoneNumber,
			&i.FcmToken,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAttendance = `-- name: SoftDeleteAttendance :one
UPDATE attendances SET
    deleted_at = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint
WHERE id = $1 AND deleted_at = 0
RETURNING id, user_id, open_date, close_date, difference, working_hours, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteAttendance(ctx context.Context, id uuid.UUID) (Attendance, error) {
	row := q.db.QueryRow(ctx, softDeleteAttendance, id)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpenDate,
		&i.CloseDate,
		&i.Difference,
		&i.WorkingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteShift = `-- name: SoftDeleteShift :one
UPDATE shifts SET
    deleted_at = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint
WHERE id = $1 AND deleted_at = 0
RETURNING id, name, role, working_days, open_time, close_time, branch_id, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteShift(ctx context.Context, id uuid.UUID) (Shift, error) {
	row := q.db.QueryRow(ctx, softDeleteShift, id)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.WorkingDays,
		&i.OpenTime,
		&i.CloseTime,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users SET
    deleted_at = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint
WHERE id = $1 AND deleted_at = 0
RETURNING id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAttendance = `-- name: UpdateAttendance :one
UPDATE attendances SET
    open_date = COALESCE($2, open_date),
    close_date = COALESCE($3, close_date),
    difference = COALESCE($4, difference),
    working_hours = COALESCE($5, working_hours)
WHERE id = $1 AND deleted_at = 0
RETURNING id, user_id, open_date, close_date, difference, working_hours, created_at, updated_at, deleted_at
`

type UpdateAttendanceParams struct {
	ID           uuid.UUID   `json:"id"`
	OpenDate     pgtype.Date `json:"open_date"`
	CloseDate    pgtype.Date `json:"close_date"`
	Difference   *int32      `json:"difference"`
	WorkingHours *int32      `json:"working_hours"`
}

func (q *Queries) UpdateAttendance(ctx context.Context, arg UpdateAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, updateAttendance,
		arg.ID,
		arg.OpenDate,
		arg.CloseDate,
		arg.Difference,
		arg.WorkingHours,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpenDate,
		&i.CloseDate,
		&i.Difference,
		&i.WorkingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateShift = `-- name: UpdateShift :one
UPDATE shifts SET
    name = COALESCE($2, name),
    role = COALESCE($3, role),
    working_days = COALESCE($4, working_days),
    open_time = COALESCE($5, open_time),
    close_time = COALESCE($6, close_time),
    branch_id = COALESCE($7, branch_id)
WHERE id = $1 AND deleted_at = 0
RETURNING id, name, role, working_days, open_time, close_time, branch_id, is_active, created_at, updated_at, deleted_at
`

type UpdateShiftParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Role        *string     `json:"role"`
	WorkingDays *string     `json:"working_days"`
	OpenTime    *int64      `json:"open_time"`
	CloseTime   *int64      `json:"close_time"`
	BranchID    pgtype.UUID `json:"branch_id"`
}

func (q *Queries) UpdateShift(ctx context.Context, arg UpdateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, updateShift,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.WorkingDays,
		arg.OpenTime,
		arg.CloseTime,
		arg.BranchID,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.WorkingDays,
		&i.OpenTime,
		&i.CloseTime,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    full_name = COALESCE($2, full_name),
    username = COALESCE($3, username),
    role = COALESCE($4, role),
    email = COALESCE($5, email),
    shift_id = COALESCE($6, shift_id),
    pincode = COALESCE($7, pincode),
    hash_password = COALESCE($8, hash_password),
    brand_id = COALESCE($9, brand_id),
    phone_number = COALESCE($10, phone_number),
    is_active = COALESCE($11, is_active)
WHERE id = $1 AND deleted_at = 0
RETURNING id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	FullName     *string     `json:"full_name"`
	Username     *string     `json:"username"`
	Role         string      `json:"role"`
	Email        *string     `json:"email"`
	ShiftID      pgtype.UUID `json:"shift_id"`
	Pincode      *string     `json:"pincode"`
	HashPassword *string     `json:"hash_password"`
	BrandID      pgtype.UUID `json:"brand_id"`
	PhoneNumber  *string     `json:"phone_number"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Username,
		arg.Role,
		arg.Email,
		arg.ShiftID,
		arg.Pincode,
		arg.HashPassword,
		arg.BrandID,
		arg.PhoneNumber,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserFCMToken = `-- name: UpdateUserFCMToken :one
UPDATE users SET
    fcm_token = $2
WHERE id = $1 AND deleted_at = 0
RETURNING id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at
`

type UpdateUserFCMTokenParams struct {
	ID       uuid.UUID `json:"id"`
	FcmToken *string   `json:"fcm_token"`
}

func (q *Queries) UpdateUserFCMToken(ctx context.Context, arg UpdateUserFCMTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFCMToken, arg.ID, arg.FcmToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserIsActive = `-- name: UpdateUserIsActive :one
UPDATE users SET
    is_active = $2
WHERE id = $1 AND deleted_at = 0
RETURNING id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at
`

type UpdateUserIsActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateUserIsActive(ctx context.Context, arg UpdateUserIsActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserIsActive, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET
    hash_password = $2
WHERE id = $1 AND deleted_at = 0
RETURNING id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	HashPassword *string   `json:"hash_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.HashPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserShift = `-- name: UpdateUserShift :one
UPDATE users SET
    shift_id = $2
WHERE id = $1 AND deleted_at = 0
RETURNING id, full_name, username, role, email, shift_id, pincode, hash_password, brand_id, phone_number, fcm_token, is_active, created_at, updated_at, deleted_at
`

type UpdateUserShiftParams struct {
	ID      uuid.UUID   `json:"id"`
	ShiftID pgtype.UUID `json:"shift_id"`
}

func (q *Queries) UpdateUserShift(ctx context.Context, arg UpdateUserShiftParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserShift, arg.ID, arg.ShiftID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.ShiftID,
		&i.Pincode,
		&i.HashPassword,
		&i.BrandID,
		&i.PhoneNumber,
		&i.FcmToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
