// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardDishSales = `-- name: GetDashboardDishSales :many
SELECT
  g.id::text AS good_id,
  g.name AS good_name,
  COALESCE(SUM(oi.quantity::numeric * oi.price), 0)::numeric AS revenue,
  COALESCE(SUM(oi.quantity::numeric), 0)::numeric AS quantity
FROM order_items oi
JOIN orders o ON o.id = oi.order_id AND o.deleted_at = 0 AND o.bill_status = 'paid'
JOIN goods g ON g.id = oi.good_id AND g.deleted_at = 0
WHERE oi.deleted_at = 0
  AND o.created_at >= $1
  AND o.created_at < $2
  AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
GROUP BY g.id, g.name
ORDER BY
  CASE
    WHEN $3::text = 'revenue' AND $4::text = 'asc' THEN COALESCE(SUM(oi.quantity::numeric * oi.price), 0)
  END ASC,
  CASE
    WHEN $3::text = 'revenue' AND $4::text = 'desc' THEN COALESCE(SUM(oi.quantity::numeric * oi.price), 0)
  END DESC,
  CASE
    WHEN $3::text = 'quantity' AND $4::text = 'asc' THEN COALESCE(SUM(oi.quantity::numeric), 0)
  END ASC,
  CASE
    WHEN $3::text = 'quantity' AND $4::text = 'desc' THEN COALESCE(SUM(oi.quantity::numeric), 0)
  END DESC,
  g.name
LIMIT $5
`

type GetDashboardDishSalesParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Column3     string             `json:"column_3"`
	Column4     string             `json:"column_4"`
	Limit       int32              `json:"limit"`
}

type GetDashboardDishSalesRow struct {
	GoodID   string         `json:"good_id"`
	GoodName string         `json:"good_name"`
	Revenue  pgtype.Numeric `json:"revenue"`
	Quantity pgtype.Numeric `json:"quantity"`
}

func (q *Queries) GetDashboardDishSales(ctx context.Context, arg GetDashboardDishSalesParams) ([]GetDashboardDishSalesRow, error) {
	rows, err := q.db.Query(ctx, getDashboardDishSales,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardDishSalesRow
	for rows.Next() {
		var i GetDashboardDishSalesRow
		if err := rows.Scan(
			&i.GoodID,
			&i.GoodName,
			&i.Revenue,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardKPIs = `-- name: GetDashboardKPIs :one
SELECT
  COALESCE(SUM(o.grand_total), 0)::numeric AS revenue,
  COUNT(DISTINCT o.id)::bigint AS checks_count,
  CASE
    WHEN COUNT(DISTINCT o.id) = 0 THEN 0
    ELSE COALESCE(SUM(o.grand_total), 0) / COUNT(DISTINCT o.id)
  END::numeric AS average_check,
  0::bigint AS returns_count,
  COALESCE(SUM(o.discount_amount), 0)::numeric AS discounts_amount,
  0::numeric AS vat_amount
FROM orders o
WHERE o.deleted_at = 0
  AND o.bill_status = 'paid'
  AND o.created_at >= $1
  AND o.created_at < $2
  AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
`

type GetDashboardKPIsParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetDashboardKPIsRow struct {
	Revenue         pgtype.Numeric `json:"revenue"`
	ChecksCount     int64          `json:"checks_count"`
	AverageCheck    pgtype.Numeric `json:"average_check"`
	ReturnsCount    int64          `json:"returns_count"`
	DiscountsAmount pgtype.Numeric `json:"discounts_amount"`
	VatAmount       pgtype.Numeric `json:"vat_amount"`
}

func (q *Queries) GetDashboardKPIs(ctx context.Context, arg GetDashboardKPIsParams) (GetDashboardKPIsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardKPIs, arg.CreatedAt, arg.CreatedAt_2)
	var i GetDashboardKPIsRow
	err := row.Scan(
		&i.Revenue,
		&i.ChecksCount,
		&i.AverageCheck,
		&i.ReturnsCount,
		&i.DiscountsAmount,
		&i.VatAmount,
	)
	return i, err
}

const getDashboardRevenueByCategories = `-- name: GetDashboardRevenueByCategories :many
WITH category_totals AS (
  SELECT
    c.id::text AS category_id,
    COALESCE(c.name,
      CASE
        WHEN $3::text = 'ru' THEN 'Без названия'
        WHEN $3::text = 'uz' THEN 'Nomsiz'
        ELSE 'Unnamed'
      END
    ) AS category_name,
    COALESCE(SUM(oi.quantity::numeric * oi.price), 0)::numeric AS revenue
  FROM orders o
  JOIN order_items oi ON oi.order_id = o.id AND oi.deleted_at = 0
  JOIN goods g ON g.id = oi.good_id AND g.deleted_at = 0
  LEFT JOIN categories c ON c.id = g.category_id AND c.deleted_at = 0
  WHERE o.deleted_at = 0
    AND o.bill_status = 'paid'
    AND o.created_at >= $1
    AND o.created_at < $2
    AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  GROUP BY c.id, c.name
)
SELECT
  category_id,
  category_name,
  revenue,
  ROUND(
    CASE
      WHEN (SELECT SUM(revenue) FROM category_totals) = 0 THEN 0::numeric
      ELSE (revenue / (SELECT SUM(revenue) FROM category_totals)) * 100
    END::numeric, 2
  ) AS percent
FROM category_totals
ORDER BY revenue DESC
`

type GetDashboardRevenueByCategoriesParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Column3     string             `json:"column_3"`
}

type GetDashboardRevenueByCategoriesRow struct {
	CategoryID   string         `json:"category_id"`
	CategoryName string         `json:"category_name"`
	Revenue      pgtype.Numeric `json:"revenue"`
	Percent      pgtype.Numeric `json:"percent"`
}

func (q *Queries) GetDashboardRevenueByCategories(ctx context.Context, arg GetDashboardRevenueByCategoriesParams) ([]GetDashboardRevenueByCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getDashboardRevenueByCategories, arg.CreatedAt, arg.CreatedAt_2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardRevenueByCategoriesRow
	for rows.Next() {
		var i GetDashboardRevenueByCategoriesRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.Revenue,
			&i.Percent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardRevenueByPaymentTypes = `-- name: GetDashboardRevenueByPaymentTypes :many
WITH payment_totals AS (
  SELECT
    COALESCE(o.payment_type::text, 'unknown') AS payment_type,
    COALESCE(SUM(o.grand_total), 0)::numeric AS revenue
  FROM orders o
  WHERE o.deleted_at = 0
    AND o.bill_status = 'paid'
    AND o.created_at >= $1
    AND o.created_at < $2
    AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
  GROUP BY o.payment_type
)
SELECT
  payment_type,
  revenue,
  ROUND(
    CASE
      WHEN (SELECT SUM(revenue) FROM payment_totals) = 0 THEN 0::numeric
      ELSE (revenue / (SELECT SUM(revenue) FROM payment_totals)) * 100
    END::numeric, 2
  ) AS percent
FROM payment_totals
ORDER BY revenue DESC
`

type GetDashboardRevenueByPaymentTypesParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetDashboardRevenueByPaymentTypesRow struct {
	PaymentType interface{}    `json:"payment_type"`
	Revenue     pgtype.Numeric `json:"revenue"`
	Percent     pgtype.Numeric `json:"percent"`
}

func (q *Queries) GetDashboardRevenueByPaymentTypes(ctx context.Context, arg GetDashboardRevenueByPaymentTypesParams) ([]GetDashboardRevenueByPaymentTypesRow, error) {
	rows, err := q.db.Query(ctx, getDashboardRevenueByPaymentTypes, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardRevenueByPaymentTypesRow
	for rows.Next() {
		var i GetDashboardRevenueByPaymentTypesRow
		if err := rows.Scan(&i.PaymentType, &i.Revenue, &i.Percent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSalesDynamics = `-- name: GetDashboardSalesDynamics :many
SELECT
  CASE
    WHEN $3::text = 'day' THEN TO_CHAR(o.created_at, 'YYYY-MM-DD')
    WHEN $3::text = 'week' THEN 'W' || TO_CHAR(o.created_at, 'YYYY-IW')
    WHEN $3::text = 'month' THEN TO_CHAR(o.created_at, 'YYYY-MM')
    ELSE TO_CHAR(o.created_at, 'YYYY-MM-DD')
  END AS period,
  CASE
    WHEN $3::text = 'day' THEN TO_CHAR(o.created_at, 'DD')
    WHEN $3::text = 'week' THEN TO_CHAR(o.created_at, 'IW')
    WHEN $3::text = 'month' THEN TO_CHAR(o.created_at, 'MM')
    ELSE TO_CHAR(o.created_at, 'DD')
  END AS label,
  COALESCE(SUM(o.grand_total), 0)::numeric AS revenue,
  COUNT(DISTINCT o.id)::bigint AS checks_count,
  CASE
    WHEN COUNT(DISTINCT o.id) = 0 THEN 0
    ELSE COALESCE(SUM(o.grand_total), 0) / COUNT(DISTINCT o.id)
  END::numeric AS average_check
FROM orders o
WHERE o.deleted_at = 0
  AND o.bill_status = 'paid'
  AND o.created_at >= $1
  AND o.created_at < $2
  AND o.branch_id = NULLIF(current_setting('app.branch_id', true), '')::uuid
GROUP BY
  CASE
    WHEN $3::text = 'day' THEN TO_CHAR(o.created_at, 'YYYY-MM-DD')
    WHEN $3::text = 'week' THEN 'W' || TO_CHAR(o.created_at, 'YYYY-IW')
    WHEN $3::text = 'month' THEN TO_CHAR(o.created_at, 'YYYY-MM')
    ELSE TO_CHAR(o.created_at, 'YYYY-MM-DD')
  END,
  CASE
    WHEN $3::text = 'day' THEN TO_CHAR(o.created_at, 'DD')
    WHEN $3::text = 'week' THEN TO_CHAR(o.created_at, 'IW')
    WHEN $3::text = 'month' THEN TO_CHAR(o.created_at, 'MM')
    ELSE TO_CHAR(o.created_at, 'DD')
  END
ORDER BY period ASC
`

type GetDashboardSalesDynamicsParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Column3     string             `json:"column_3"`
}

type GetDashboardSalesDynamicsRow struct {
	Period       interface{}    `json:"period"`
	Label        interface{}    `json:"label"`
	Revenue      pgtype.Numeric `json:"revenue"`
	ChecksCount  int64          `json:"checks_count"`
	AverageCheck pgtype.Numeric `json:"average_check"`
}

func (q *Queries) GetDashboardSalesDynamics(ctx context.Context, arg GetDashboardSalesDynamicsParams) ([]GetDashboardSalesDynamicsRow, error) {
	rows, err := q.db.Query(ctx, getDashboardSalesDynamics, arg.CreatedAt, arg.CreatedAt_2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardSalesDynamicsRow
	for rows.Next() {
		var i GetDashboardSalesDynamicsRow
		if err := rows.Scan(
			&i.Period,
			&i.Label,
			&i.Revenue,
			&i.ChecksCount,
			&i.AverageCheck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
