// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_item_modifiers.sql

package pg

import (
	"context"

	"github.com/google/uuid"
)

const createOrderItemModifier = `-- name: CreateOrderItemModifier :one
INSERT INTO order_item_modifiers (
    id,
    order_item_id,
    modifier_id,
    units
)
VALUES (
    $1, $2, $3, $4
)
RETURNING
    id,
    order_item_id,
    modifier_id,
    units,
    created_at,
    updated_at,
    deleted_at
`

type CreateOrderItemModifierParams struct {
	ID          uuid.UUID `json:"id"`
	OrderItemID uuid.UUID `json:"order_item_id"`
	ModifierID  uuid.UUID `json:"modifier_id"`
	Units       int32     `json:"units"`
}

func (q *Queries) CreateOrderItemModifier(ctx context.Context, arg CreateOrderItemModifierParams) (OrderItemModifier, error) {
	row := q.db.QueryRow(ctx, createOrderItemModifier,
		arg.ID,
		arg.OrderItemID,
		arg.ModifierID,
		arg.Units,
	)
	var i OrderItemModifier
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.ModifierID,
		&i.Units,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteOrderItemModifiersByOrderItemID = `-- name: DeleteOrderItemModifiersByOrderItemID :exec
UPDATE order_item_modifiers
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE order_item_id = $1
  AND deleted_at = 0
`

func (q *Queries) DeleteOrderItemModifiersByOrderItemID(ctx context.Context, orderItemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderItemModifiersByOrderItemID, orderItemID)
	return err
}

const getOrderItemModifiersByOrderItemID = `-- name: GetOrderItemModifiersByOrderItemID :many
SELECT
    id,
    order_item_id,
    modifier_id,
    units,
    created_at,
    updated_at,
    deleted_at
FROM order_item_modifiers
WHERE order_item_id = $1
  AND deleted_at = 0
ORDER BY created_at ASC
`

func (q *Queries) GetOrderItemModifiersByOrderItemID(ctx context.Context, orderItemID uuid.UUID) ([]OrderItemModifier, error) {
	rows, err := q.db.Query(ctx, getOrderItemModifiersByOrderItemID, orderItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItemModifier
	for rows.Next() {
		var i OrderItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.OrderItemID,
			&i.ModifierID,
			&i.Units,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemModifiersByOrderID = `-- name: ListOrderItemModifiersByOrderID :many
SELECT
    oim.id,
    oim.order_item_id,
    oim.modifier_id,
    oim.units,
    oim.created_at,
    oim.updated_at,
    oim.deleted_at
FROM order_item_modifiers oim
JOIN order_items oi ON oi.id = oim.order_item_id
WHERE oi.order_id = $1
  AND oi.deleted_at = 0
  AND oim.deleted_at = 0
ORDER BY oi.created_at ASC, oim.created_at ASC
`

func (q *Queries) ListOrderItemModifiersByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItemModifier, error) {
	rows, err := q.db.Query(ctx, listOrderItemModifiersByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItemModifier
	for rows.Next() {
		var i OrderItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.OrderItemID,
			&i.ModifierID,
			&i.Units,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
