// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDepartments = `-- name: CountDepartments :one
SELECT COUNT(*) FROM departments WHERE deleted_at = 0
`

func (q *Queries) CountDepartments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDepartmentsByStorage = `-- name: CountDepartmentsByStorage :one
SELECT COUNT(*) FROM departments WHERE storage_id = $1 AND deleted_at = 0
`

func (q *Queries) CountDepartmentsByStorage(ctx context.Context, storageID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartmentsByStorage, storageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (id, name, name_i18n, storage_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, name_i18n, storage_id, created_at, updated_at, deleted_at
`

type CreateDepartmentParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	NameI18n  pgtype.UUID `json:"name_i18n"`
	StorageID pgtype.UUID `json:"storage_id"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.ID,
		arg.Name,
		arg.NameI18n,
		arg.StorageID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.StorageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
UPDATE departments
SET deleted_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND deleted_at = 0
`

func (q *Queries) DeleteDepartment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const getAllDepartments = `-- name: GetAllDepartments :many
SELECT id, name, name_i18n, storage_id, created_at, updated_at, deleted_at
FROM departments
WHERE deleted_at = 0
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllDepartmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllDepartments(ctx context.Context, arg GetAllDepartmentsParams) ([]Department, error) {
	rows, err := q.db.Query(ctx, getAllDepartments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameI18n,
			&i.StorageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, name, name_i18n, storage_id, created_at, updated_at, deleted_at
FROM departments
WHERE id = $1 AND deleted_at = 0
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.StorageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDepartmentStats = `-- name: GetDepartmentStats :one
SELECT 
    d.id,
    d.name,
    COUNT(DISTINCT c.id) as category_count
FROM departments d
LEFT JOIN categories c ON d.id = c.department_id AND c.deleted_at = 0
WHERE d.id = $1 AND d.deleted_at = 0
GROUP BY d.id, d.name
`

type GetDepartmentStatsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	CategoryCount int64     `json:"category_count"`
}

func (q *Queries) GetDepartmentStats(ctx context.Context, id uuid.UUID) (GetDepartmentStatsRow, error) {
	row := q.db.QueryRow(ctx, getDepartmentStats, id)
	var i GetDepartmentStatsRow
	err := row.Scan(&i.ID, &i.Name, &i.CategoryCount)
	return i, err
}

const getDepartmentWithStorage = `-- name: GetDepartmentWithStorage :one
SELECT 
    d.id,
    d.name,
    d.name_i18n,
    d.storage_id,
    d.created_at,
    d.updated_at,
    s.name as storage_name,
    s.branch_id as storage_branch_id
FROM departments d
LEFT JOIN storages s ON d.storage_id = s.id AND s.deleted_at = 0
WHERE d.id = $1 AND d.deleted_at = 0
`

type GetDepartmentWithStorageRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	NameI18n        pgtype.UUID        `json:"name_i18n"`
	StorageID       pgtype.UUID        `json:"storage_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	StorageName     *string            `json:"storage_name"`
	StorageBranchID pgtype.UUID        `json:"storage_branch_id"`
}

func (q *Queries) GetDepartmentWithStorage(ctx context.Context, id uuid.UUID) (GetDepartmentWithStorageRow, error) {
	row := q.db.QueryRow(ctx, getDepartmentWithStorage, id)
	var i GetDepartmentWithStorageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.StorageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageName,
		&i.StorageBranchID,
	)
	return i, err
}

const getDepartmentsByStorageID = `-- name: GetDepartmentsByStorageID :many
SELECT id, name, name_i18n, storage_id, created_at, updated_at, deleted_at
FROM departments
WHERE storage_id = $1 AND deleted_at = 0
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetDepartmentsByStorageIDParams struct {
	StorageID pgtype.UUID `json:"storage_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) GetDepartmentsByStorageID(ctx context.Context, arg GetDepartmentsByStorageIDParams) ([]Department, error) {
	rows, err := q.db.Query(ctx, getDepartmentsByStorageID, arg.StorageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameI18n,
			&i.StorageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDepartment = `-- name: RestoreDepartment :exec
UPDATE departments
SET deleted_at = 0
WHERE id = $1 AND deleted_at != 0
`

func (q *Queries) RestoreDepartment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreDepartment, id)
	return err
}

const searchDepartments = `-- name: SearchDepartments :many
SELECT id, name, name_i18n, storage_id, created_at, updated_at, deleted_at
FROM departments
WHERE deleted_at = 0 AND name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchDepartmentsParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) SearchDepartments(ctx context.Context, arg SearchDepartmentsParams) ([]Department, error) {
	rows, err := q.db.Query(ctx, searchDepartments, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameI18n,
			&i.StorageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = COALESCE($2, name),
    name_i18n = COALESCE($3, name_i18n),
    storage_id = COALESCE($4, storage_id),
    updated_at = NOW()
WHERE id = $1 AND deleted_at = 0
RETURNING id, name, name_i18n, storage_id, created_at, updated_at, deleted_at
`

type UpdateDepartmentParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	NameI18n  pgtype.UUID `json:"name_i18n"`
	StorageID pgtype.UUID `json:"storage_id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Name,
		arg.NameI18n,
		arg.StorageID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameI18n,
		&i.StorageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
