// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                      string           `json:"id"`
	FullName                *string          `json:"fullName"`
	DateOfBirth             pgtype.Timestamp `json:"dateOfBirth"`
	OverAll                 *int32           `json:"overAll"`
	Level                   *string          `json:"level"`
	Email                   *string          `json:"email"`
	PhoneNumber             *int64           `json:"phoneNumber"`
	PasswordHash            string           `json:"passwordHash"`
	Role                    *string          `json:"role"`
	CreatedAt               pgtype.Timestamp `json:"createdAt"`
	UpdatedAt               pgtype.Timestamp `json:"updatedAt"`
	DeletedAt               *int64           `json:"deletedAt"`
	Gender                  *string          `json:"gender"`
	IsAgreedForUserContract *bool            `json:"isAgreedForUserContract"`
	IsVerified              *bool            `json:"isVerified"`
	Status                  *string          `json:"status"`
	Group                   *string          `json:"group"`
	Photo                   *string          `json:"photo"`
	XP                      *int32           `json:"XP"`
	Balance                 *int64           `json:"balance"`
	FirebaseToken           *string          `json:"firebaseToken"`
}
