// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, "fullName", "dateOfBirth", email, "phoneNumber", 
    "passwordHash", role, "isVerified", status,"googleId"
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt"
`

type CreateUserParams struct {
	ID           string         `json:"id"`
	FullName     string         `json:"fullName"`
	DateOfBirth  pgtype.Date    `json:"dateOfBirth"`
	Email        *string        `json:"email"`
	PhoneNumber  *string        `json:"phoneNumber"`
	PasswordHash *string        `json:"passwordHash"`
	Role         NullUserRole   `json:"role"`
	IsVerified   *bool          `json:"isVerified"`
	Status       NullUserStatus `json:"status"`
	GoogleId     *string        `json:"googleId"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.Role,
		arg.IsVerified,
		arg.Status,
		arg.GoogleId,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleId,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.Gender,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt" FROM users 
WHERE "deletedAt" IS NULL
ORDER BY "createdAt" DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleId,
			&i.FullName,
			&i.DateOfBirth,
			&i.OverAll,
			&i.Level,
			&i.Email,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.Role,
			&i.Gender,
			&i.IsVerified,
			&i.Status,
			&i.Group,
			&i.Photo,
			&i.XP,
			&i.Balance,
			&i.FirebaseToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersPaginated = `-- name: GetAllUsersPaginated :many
SELECT id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt" FROM users 
WHERE "deletedAt" IS NULL
ORDER BY "createdAt" DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllUsersPaginated(ctx context.Context, arg GetAllUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleId,
			&i.FullName,
			&i.DateOfBirth,
			&i.OverAll,
			&i.Level,
			&i.Email,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.Role,
			&i.Gender,
			&i.IsVerified,
			&i.Status,
			&i.Group,
			&i.Photo,
			&i.XP,
			&i.Balance,
			&i.FirebaseToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt" FROM users 
WHERE email = $1 AND "deletedAt" IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleId,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.Gender,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt" FROM users 
WHERE id = $1 AND "deletedAt" IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleId,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.Gender,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt" FROM users 
WHERE "phoneNumber" = $1 AND "deletedAt" IS NULL
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phonenumber *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phonenumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleId,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.Gender,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUsersByGroup = `-- name: GetUsersByGroup :many
SELECT id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt" FROM users 
WHERE "group" = $1 AND "deletedAt" IS NULL
ORDER BY "createdAt" DESC
`

func (q *Queries) GetUsersByGroup(ctx context.Context, group *string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByGroup, group)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleId,
			&i.FullName,
			&i.DateOfBirth,
			&i.OverAll,
			&i.Level,
			&i.Email,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.Role,
			&i.Gender,
			&i.IsVerified,
			&i.Status,
			&i.Group,
			&i.Photo,
			&i.XP,
			&i.Balance,
			&i.FirebaseToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt" FROM users 
WHERE role = $1 AND "deletedAt" IS NULL
ORDER BY "createdAt" DESC
`

func (q *Queries) GetUsersByRole(ctx context.Context, role NullUserRole) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleId,
			&i.FullName,
			&i.DateOfBirth,
			&i.OverAll,
			&i.Level,
			&i.Email,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.Role,
			&i.Gender,
			&i.IsVerified,
			&i.Status,
			&i.Group,
			&i.Photo,
			&i.XP,
			&i.Balance,
			&i.FirebaseToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByStatus = `-- name: GetUsersByStatus :many
SELECT id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt" FROM users 
WHERE status = $1 AND "deletedAt" IS NULL
ORDER BY "createdAt" DESC
`

func (q *Queries) GetUsersByStatus(ctx context.Context, status NullUserStatus) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleId,
			&i.FullName,
			&i.DateOfBirth,
			&i.OverAll,
			&i.Level,
			&i.Email,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.Role,
			&i.Gender,
			&i.IsVerified,
			&i.Status,
			&i.Group,
			&i.Photo,
			&i.XP,
			&i.Balance,
			&i.FirebaseToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users SET
    "deletedAt" = CURRENT_TIMESTAMP
WHERE id = $1 AND "deletedAt" IS NULL
RETURNING id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt"
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleId,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.Gender,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    "fullName" = COALESCE($2, "fullName"),
    "dateOfBirth" = COALESCE($3, "dateOfBirth"),
    "overAll" = COALESCE($4, "overAll"),
    email = COALESCE($5, email),
    "phoneNumber" = COALESCE($6, "phoneNumber"),
    "passwordHash" = COALESCE($7, "passwordHash"),
    role = COALESCE($8, role),
    gender = COALESCE($9, gender),
    "isVerified" = COALESCE($10, "isVerified"),
    status = COALESCE($11, status),
    "group" = COALESCE($12, "group"),
    photo = COALESCE($13, photo),
    "XP" = COALESCE($14, "XP"),
    balance = COALESCE($15, balance),
    "firebaseToken" = COALESCE($16, "firebaseToken"),
    "googleId" = COALESCE($17, "googleId")
WHERE id = $1
RETURNING id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt"
`

type UpdateUserParams struct {
	ID            string         `json:"id"`
	FullName      string         `json:"fullName"`
	DateOfBirth   pgtype.Date    `json:"dateOfBirth"`
	OverAll       *int32         `json:"overAll"`
	Email         *string        `json:"email"`
	PhoneNumber   *string        `json:"phoneNumber"`
	PasswordHash  *string        `json:"passwordHash"`
	Role          NullUserRole   `json:"role"`
	Gender        NullUserGender `json:"gender"`
	IsVerified    *bool          `json:"isVerified"`
	Status        NullUserStatus `json:"status"`
	Group         *string        `json:"group"`
	Photo         *string        `json:"photo"`
	XP            *int32         `json:"XP"`
	Balance       *int64         `json:"balance"`
	FirebaseToken *string        `json:"firebaseToken"`
	GoogleId      *string        `json:"googleId"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.DateOfBirth,
		arg.OverAll,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.Role,
		arg.Gender,
		arg.IsVerified,
		arg.Status,
		arg.Group,
		arg.Photo,
		arg.XP,
		arg.Balance,
		arg.FirebaseToken,
		arg.GoogleId,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleId,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.Gender,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET
    "passwordHash" = $2
WHERE id = $1 AND "deletedAt" IS NULL
RETURNING id, "googleId", "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, gender, "isVerified", status, "group", photo, "XP", balance, "firebaseToken", "createdAt", "updatedAt", "deletedAt"
`

type UpdateUserPasswordParams struct {
	ID           string  `json:"id"`
	PasswordHash *string `json:"passwordHash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleId,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.Gender,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
