// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    "fullName",
    "dateOfBirth",
    "overAll",
    level,
    email,
    "phoneNumber",
    "passwordHash",
    role,
    gender,
    "isAgreedForUserContract",
    "isVerified",
    status,
    "group",
    photo,
    "XP",
    balance,
    "firebaseToken"
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18
)
RETURNING id, "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, "createdAt", "updatedAt", "deletedAt", gender, "isAgreedForUserContract", "isVerified", status, "group", photo, "XP", balance, "firebaseToken"
`

type CreateUserParams struct {
	ID                      string           `json:"id"`
	FullName                *string          `json:"fullName"`
	DateOfBirth             pgtype.Timestamp `json:"dateOfBirth"`
	OverAll                 *int32           `json:"overAll"`
	Level                   *string          `json:"level"`
	Email                   *string          `json:"email"`
	PhoneNumber             *int64           `json:"phoneNumber"`
	PasswordHash            string           `json:"passwordHash"`
	Role                    *string          `json:"role"`
	Gender                  *string          `json:"gender"`
	IsAgreedForUserContract *bool            `json:"isAgreedForUserContract"`
	IsVerified              *bool            `json:"isVerified"`
	Status                  *string          `json:"status"`
	Group                   *string          `json:"group"`
	Photo                   *string          `json:"photo"`
	XP                      *int32           `json:"XP"`
	Balance                 *int64           `json:"balance"`
	FirebaseToken           *string          `json:"firebaseToken"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.DateOfBirth,
		arg.OverAll,
		arg.Level,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.Role,
		arg.Gender,
		arg.IsAgreedForUserContract,
		arg.IsVerified,
		arg.Status,
		arg.Group,
		arg.Photo,
		arg.XP,
		arg.Balance,
		arg.FirebaseToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Gender,
		&i.IsAgreedForUserContract,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, "createdAt", "updatedAt", "deletedAt", gender, "isAgreedForUserContract", "isVerified", status, "group", photo, "XP", balance, "firebaseToken" FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.DateOfBirth,
			&i.OverAll,
			&i.Level,
			&i.Email,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Gender,
			&i.IsAgreedForUserContract,
			&i.IsVerified,
			&i.Status,
			&i.Group,
			&i.Photo,
			&i.XP,
			&i.Balance,
			&i.FirebaseToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, "createdAt", "updatedAt", "deletedAt", gender, "isAgreedForUserContract", "isVerified", status, "group", photo, "XP", balance, "firebaseToken" FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Gender,
		&i.IsAgreedForUserContract,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, "fullName", "dateOfBirth", "overAll", level, email, "phoneNumber", "passwordHash", role, "createdAt", "updatedAt", "deletedAt", gender, "isAgreedForUserContract", "isVerified", status, "group", photo, "XP", balance, "firebaseToken" FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.DateOfBirth,
		&i.OverAll,
		&i.Level,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Gender,
		&i.IsAgreedForUserContract,
		&i.IsVerified,
		&i.Status,
		&i.Group,
		&i.Photo,
		&i.XP,
		&i.Balance,
		&i.FirebaseToken,
	)
	return i, err
}
