import type { Tweaks } from '../tweaks/use-tweaks';
import type { Kpi, Insight, AnalyticsPayload } from '../data/types';

import { useTranslation } from 'react-i18next';

import { Panel } from '../modules/panel';
import { KpiStrip } from '../modules/kpi-card';
import { TopDishes } from '../modules/top-dishes';
import { CategoryList } from '../modules/category-list';
import { PaymentSplit } from '../modules/payment-split';
import { InsightsList } from '../modules/insights-list';
import { SalesDynamics } from '../modules/sales-dynamics';
import { HourlyHeatmap } from '../modules/hourly-heatmap';

interface Props {
  tweaks: Tweaks;
  payload: AnalyticsPayload;
  kpis: Kpi[];
  insights: Insight[];
}

export function LayoutClassic({ tweaks, payload, kpis, insights }: Props) {
  const { t } = useTranslation('menu');
  const showCompare = tweaks.compare;
  return (
    <div className="layout-classic">
      {tweaks.sec_kpis && <KpiStrip kpis={kpis} numFormat={tweaks.numFormat} showCompare={showCompare} />}

      {tweaks.sec_sales && (
        <Panel
          title={t('analyticsDashboard.panels.salesDynamics')}
          eyebrow={t('analyticsDashboard.eyebrows.dailyRevenue')}
          action={
            <span className="panel-foot-meta mono muted">
              {showCompare
                ? t('analyticsDashboard.compareMeta.currentVsPrevious')
                : t('analyticsDashboard.compareMeta.currentPeriod')}
            </span>
          }
        >
          <SalesDynamics
            payload={payload}
            chartStyle={tweaks.chartStyle}
            showCompare={showCompare}
            numFormat={tweaks.numFormat}
          />
        </Panel>
      )}

      <div className="layout-classic-row-2">
        {tweaks.sec_categories && (
          <Panel title={t('analyticsDashboard.panels.revenueByCategory')} eyebrow={t('analyticsDashboard.eyebrows.mix')}>
            <CategoryList items={payload.current.categories} numFormat={tweaks.numFormat} limit={8} />
          </Panel>
        )}
        {tweaks.sec_payments && (
          <Panel title={t('analyticsDashboard.panels.paymentTypes')} eyebrow={t('analyticsDashboard.eyebrows.split')}>
            <PaymentSplit items={payload.current.payment_types} numFormat={tweaks.numFormat} variant="donut" />
          </Panel>
        )}
      </div>

      {tweaks.sec_dishes && (
        <Panel
          title={t('analyticsDashboard.panels.topDishes')}
          eyebrow={t('analyticsDashboard.eyebrows.sortedByRevenueTop', { count: payload.current.dish_sales.length })}
        >
          <TopDishes items={payload.current.dish_sales} numFormat={tweaks.numFormat} style={tweaks.dishesStyle} />
        </Panel>
      )}

      <div className="layout-classic-row-2">
        {tweaks.sec_insights && (
          <Panel title={t('analyticsDashboard.panels.insights')} eyebrow={t('analyticsDashboard.eyebrows.autoGenerated')}>
            <InsightsList items={insights} variant="grid" />
          </Panel>
        )}
        {tweaks.sec_heatmap && (
          <Panel title={t('analyticsDashboard.panels.hourlyActivity')} eyebrow={t('analyticsDashboard.eyebrows.whenAreWeBusy')}>
            <HourlyHeatmap />
          </Panel>
        )}
      </div>
    </div>
  );
}
