import type { IMealsItem } from "src/types/meals";

// Mock order data - production'da API'dan olasiz
export const mockMeals: IMealsItem[] = [
    {
        id: '1',
        sku: '16H9UR0',
        orderNumber: '#60100',
        name: 'Osh',
        section: 'Milliy Taom',
        stock: 'Oshxona',
        unit: 'kg',
        category: 'Taom',
        originalPrice: 50000,
        price: 30000,
        profit: 35,
        profitnumber: 20000,
        quantity: 10,
        coverUrl: 'https://www.shutterstock.com/shutterstock/photos/2488727069/display_1500/stock-photo-palov-osh-which-is-one-of-uzbek-cuisine-2488727069.jpg',

        createdAt: new Date().toISOString() as any,
        customer: {
            id: '1',
            name: 'John Doe',
            email: 'john@example.com',
            avatarUrl: 'https://www.shutterstock.com/shutterstock/photos/2488727069/display_1500/stock-photo-palov-osh-which-is-one-of-uzbek-cuisine-2488727069.jpg',
            ipAddress: '192.168.1.1',
        },
        items: [
            {
                id: '1',
                sku: '16H9UR0',
                name: 'Palov',
                unit: 'kg',
                category: 'Taom',
                originalPrice: 50000,
                quantity: 1,
                price: 50000,
                coverUrl: 'https://www.shutterstock.com/shutterstock/photos/2488727069/display_1500/stock-photo-palov-osh-which-is-one-of-uzbek-cuisine-2488727069.jpg',
            },
        ],
        delivery: {
            shipBy: 'DHL',
            speedy: 'Standard',
            trackingNumber: 'SPX037739199373',
        },
        shippingAddress: {
            fullAddress: '123 Main St, City, Country',
            phoneNumber: '123-456-7890',
        },
        payment: {
            cardType: 'mastercard',
            cardNumber: '**** **** **** 5678',
        },
        history: {
            orderTime: new Date().toISOString() as any,
            paymentTime: new Date().toISOString() as any,
            deliveryTime: new Date().toISOString() as any,
            completionTime: new Date().toISOString() as any,
            timeline: [],
        },
        subtotal: 50000,
        shipping: 10,
        discount: 10,
        taxes: 10,
        totalAmount: 50010,
        totalQuantity: 1,
        status: 'pending',
    },
    {
        id: '2',
        sku: '16H9UR1',
        orderNumber: '#60101',
        name: 'Haggi',
        section: 'Fast Food',
        stock: 'Oshxona',
        unit: 'dona',
        category: 'Taom',
        originalPrice: 25000,
        price: 15000,
        profit: 40,
        profitnumber: 10000,
        quantity: 20,
        coverUrl: 'https://imageproxy.wolt.com/menu/menu-images/669105f598f9f8adccf97e39/97fe25e4-d740-11f0-b813-7aeae949e502_d966f41d881e3f7d54e63cbaa4d7587a.png',
        createdAt: new Date().toISOString() as any,
        customer: {
            id: '2',
            name: 'Jane Smith',
            email: 'jane@example.com',
            avatarUrl: 'https://api-dev-minimal-v6.vercel.app/images/avatars/avatar_2.jpg',
            ipAddress: '192.168.1.2',
        },
        items: [
            {
                id: '1',
                sku: '16H9UR1',
                name: 'Qabuli',
                unit: 'dona',
                category: 'Taom',
                originalPrice: 35000,
                quantity: 2,
                price: 35000,
                coverUrl: 'https://imageproxy.wolt.com/menu/menu-images/669105f598f9f8adccf97e39/97fe25e4-d740-11f0-b813-7aeae949e502_d966f41d881e3f7d54e63cbaa4d7587a.png',
            },
        ],
        delivery: {
            shipBy: 'FedEx',
            speedy: 'Express',
            trackingNumber: 'SPX037739199374',
        },
        shippingAddress: {
            fullAddress: '456 Oak Ave, Town, Country',
            phoneNumber: '098-765-4321',
        },
        payment: {
            cardType: 'visa',
            cardNumber: '**** **** **** 1234',
        },
        history: {
            orderTime: new Date().toISOString() as any,
            paymentTime: new Date().toISOString() as any,
            deliveryTime: new Date().toISOString() as any,
            completionTime: new Date().toISOString() as any,
            timeline: [],
        },
        subtotal: 70000,
        shipping: 15,
        discount: 20,
        taxes: 39.5,
        totalAmount: 70034.5,
        totalQuantity: 2,
        status: 'completed',
    },
    {
        id: '3',
        sku: '16H9UR0',
        orderNumber: '#60100',
        name: 'Uyg\'ur lag\'mon',
        section: 'Uyg\'ur milliy taom',
        stock: 'Oshxona',
        unit: 'kg',
        category: 'Taom',
        originalPrice: 40000,
        price: 60000,
        profitnumber: 20000,
        profit: 33,
        quantity: 10,
        coverUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGJcGxMOOCjpMV6eYxJuH_4wa-NE-2ztlwjg&s',
        createdAt: new Date().toISOString() as any,
        customer: {
            id: '1',
            name: 'John Doe',
            email: 'john@example.com',
            avatarUrl: 'https://api-dev-minimal-v6.vercel.app/images/avatars/avatar_1.jpg',
            ipAddress: '192.168.1.1',
        },
        items: [
            {
                id: '1',
                sku: '16H9UR0',
                name: 'Palov',
                unit: 'kg',
                category: 'Taom',
                originalPrice: 50000,
                quantity: 1,
                price: 50000,
                coverUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGJcGxMOOCjpMV6eYxJuH_4wa-NE-2ztlwjg&s',
            },
        ],
        delivery: {
            shipBy: 'DHL',
            speedy: 'Standard',
            trackingNumber: 'SPX037739199373',
        },
        shippingAddress: {
            fullAddress: '123 Main St, City, Country',
            phoneNumber: '123-456-7890',
        },
        payment: {
            cardType: 'mastercard',
            cardNumber: '**** **** **** 5678',
        },
        history: {
            orderTime: new Date().toISOString() as any,
            paymentTime: new Date().toISOString() as any,
            deliveryTime: new Date().toISOString() as any,
            completionTime: new Date().toISOString() as any,
            timeline: [],
        },
        subtotal: 50000,
        shipping: 10,
        discount: 10,
        taxes: 10,
        totalAmount: 50010,
        totalQuantity: 1,
        status: 'pending',
    },
    {
        id: '4',
        sku: '16H9UR1',
        orderNumber: '#60101',
        name: 'Manti',
        section: 'Milliy taom',
        stock: 'Oshxona',
        unit: 'dona',
        category: 'Taom',
        originalPrice: 12000,
        price: 6000,
        profit: 50,
        profitnumber: 6000,
        quantity: 20,
        coverUrl: 'https://cdn.tveda.ru/thumbs/13f/13fb7f86894176fbf3137bc728d083f0/3252227abdbd4aa2064f9a01fff6d164.jpg',
        createdAt: new Date().toISOString() as any,
        customer: {
            id: '2',
            name: 'Jane Smith',
            email: 'jane@example.com',
            avatarUrl: 'https://api-dev-minimal-v6.vercel.app/images/avatars/avatar_2.jpg',
            ipAddress: '192.168.1.2',
        },
        items: [
            {
                id: '1',
                sku: '16H9UR1',
                name: 'Qabuli',
                unit: 'dona',
                category: 'Taom',
                originalPrice: 35000,
                quantity: 2,
                price: 35000,
                coverUrl: 'https://cdn.tveda.ru/thumbs/13f/13fb7f86894176fbf3137bc728d083f0/3252227abdbd4aa2064f9a01fff6d164.jpg',
            },
        ],
        delivery: {
            shipBy: 'FedEx',
            speedy: 'Express',
            trackingNumber: 'SPX037739199374',
        },
        shippingAddress: {
            fullAddress: '456 Oak Ave, Town, Country',
            phoneNumber: '098-765-4321',
        },
        payment: {
            cardType: 'visa',
            cardNumber: '**** **** **** 1234',
        },
        history: {
            orderTime: new Date().toISOString() as any,
            paymentTime: new Date().toISOString() as any,
            deliveryTime: new Date().toISOString() as any,
            completionTime: new Date().toISOString() as any,
            timeline: [],
        },
        subtotal: 70000,
        shipping: 15,
        discount: 20,
        taxes: 39.5,
        totalAmount: 70034.5,
        totalQuantity: 2,
        status: 'completed',
    },
];