import type { ICompound } from "src/types/compounds";

// Mock compound data - production'da API'dan olasiz
export const mockOrders: ICompound[] = [
    {
        id: '1',
        name: 'Chesnokli sous',
        measurement: 'kg',
        description: 'Garlic sauce',
        price: 6000,
        quantity: 0.7,
        picture_url: 'https://www.russianfood.com/dycontent/images_upl/604/big_603346.jpg',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        department_id: '1',
        department_name: 'Oshxona',
    },
    {
        id: '2',
        name: 'Bon fele',
        measurement: 'kg',
        description: 'Meat dish',
        price: 590000,
        quantity: 1.7,
        picture_url: 'https://185504.selcdn.ru/static/optoffka.reshop.kz/catalog/1058/563192165bc6a9d4b8983_original.jpg',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        department_id: '2',
        department_name: 'Taom',
    },
    {
        id: '3',
        name: 'Tvorog',
        measurement: 'kg',
        description: 'Cottage cheese',
        price: 34990,
        quantity: 4.5,
        picture_url: 'https://thumb.tildacdn.com/tild6336-3034-4062-a336-366533633235/-/resize/824x/-/format/webp/bowl-3366480_1920.jpg',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        department_id: '1',
        department_name: 'Oshxona',
    },
    {
        id: '4',
        name: 'Pesto sous',
        measurement: 'kg',
        description: 'Pesto sauce',
        price: 60600,
        quantity: 1.5,
        picture_url: 'https://basket-01.wbbasket.ru/vol101/part10140/10140166/images/big/1.webp',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        department_id: '2',
        department_name: 'Taom',
    },
];