import type { ISemifinishedItem } from "src/types/semifinished";

// Mock order data - production'da API'dan olasiz
export const mockOrders: ISemifinishedItem[] = [
    {
        id: '1',
        sku: '16H9UR0',
        orderNumber: '#60100',
        name: 'Chesnokli sous',
        unit: 'kg',
        category: 'Oshxona',
        originalPrice: 10000,
        costprice: 6000,
        quantity: 0.7,
        coverUrl: 'https://www.russianfood.com/dycontent/images_upl/604/big_603346.jpg',
        createdAt: new Date().toISOString() as any,
        customer: {
            id: '1',
            name: 'John Doe',
            email: 'john@example.com',
            avatarUrl: 'https://api-dev-minimal-v6.vercel.app/images/avatars/avatar_1.jpg',
            ipAddress: '192.168.1.1',
        },
        items: [
            {
                id: '1',
                sku: '16H9UR0',
                name: 'Palov',
                unit: 'kg',
                category: 'Taom',
                originalPrice: 50000,
                quantity: 1,
                price: 50000,
                coverUrl: 'https://www.russianfood.com/dycontent/images_upl/604/big_603346.jpg',
            },
        ],
        delivery: {
            shipBy: 'DHL',
            speedy: 'Standard',
            trackingNumber: 'SPX037739199373',
        },
        shippingAddress: {
            fullAddress: '123 Main St, City, Country',
            phoneNumber: '123-456-7890',
        },
        payment: {
            cardType: 'mastercard',
            cardNumber: '**** **** **** 5678',
        },
        history: {
            orderTime: new Date().toISOString() as any,
            paymentTime: new Date().toISOString() as any,
            deliveryTime: new Date().toISOString() as any,
            completionTime: new Date().toISOString() as any,
            timeline: [],
        },
        subtotal: 50000,
        shipping: 10,
        discount: 10,
        taxes: 10,
        totalAmount: 50010,
        totalQuantity: 1,
        status: 'pending',
    },
    {
        id: '2',
        sku: '16H9UR1',
        orderNumber: '#60101',
        name: 'Bon fele',
        unit: 'kg',
        category: 'Taom',
        originalPrice: 35000,
        costprice: 590000,
        quantity: 1.7,
        coverUrl: 'https://185504.selcdn.ru/static/optoffka.reshop.kz/catalog/1058/563192165bc6a9d4b8983_original.jpg',
        createdAt: new Date().toISOString() as any,
        customer: {
            id: '2',
            name: 'Jane Smith',
            email: 'jane@example.com',
            avatarUrl: 'https://api-dev-minimal-v6.vercel.app/images/avatars/avatar_2.jpg',
            ipAddress: '192.168.1.2',
        },
        items: [
            {
                id: '1',
                sku: '16H9UR1',
                name: 'Qabuli',
                unit: 'dona',
                category: 'Taom',
                originalPrice: 35000,
                quantity: 2,
                price: 35000,
                coverUrl: 'https://185504.selcdn.ru/static/optoffka.reshop.kz/catalog/1058/563192165bc6a9d4b8983_original.jpg',
            },
        ],
        delivery: {
            shipBy: 'FedEx',
            speedy: 'Express',
            trackingNumber: 'SPX037739199374',
        },
        shippingAddress: {
            fullAddress: '456 Oak Ave, Town, Country',
            phoneNumber: '098-765-4321',
        },
        payment: {
            cardType: 'visa',
            cardNumber: '**** **** **** 1234',
        },
        history: {
            orderTime: new Date().toISOString() as any,
            paymentTime: new Date().toISOString() as any,
            deliveryTime: new Date().toISOString() as any,
            completionTime: new Date().toISOString() as any,
            timeline: [],
        },
        subtotal: 70000,
        shipping: 15,
        discount: 20,
        taxes: 39.5,
        totalAmount: 70034.5,
        totalQuantity: 2,
        status: 'completed',
    },
    {
        id: '3',
        sku: '16H9UR0',
        orderNumber: '#60100',
        name: 'Tvorog',
        unit: 'kg',
        category: 'Taom',
        originalPrice: 50000,
        costprice: 34990,
        quantity: 4.5,
        coverUrl: 'https://thumb.tildacdn.com/tild6336-3034-4062-a336-366533633235/-/resize/824x/-/format/webp/bowl-3366480_1920.jpg',
        createdAt: new Date().toISOString() as any,
        customer: {
            id: '1',
            name: 'John Doe',
            email: 'john@example.com',
            avatarUrl: 'https://api-dev-minimal-v6.vercel.app/images/avatars/avatar_1.jpg',
            ipAddress: '192.168.1.1',
        },
        items: [
            {
                id: '1',
                sku: '16H9UR0',
                name: 'Palov',
                unit: 'kg',
                category: 'Taom',
                originalPrice: 50000,
                quantity: 1,
                price: 50000,
                coverUrl: 'https://thumb.tildacdn.com/tild6336-3034-4062-a336-366533633235/-/resize/824x/-/format/webp/bowl-3366480_1920.jpg',
            },
        ],
        delivery: {
            shipBy: 'DHL',
            speedy: 'Standard',
            trackingNumber: 'SPX037739199373',
        },
        shippingAddress: {
            fullAddress: '123 Main St, City, Country',
            phoneNumber: '123-456-7890',
        },
        payment: {
            cardType: 'mastercard',
            cardNumber: '**** **** **** 5678',
        },
        history: {
            orderTime: new Date().toISOString() as any,
            paymentTime: new Date().toISOString() as any,
            deliveryTime: new Date().toISOString() as any,
            completionTime: new Date().toISOString() as any,
            timeline: [],
        },
        subtotal: 50000,
        shipping: 10,
        discount: 10,
        taxes: 10,
        totalAmount: 50010,
        totalQuantity: 1,
        status: 'pending',
    },
    {
        id: '4',
        sku: '16H9UR1',
        orderNumber: '#60101',
        name: 'Pesto sous',
        unit: 'kg',
        category: 'Taom',
        originalPrice: 35000,
        costprice: 60600,
        quantity: 1.5,
        coverUrl: 'https://basket-01.wbbasket.ru/vol101/part10140/10140166/images/big/1.webp',
        createdAt: new Date().toISOString() as any,
        customer: {
            id: '2',
            name: 'Jane Smith',
            email: 'jane@example.com',
            avatarUrl: 'https://api-dev-minimal-v6.vercel.app/images/avatars/avatar_2.jpg',
            ipAddress: '192.168.1.2',
        },
        items: [
            {
                id: '1',
                sku: '16H9UR1',
                name: 'Qabuli',
                unit: 'dona',
                category: 'Taom',
                originalPrice: 35000,
                quantity: 2,
                price: 35000,
                coverUrl: 'https://basket-01.wbbasket.ru/vol101/part10140/10140166/images/big/1.webp',
            },
        ],
        delivery: {
            shipBy: 'FedEx',
            speedy: 'Express',
            trackingNumber: 'SPX037739199374',
        },
        shippingAddress: {
            fullAddress: '456 Oak Ave, Town, Country',
            phoneNumber: '098-765-4321',
        },
        payment: {
            cardType: 'visa',
            cardNumber: '**** **** **** 1234',
        },
        history: {
            orderTime: new Date().toISOString() as any,
            paymentTime: new Date().toISOString() as any,
            deliveryTime: new Date().toISOString() as any,
            completionTime: new Date().toISOString() as any,
            timeline: [],
        },
        subtotal: 70000,
        shipping: 15,
        discount: 20,
        taxes: 39.5,
        totalAmount: 70034.5,
        totalQuantity: 2,
        status: 'completed',
    },
];